'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { BookOpen, Flame, Music2, Play, Sparkles, Trophy, Volume2 } from 'lucide-react';

type Screen = 'home' | 'songs' | 'game' | 'result' | 'dictionary';
const vocab = [
  ['食べ物','たべもの','tabemono','đồ ăn'],['友達','ともだち','tomodachi','bạn bè'],['学校','がっこう','gakkou','trường học'],['音楽','おんがく','ongaku','âm nhạc'],['大好き','だいすき','daisuki','rất thích'],['おはよう','おはよう','ohayou','chào buổi sáng']
];
const songs = [
  ['桜ステップ','Sakura Step','128','N5','Easy','#ff5f91'],['星空ドライブ','Hoshizora Drive','154','N4','Normal','#7857ff'],['東京ネオン','Tokyo Neon','178','N3','Hard','#19c6d3']
];
const arrowKeys = ['ArrowLeft','ArrowDown','ArrowUp','ArrowRight'];
const arrowGlyphs = ['←','↓','↑','→'];

export default function Home() {
  const [screen,setScreen]=useState<Screen>('home');
  const [selected,setSelected]=useState(0);
  const [score,setScore]=useState(0);
  const [combo,setCombo]=useState(0);
  const [word,setWord]=useState(0);
  const [progress,setProgress]=useState(0);
  const [judgment,setJudgment]=useState('READY?');
  const [active,setActive]=useState(-1);
  const [phase,setPhase]=useState<'answer'|'sequence'|'beat'>('answer');
  const [sequence,setSequence]=useState<number[]>([0,1,3]);
  const [entered,setEntered]=useState<number[]>([]);
  const [round,setRound]=useState(1);
  const [roundTime,setRoundTime]=useState(6);
  const [beat,setBeat]=useState(0);
  const [correct,setCorrect]=useState(0);
  const options=useMemo(()=>{const column=round%3===0?2:3;return [vocab[word][column],vocab[(word+2)%vocab.length][column],vocab[(word+4)%vocab.length][column]].sort(()=>.5-Math.random())},[word,round]);
  const makeRound=useCallback(()=>{setWord(w=>(w+1)%vocab.length);setRound(r=>r+1);setPhase('answer');setEntered([]);setRoundTime(6);setJudgment('DỊCH TỪ');setSequence(Array.from({length:Math.min(3+Math.floor(round/3),7)},(_,i)=>(round*3+i*2)%4))},[round]);
  const start=()=>{setScore(0);setCombo(0);setProgress(0);setWord(0);setCorrect(0);setRound(1);setRoundTime(6);setSequence([0,1,3]);setEntered([]);setPhase('answer');setJudgment('DỊCH TỪ');setScreen('game')};
  const chooseAnswer=useCallback((answer:string)=>{if(phase!=='answer')return;const target=vocab[word][round%3===0?2:3];if(answer===target){setCorrect(c=>c+1);setScore(s=>s+500);setJudgment('CHÍNH XÁC!');setPhase('sequence')}else{setCombo(0);setJudgment('SAI NGHĨA');setTimeout(()=>setPhase('sequence'),450)}},[phase,word,round]);
  const pressArrow=useCallback((lane:number)=>{if(screen!=='game'||phase!=='sequence')return;setActive(lane);setTimeout(()=>setActive(-1),120);const expected=sequence[entered.length];if(lane===expected){const next=[...entered,lane];setEntered(next);if(next.length===sequence.length){setPhase('beat');setJudgment('SPACE!')}}else{setEntered([]);setCombo(0);setJudgment('THỬ LẠI!')}},[screen,phase,sequence,entered]);
  const hitBeat=useCallback(()=>{if(phase!=='beat')return;const distance=Math.abs(50-beat);const result=distance<9?'PERFECT':distance<18?'GREAT':'GOOD';const points=distance<9?1500:distance<18?1000:600;setJudgment(result);setScore(s=>s+points+combo*25);setCombo(c=>c+1);setTimeout(makeRound,500)},[phase,beat,combo,makeRound]);
  useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if(screen!=='game')return;if(e.code==='Space'){e.preventDefault();hitBeat();return}if(phase==='answer'&&['Digit1','Digit2','Digit3'].includes(e.code)){chooseAnswer(options[Number(e.code.slice(-1))-1]);return}const lane=arrowKeys.indexOf(e.key);if(lane>=0){e.preventDefault();pressArrow(lane)}};addEventListener('keydown',onKey);return()=>removeEventListener('keydown',onKey)},[screen,phase,options,chooseAnswer,pressArrow,hitBeat]);
  useEffect(()=>{if(screen!=='game')return;const started=Date.now();const duration=150000;const t=setInterval(()=>{const elapsed=Date.now()-started;setProgress(Math.min(100,elapsed/duration*100));setBeat((elapsed/12)%100);if(elapsed>=duration)setScreen('result')},50);return()=>clearInterval(t)},[screen]);
  useEffect(()=>{if(screen!=='game'||phase==='beat')return;const t=setInterval(()=>setRoundTime(v=>{if(v<=1){setCombo(0);setJudgment('TIME OUT');setTimeout(makeRound,350);return 6}return v-1}),1000);return()=>clearInterval(t)},[screen,phase,makeRound]);
  useEffect(()=>{
    const controller=new AbortController();
    const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>void}}).modelContext;
    if(!context?.registerTool)return;
    try{context.registerTool({name:'start_rhythm_song',title:'Bắt đầu bài hát',description:'Chọn và bắt đầu một bài hát trong Nihon Beat.',inputSchema:{type:'object',properties:{songIndex:{type:'integer',minimum:0,maximum:2}},required:['songIndex'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input:unknown)=>{const i=(input as {songIndex:number}).songIndex;if(!Number.isInteger(i)||i<0||i>=songs.length)throw new Error('songIndex không hợp lệ');setSelected(i);setScore(0);setCombo(0);setProgress(0);setScreen('game');return{status:'started',song:songs[i][1]}}},{signal:controller.signal})}catch{/* Browser chưa hỗ trợ WebMCP. */}
    return()=>controller.abort();
  },[]);
  const speak=(text:string)=>speechSynthesis.speak(new SpeechSynthesisUtterance(text));

  if(screen==='game') return <main className="game audition"><div className="hud"><button onClick={()=>setScreen('songs')}>EXIT</button><div><small>SCORE</small><b>{score.toLocaleString()}</b></div><div className="now"><b>{songs[selected][0]}</b><small>{songs[selected][1]} · {songs[selected][2]} BPM · 02:30</small></div><div><small>COMBO</small><b>{combo}</b></div></div><div className="bar"><i style={{width:`${progress}%`}}/></div><div className="dance-bg"><div className="spotlight left"/><div className="spotlight right"/><div className="crowd"/></div><section className="audition-stage"><div className="round-info"><span>ROUND {round}</span><b>{roundTime}s</b></div><article className="quiz-card"><span>{round%3===0?'DỊCH SANG ROMAJI':'DỊCH SANG TIẾNG VIỆT'}</span><h1>{vocab[word][0]}</h1><p>{vocab[word][1]}</p>{phase==='answer'?<div className="answer-options">{options.map((o,i)=><button key={o} onClick={()=>chooseAnswer(o)}><kbd>{i+1}</kbd>{round%3===0&&o===vocab[word][3]?vocab[word][2]:o}</button>)}</div>:<div className="answer-reveal"><b>{vocab[word][2]}</b><span>{vocab[word][3]}</span></div>}</article><div className="dance-avatar"><div className="dancer-head">◡ ‿ ◡</div><div className="dancer-body">日</div></div><div className={`command-panel ${phase}`}><strong className="judgment">{judgment}</strong><div className="sequence">{sequence.map((lane,i)=><span className={`c${lane} ${i<entered.length?'done':''} ${i===entered.length?'current':''}`} key={`${lane}-${i}`}>{arrowGlyphs[lane]}</span>)}</div>{phase==='beat'&&<div className="beat-track"><i style={{left:`${beat}%`}}/><b>SPACE</b></div>}<div className="touch-controls">{arrowGlyphs.map((glyph,lane)=><button className={`c${lane} ${active===lane?'pressed':''}`} onPointerDown={()=>pressArrow(lane)} key={glyph}>{glyph}</button>)}<button className="space-button" onPointerDown={hitBeat}>SPACE</button></div><p>{phase==='answer'?'Chọn nghĩa bằng phím 1 · 2 · 3':phase==='sequence'?'Nhập chuỗi phím mũi tên':'Nhấn SPACE khi vệt sáng vào giữa'}</p></div></section><aside className="audition-side"><span>VOCAB HIT</span><b>{correct}</b><small>/ {round} từ</small><button onClick={()=>speak(vocab[word][1])}><Volume2/> Phát âm</button></aside></main>;
  if(screen==='result') return <main className="result"><section><span className="eyebrow">DANCE COMPLETE!</span><div className="rank">A</div><h1>{songs[selected][0]}</h1><p>{songs[selected][1]}</p><b className="final">{score.toLocaleString()}</b><div className="stats"><span><b>{round}</b>Lượt</span><span><b>{correct}</b>Từ đúng</span><span><b>{combo}</b>Combo</span><span><b>{Math.round(correct/Math.max(1,round)*100)}%</b>Chính xác</span></div><div className="actions"><button onClick={start}><Play/> Chơi lại</button><button onClick={()=>setScreen('dictionary')}><BookOpen/> Ôn từ</button><button onClick={()=>setScreen('home')}>Về menu</button></div></section></main>;
  return <main className="app"><header><button className="brand" onClick={()=>setScreen('home')}><span>日</span><b>Nihon Beat<small>Learn Japanese in rhythm</small></b></button><nav><button className={screen==='home'?'on':''} onClick={()=>setScreen('home')}>Trang chủ</button><button className={screen==='songs'?'on':''} onClick={()=>setScreen('songs')}>Bài hát</button><button className={screen==='dictionary'?'on':''} onClick={()=>setScreen('dictionary')}>Từ điển</button></nav><div className="user"><span>12</span><b>Hana<small>Level 8</small></b></div></header>
  {screen==='home'&&<div className="home"><section className="hero"><div><span className="eyebrow"><Sparkles/> HỌC TIẾNG NHẬT QUA ÂM NHẬC</span><h1>Chạm đúng nhịp.<br/><em>Nhớ đúng từ.</em></h1><p>Mỗi phím bấm là một từ vựng mới. Bắt đầu hành trình từ N5 đến N1 theo cách vui nhất.</p><div className="actions"><button onClick={()=>setScreen('songs')}><Play/> Chơi ngay</button><button onClick={()=>setScreen('dictionary')}><BookOpen/> Từ điển của tôi</button></div><div className="streak"><Flame/><span><b>7 ngày liên tiếp!</b><small>Thêm 1 ngày nữa để nhận 100 XP</small></span></div></div><div className="mascot"><div className="head">◡ ‿ ◡</div><div className="body">日</div><span>♪</span><b>Let’s go!<small>がんばって！</small></b></div></section><aside><section className="daily"><span className="eyebrow">DAILY CHALLENGE</span><h3>Tokyo Morning</h3><p>Hoàn thành trước 23:59</p><button onClick={start}><Play/></button></section><section className="today"><h3>Tiến độ hôm nay</h3><div><span>13<small>/ 20 từ</small></span></div><p>Chỉ còn <b>7 từ</b> để đạt mục tiêu!</p></section></aside><section className="continue"><div><span className="eyebrow">TIẾP TỤC HÀNH TRÌNH</span><h2>N5 · Chào hỏi & Hằng ngày</h2></div><article><div className="album">桜<Music2/></div><div><h3>桜ステップ <small>Sakura Step</small></h3><p>128 BPM · 12 từ vựng</p><i><b/></i></div><strong>84,650<small>BEST SCORE</small></strong><button onClick={start}><Play/></button></article></section><section className="quick"><span><Trophy/><b>18</b>Bài đã xong</span><span><BookOpen/><b>126</b>Từ đã học</span><span><Flame/><b>42</b>Combo cao nhất</span></section></div>}
  {screen==='songs'&&<section className="page"><div className="title"><span className="eyebrow">FREE PLAY</span><h1>Chọn giai điệu của bạn</h1><p>Mỗi bài hát là một chủ đề từ vựng mới.</p></div><div className="filters"><button>Tất cả</button><button>N5</button><button>N4</button><button>N3</button></div><div className="songs">{songs.map((s,i)=><article className={selected===i?'selected':''} onClick={()=>setSelected(i)} key={s[0]}><div className="album" style={{background:s[5]}}>{s[0][0]}<Music2/></div><div><small>{s[3]}</small><h2>{s[0]}</h2><p>{s[1]}</p></div><strong>{s[4]}<small>{s[2]} BPM · {12+i*6} từ</small></strong><button onClick={()=>{setSelected(i);start()}}><Play/></button></article>)}</div></section>}
  {screen==='dictionary'&&<section className="page"><div className="title"><span className="eyebrow">MY VOCABULARY</span><h1>Từ điển của tôi</h1><p>Những từ bạn đã gặp trên hành trình âm nhạc.</p></div><div className="words">{vocab.map((w,i)=><article key={w[2]}><div><span className={`master m${i%3}`}>{i%3===0?'Đã thuộc':i%3===1?'Đang học':'Cần ôn'}</span><h2>{w[0]}</h2><p>{w[1]} · {w[2]}</p><b>{w[3]}</b></div><button onClick={()=>speak(w[1])}><Volume2/></button></article>)}</div></section>}</main>;
}
