import type { VocabularyEntry } from './hsk2-vocabulary';

/**
 * CẤP ĐỘ BÌNH THƯỜNG: Collocations (Kết hợp từ thường gặp: Động-Tân, Động-Bổ, Định-Trung)
 * Tổng cộng: 60 mục
 */
export const collocationsVocabulary: VocabularyEntry[] = [
  ["喝茶", "hē chá", "he cha", "uống trà", "HSK 2"],
  ["看电影", "kàn diànyǐng", "kan dianying", "xem phim", "HSK 2"],
  ["打电话", "dǎ diànhuà", "da dianhua", "gọi điện thoại", "HSK 2"],
  ["吃米饭", "chī mǐfàn", "chi mifan", "ăn cơm trắng", "HSK 2"],
  ["听音乐", "tīng yīnyuè", "ting yinyue", "nghe nhạc", "HSK 2"],
  ["做作业", "zuò zuòyè", "zuo zuoye", "làm bài tập", "HSK 2"],
  ["去学校", "qù xuéxiào", "qu xuexiao", "đến trường học", "HSK 2"],
  ["买东西", "mǎi dōngxi", "mai dongxi", "mua sắm đồ đạc", "HSK 2"],
  ["学汉语", "xué hànyǔ", "xue hanyu", "học tiếng Trung", "HSK 2"],
  ["开汽车", "kāi qìchē", "kai qiche", "lái xe ô tô", "HSK 2"],
  ["洗衣服", "xǐ yīfu", "xi yifu", "giặt quần áo", "HSK 2"],
  ["跑步锻炼", "pǎobù duànliàn", "paobu duanlian", "chạy bộ tập thể dục", "HSK 3"],
  ["工作忙碌", "gōngzuò mánglù", "gongzuo manglu", "công việc bận rộn", "HSK 3"],
  ["打篮球", "dǎ lánqiú", "da lanqiu", "chơi bóng rổ", "HSK 2"],
  ["唱歌跳舞", "chànggē tiàowǔ", "changge tiaowu", "ca hát nhảy múa", "HSK 2"],
  ["漂亮衣服", "piàoliang yīfu", "piaoliang yifu", "quần áo đẹp", "HSK 2"],
  ["好朋友", "hǎo péngyou", "hao pengyou", "bạn bè tốt", "HSK 2"],
  ["新电脑", "xīn diànnǎo", "xin diannao", "máy tính mới", "HSK 2"],
  ["晴朗天气", "qínglǎng tiānqì", "qinglang tianqi", "thời tiết nắng đẹp", "HSK 3"],
  ["身体健康", "shēntǐ jiànkāng", "shenti jiankang", "sức khỏe dồi dào", "HSK 2"],
  ["认识朋友", "rènshi péngyou", "renshi pengyou", "làm quen bạn bè", "HSK 2"],
  ["写汉字", "xiě hànzì", "xie hanzi", "viết chữ Hán", "HSK 2"],
  ["看书学习", "kànshū xuéxí", "kanshu xuexi", "đọc sách học tập", "HSK 2"],
  ["坐飞机", "zuò fēijī", "zuo feiji", "đi máy bay", "HSK 2"],
  ["去医院", "qù yīyuàn", "qu yiyuan", "đến bệnh viện", "HSK 2"],
  ["吃早饭", "chī zǎofàn", "chi zaofan", "ăn bữa sáng", "HSK 2"],
  ["喝咖啡", "hē kāfēi", "he kafei", "uống cà phê", "HSK 2"],
  ["骑自行车", "qí zìxíngchē", "qi zixingche", "đi xe đạp", "HSK 2"],
  ["穿新衣服", "chuān xīn yīfu", "chuan xin yifu", "mặc quần áo mới", "HSK 2"],
  ["找工作", "zhǎo gōngzuò", "zhao gongzuo", "tìm việc làm", "HSK 2"],
  ["喝水", "hē shuǐ", "he shui", "uống nước", "HSK 1"],
  ["吃饭", "chī fàn", "chi fan", "ăn cơm, dùng bữa", "HSK 1"],
  ["看书", "kàn shū", "kan shu", "đọc sách", "HSK 1"],
  ["看电视", "kàn diànshì", "kan dianshi", "xem tivi", "HSK 1"],
  ["买水果", "mǎi shuǐguǒ", "mai shuiguo", "mua hoa quả / trái cây", "HSK 1"],
  ["回学校", "huí xuéxiào", "hui xuexiao", "quay lại trường / về trường", "HSK 1"],
  ["回家", "huí jiā", "hui jia", "về nhà", "HSK 1"],
  ["开车", "kāi chē", "kai che", "lái xe ô tô", "HSK 1"],
  ["坐出租车", "zuò chūzūchē", "zuo chuzuche", "đi xe taxi", "HSK 1"],
  ["坐火车", "zuò huǒchē", "zuo huoche", "đi tàu hỏa", "HSK 2"],
  ["做饭", "zuò fàn", "zuo fan", "nấu cơm / nấu ăn", "HSK 1"],
  ["学习汉语", "xuéxí hànyǔ", "xuexi hanyu", "học tiếng Trung", "HSK 1"],
  ["说汉语", "shuō hànyǔ", "shuo hanyu", "nói tiếng Trung", "HSK 1"],
  ["读书", "dú shū", "du shu", "đọc sách / đi học", "HSK 1"],
  ["睡觉", "shuì jiào", "shui jiao", "đi ngủ", "HSK 1"],
  ["休息", "xiū xi", "xiu xi", "nghỉ ngơi", "HSK 1"],
  ["认识你", "rènshi nǐ", "renshi ni", "quen biết bạn / rất vui được gặp bạn", "HSK 1"],
  ["很高兴", "hěn gāoxìng", "hen gaoxing", "rất vui mừng", "HSK 1"],
  ["太好了", "tài hǎo le", "tai hao le", "tuyệt quá, tốt quá", "HSK 1"],
  ["太大了", "tài dà le", "tai da le", "quá lớn / rộng quá", "HSK 1"],
  ["太贵了", "tài guì le", "tai gui le", "đắt quá", "HSK 2"],
  ["太多了", "tài duō le", "tai duo le", "nhiều quá", "HSK 1"],
  ["吃得好", "chī de hǎo", "chi de hao", "ăn ngon, ăn tốt", "HSK 2"],
  ["玩得很高兴", "wán de hěn gāoxìng", "wan de hen gaoxing", "chơi rất vui vẻ", "HSK 2"],
  ["听不懂", "tīng bù dǒng", "ting bu dong", "nghe không hiểu", "HSK 2"],
  ["写得很好", "xiě de hěn hǎo", "xie de hen hao", "viết rất đẹp / rất tốt", "HSK 2"],
  ["一点儿", "yì diǎnr", "yi dianr", "một chút, một ít", "HSK 1"],
  ["一会儿", "yí huìr", "yi huir", "một lát, chốc lát", "HSK 2"],
  ["一个", "yí gè", "yi ge", "một cái / một người", "HSK 1"],
  ["一下儿", "yí xiàr", "yi xiar", "một lát / thử làm trong chốc lát", "HSK 2"],
];

/**
 * CẤP ĐỘ BÌNH THƯỜNG: Fixed Expressions (Quán ngữ thông dụng & Thành ngữ 4 chữ & Cụm khẩu ngữ cố định)
 * Tổng cộng: 44 mục
 */
export const fixedExpressionsVocabulary: VocabularyEntry[] = [
  ["不客气", "bú kèqi", "bu keqi", "không có gì", "HSK 1"],
  ["对不起", "duìbuqǐ", "duibuqi", "xin lỗi", "HSK 1"],
  ["没关系", "méi guānxi", "mei guanxi", "không sao đâu", "HSK 1"],
  ["不好意思", "bù hǎo yìsi", "bu hao yisi", "ngại quá, xin thứ lỗi", "HSK 2"],
  ["没问题", "méi wèntí", "mei wenti", "không thành vấn đề", "HSK 2"],
  ["差不多", "chàbuduō", "chabuduo", "xấp xỉ, gần như nhau", "HSK 3"],
  ["算了吧", "suàn le ba", "suan le ba", "thôi bỏ qua đi", "HSK 3"],
  ["太棒了", "tài bàng le", "tai bang le", "tuyệt vời quá", "HSK 2"],
  ["开玩笑", "kāi wánxiào", "kai wanxiao", "nói đùa, trêu chọc", "HSK 3"],
  ["随随便便", "suísuí biànbiàn", "suisui bianbian", "tùy tiện, qua loa", "HSK 4"],
  ["各种各样", "gè zhǒng gè yàng", "ge zhong ge yang", "đủ mọi chủng loại", "HSK 3"],
  ["一心一意", "yì xīn yí yì", "yi xin yi yi", "một lòng một dạ", "HSK 4"],
  ["自由自在", "zì yóu zì zài", "zi you zi zai", "tự do tự tại", "HSK 4"],
  ["马到成功", "mǎ dào chéng gōng", "ma dao cheng gong", "mã đáo thành công", "HSK 4"],
  ["半途而废", "bàn tú ér fèi", "ban tu er fei", "bỏ cuộc giữa chừng", "HSK 4"],
  ["七上八下", "qī shàng bā xià", "qi shang ba xia", "thấp thỏm lo âu", "HSK 4"],
  ["自相矛盾", "zì xiāng máodùn", "zi xiang maodun", "tự mâu thuẫn", "HSK 4"],
  ["井底之蛙", "jǐng dǐ zhī wā", "jing di zhi wa", "ếch ngồi đáy giếng", "HSK 4"],
  ["不可思议", "bù kě sī yì", "bu ke si yi", "không thể tưởng tượng nổi", "HSK 4"],
  ["津津有味", "jīnjīn yǒu wèi", "jinjin you wei", "thích thú say mê", "HSK 4"],
  ["大吃一惊", "dà chī yì jīng", "da chi yi jing", "vô cùng kinh ngạc", "HSK 4"],
  ["千方百计", "qiān fāng bǎi jì", "qian fang bai ji", "trăm phương ngàn kế", "HSK 4"],
  ["全力以赴", "quán lì yǐ fù", "quan li yi fu", "dốc hết toàn lực", "HSK 4"],
  ["喜出望外", "xǐ chū wàng wài", "xi chu wang wai", "vui mừng khôn xiết", "HSK 4"],
  ["你好", "nǐ hǎo", "ni hao", "xin chào", "HSK 1"],
  ["再见", "zài jiàn", "zai jian", "tạm biệt", "HSK 1"],
  ["谢谢", "xièxie", "xiexie", "cảm ơn", "HSK 1"],
  ["没意见", "méi yìjiàn", "mei yijian", "không có ý kiến gì", "HSK 2"],
  ["怎么样", "zěnmeyàng", "zenmeyang", "thế nào, ra sao", "HSK 1"],
  ["多少钱", "duōshao qián", "duoshao qian", "bao nhiêu tiền", "HSK 1"],
  ["几点钟", "jǐ diǎn zhōng", "ji dian zhong", "mấy giờ", "HSK 1"],
  ["几个人", "jǐ gè rén", "ji ge ren", "mấy người", "HSK 1"],
  ["哪国人", "nǎ guó rén", "na guo ren", "người nước nào", "HSK 1"],
  ["叫什么", "jiào shénme", "jiao shenme", "tên là gì", "HSK 1"],
  ["去哪儿", "qù nǎr", "qu nar", "đi đâu", "HSK 1"],
  ["在哪儿", "zài nǎr", "zai nar", "ở đâu", "HSK 1"],
  ["是什么", "shì shénme", "shi shenme", "là cái gì", "HSK 1"],
  ["是谁", "shì shuí", "shi shui", "là ai", "HSK 1"],
  ["好不好", "hǎo bu hǎo", "hao bu hao", "được không, tốt không", "HSK 1"],
  ["行不行", "xíng bù xíng", "xing bu xing", "được hay không, có được không", "HSK 2"],
  ["是不是", "shì bú shì", "shi bu shi", "phải không, đúng không", "HSK 1"],
  ["能不能", "néng bù néng", "neng bu neng", "có thể... hay không", "HSK 1"],
  ["会不会", "huì bú huì", "hui bu hui", "có biết... hay không", "HSK 1"],
  ["有没有", "yǒu méi yǒu", "you mei you", "có... hay không", "HSK 1"],
];

/**
 * CẤP ĐỘ KHÓ: Sentence Patterns (Mẫu câu liên từ & Cấu trúc ngữ pháp / Chính phản)
 * Tổng cộng: 26 mẫu câu
 */
export const sentencePatternsVocabulary: VocabularyEntry[] = [
  ["虽然很忙，但是他很高兴。", "suīrán hěn máng, dànshì tā hěn gāoxìng.", "suiran hen mang danshi ta hen gaoxing", "Tuy rất bận nhưng anh ấy rất vui.", "HSK 3"],
  ["因为下雨，所以我们没去公园。", "yīnwèi xiàyǔ, suǒyǐ wǒmen méi qù gōngyuán.", "yinwei xiayu suoyi women mei qu gongyuan", "Vì trời mưa nên chúng tôi không đi công viên.", "HSK 2"],
  ["如果明天下雨，我们就不去。", "rúguǒ míngtiān xiàyǔ, wǒmen jiù bú qù.", "ruguo mingtian xiayu women jiu bu qu", "Nếu ngày mai trời mưa thì chúng ta không đi.", "HSK 3"],
  ["除了汉语以外，他还会说英语。", "chúle hànyǔ yǐwài, tā hái huì shuō yīngyǔ.", "chule hanyu yiwai ta hai hui shuo yingyu", "Ngoài tiếng Trung ra, anh ấy còn biết nói tiếng Anh.", "HSK 3"],
  ["他喜欢一边听音乐一边看书。", "tā xǐhuan yìbiān tīng yīnyuè yìbiān kànshū.", "ta xihuan yibian ting yinyue yibian kanshu", "Anh ấy thích vừa nghe nhạc vừa đọc sách.", "HSK 3"],
  ["他的汉语水平越来越高了。", "tā de hànyǔ shuǐpíng yuè lái yuè gāo le.", "ta de hanyu shuiping yue lai yue gao le", "Trình độ tiếng Trung của anh ấy ngày càng cao.", "HSK 3"],
  ["这个苹果又大又甜。", "zhè ge píngguǒ yòu dà yòu tián.", "zhe ge pingguo you da you tian", "Quả táo này vừa to lại vừa ngọt.", "HSK 3"],
  ["她不但漂亮，而且很聪明。", "tā búdàn piàoliang, érqiě hěn cōngming.", "ta budan piaoliang erqie hen congming", "Cô ấy không những xinh đẹp mà còn rất thông minh.", "HSK 3"],
  ["天气越来越热了。", "tiānqì yuè lái yuè rè le.", "tianqi yue lai yue re le", "Thời tiết càng ngày càng nóng rồi.", "HSK 3"],
  ["这里的风景太漂亮了！", "zhèlǐ de fēngjǐng tài piàoliang le!", "zheli de fengjing tai piaoliang le", "Phong cảnh ở đây đẹp quá!", "HSK 2"],
  ["你越努力，就会越幸运。", "nǐ yuè nǔlì, jiù huì yuè xìngyùn.", "ni yue nuli jiu hui yue xingyun", "Bạn càng nỗ lực thì sẽ càng may mắn.", "HSK 4"],
  ["只要坚持，就一定能成功。", "zhǐyào jiānchí, jiù yídìng néng chénggōng.", "zhiyao jianchi jiu yiding neng chenggong", "Chỉ cần kiên trì thì nhất định sẽ thành công.", "HSK 4"],
  ["无论多难，我都要学好中文。", "wúlùn duō nán, wǒ dōu yào xué hǎo zhōngwén.", "wulun duo nan wo dou yao xue hao zhongwen", "Dù khó thế nào tôi cũng phải học tốt tiếng Trung.", "HSK 4"],
  ["既然来了，就多玩几天吧。", "jìrán lái le, jiù duō wán jǐ tiān ba.", "jiran lai le jiu duo wan ji tian ba", "Đã đến rồi thì ở lại chơi thêm mấy ngày nhé.", "HSK 4"],
  ["即使下雨，比赛也照常进行。", "jíshǐ xiàyǔ, bǐsài yě zhàocháng jìnxíng.", "jishi xiayu bisai ye zhaochang jinxing", "Cho dù trời mưa thì cuộc thi vẫn diễn ra như thường.", "HSK 4"],
  ["大家如果没意见，我们就这么决定吧。", "dàjiā rúguǒ méi yìjiàn, wǒmen jiù zhème juéding ba.", "dajia ruguo mei yijian women jiu zheme jueding ba", "Mọi người nếu không có ý kiến gì, chúng ta quyết định vậy nhé.", "HSK 3"],
  ["他是不是你的汉语老师？", "tā shì bú shì nǐ de hànyǔ lǎoshī?", "ta shi bu shi ni de hanyu laoshi", "Anh ấy có phải là giáo viên tiếng Trung của bạn không?", "HSK 2"],
  ["这个字你能不能写？", "zhège zì nǐ néng bù néng xiě?", "zhege zi ni neng bu neng xie", "Chữ này bạn có viết được không?", "HSK 2"],
  ["你会不会做中国菜？", "nǐ huì bú huì zuò zhōngguó cài?", "ni hui bu hui zuo zhongguo cai", "Bạn có biết làm món ăn Trung Quốc không?", "HSK 2"],
  ["你有没有汉语字典？", "nǐ yǒu méi yǒu hànyǔ zìdiǎn?", "ni you mei you hanyu zidian", "Bạn có từ điển tiếng Trung không?", "HSK 2"],
  ["在这里我们住得好，吃得好。", "zài zhèli wǒmen zhù de hǎo, chī de hǎo.", "zai zheli women zhu de hao chi de hao", "Ở đây chúng tôi ở tốt, ăn ngon.", "HSK 2"],
  ["昨天我们去公园，玩得很高兴。", "zuótiān wǒmen qù gōngyuán, wán de hěn gāoxìng.", "zuotian women qu gongyuan wan de hen gaoxing", "Hôm qua chúng tôi đi công viên, chơi rất vui.", "HSK 2"],
  ["他说得太快了，我听不懂。", "tā shuō de tài kuài le, wǒ tīng bù dǒng.", "ta shuo de tai kuai le wo ting bu dong", "Anh ấy nói nhanh quá, tôi nghe không hiểu.", "HSK 2"],
  ["你的汉字写得很好。", "nǐ de hànzì xiě de hěn hǎo.", "ni de hanzi xie de hen hao", "Chữ Hán của bạn viết rất đẹp.", "HSK 2"],
  ["身体不舒服就要去医院。", "shēntǐ bù shūfu jiù yào qù yīyuàn.", "shenti bu shufu jiu yao qu yiyuan", "Cơ thể không khỏe là phải đi bệnh viện.", "HSK 2"],
  ["一天一个苹果，医生远离我。", "yì tiān yí gè píngguǒ, yīshēng yuánlí wǒ.", "yi tian yi ge pingguo yisheng yuanli wo", "Mỗi ngày một quả táo, bác sĩ tránh xa tôi.", "HSK 3"],
];

/**
 * CẤP ĐỘ KHÓ: Context Sentences (Câu ngắn giao tiếp ngữ cảnh thực tế đời sống)
 * Tổng cộng: 95 câu ngữ cảnh
 */
export const contextSentencesVocabulary: VocabularyEntry[] = [
  ["请问去火车站应该怎么走？", "qǐngwèn qù huǒchēzhàn yīnggāi zěnme zǒu?", "qingwen qu huochezhan yinggai zenme zou", "Xin hỏi đi đến ga tàu hỏa đi đường nào?", "HSK 2"],
  ["这件衣服多少钱一件？", "zhè jiàn yīfu duōshao qián yí jiàn?", "zhe jian yifu duoshao qian yi jian", "Bộ quần áo này bao nhiêu tiền một bộ?", "HSK 2"],
  ["服务员，请给我们一份菜单。", "fúwùyuán, qǐng gěi wǒmen yí fèn càidān.", "fuwuyuan qing gei women yi fen caidan", "Phục vụ ơi, vui lòng cho chúng tôi một thực đơn.", "HSK 3"],
  ["我打算明年去北京大学留学。", "wǒ dǎsuàn míngnián qù běijīng dàxué liúxué.", "wo dasuan mingnian qu beijing daxue liuxue", "Tôi dự định năm sau đi du học Đại học Bắc Kinh.", "HSK 3"],
  ["飞机明天早上八点半起飞。", "fēijī míngtiān zǎoshang bā diǎn bàn qǐfēi.", "feiji mingtian zaoshang ba dian ban qifei", "Máy bay sáng mai 8 giờ rưỡi cất cánh.", "HSK 2"],
  ["你今天身体感觉怎么样了？", "nǐ jīntiān shēntǐ gǎnjué zěnmeyàng le?", "ni jintian shenti ganjue zenmeyang le", "Hôm nay trong người bạn cảm thấy thế nào rồi?", "HSK 2"],
  ["我们明天下午两点在图书馆见面。", "wǒmen míngtiān xiàwǔ liǎng diǎn zài túshūguǎn jiànmiàn.", "women mingtian xiawu liang dian zai tushuguan jianmian", "Chiều mai hai giờ chúng ta gặp nhau ở thư viện.", "HSK 3"],
  ["请问附近有中国银行吗？", "qǐngwèn fùjìn yǒu zhōngguó yínháng ma?", "qingwen fujin you zhongguo yinhang ma", "Xin hỏi gần đây có Ngân hàng Trung Quốc không?", "HSK 3"],
  ["这本书非常有意思，推荐你看。", "zhè běn shū fēicháng yǒu yìsi, tuījiàn nǐ kàn.", "zhe ben shu feichang you yisi tuijian ni kan", "Cuốn sách này rất hay, khuyên bạn nên đọc.", "HSK 3"],
  ["祝你生日快乐，学习进步！", "zhù nǐ shēngrì kuàilè, xuéxí jìnbù!", "zhu ni shengri kuaile xuexi jinbu", "Chúc bạn sinh nhật vui vẻ, học tập tiến bộ!", "HSK 2"],
  ["我想买两张去上海的高铁票。", "wǒ xiǎng mǎi liǎng zhāng qù shànghǎi de gāotiě piào.", "wo xiang mai liang zhang qu shanghai de gaotie piao", "Tôi muốn mua hai vé tàu cao tốc đi Thượng Hải.", "HSK 3"],
  ["今天的天气非常舒服，适合散步。", "jīntiān de tiānqì fēicháng shūfu, shìhé sànbù.", "jintian de tianqi feichang shufu shihe sanbu", "Thời tiết hôm nay rất dễ chịu, thích hợp đi dạo.", "HSK 3"],
  ["很高兴认识你，欢迎来到中国。", "hěn gāoxìng rènshi nǐ, huānyíng lái dào zhōngguó.", "hen gaoxing renshi ni huanying lai dao zhongguo", "Rất vui được quen bạn, chào mừng đến Trung Quốc.", "HSK 2"],
  ["医生说你需要多喝水多休息。", "yīshēng shuō nǐ xūyào duō hē shuǐ duō xiūxi.", "yisheng shuo ni xuyao duo he shui duo xiuxi", "Bác sĩ nói bạn cần uống nhiều nước và nghỉ ngơi.", "HSK 2"],
  ["这道中国菜味道非常地道。", "zhè dào zhōngguó cài wèidao fēicháng dìdao.", "zhe dao zhongguo cai weidao feichang didao", "Món ăn Trung Quốc này hương vị rất chuẩn vị.", "HSK 4"],
  ["老师，你好！", "lǎoshī, nǐ hǎo!", "laoshi ni hao", "Thưa thầy/cô, xin chào!", "HSK 1"],
  ["同学们，再见！", "tóngxuémen, zàijiàn!", "tongxuemen zaijian", "Các bạn học sinh, tạm biệt!", "HSK 1"],
  ["谢谢你帮我。", "xièxie nǐ bāng wǒ.", "xiexie ni bang wo", "Cảm ơn bạn đã giúp tôi.", "HSK 1"],
  ["不好意思，让您久等了。", "bù hǎoyìsi, ràng nín jiǔ děng le.", "bu haoyisi rang nin jiu deng le", "Ngại quá, để ngài phải đợi lâu rồi.", "HSK 2"],
  ["今天的天气怎么样？", "jīntiān de tiānqì zěnmeyàng?", "jintian de tianqi zenmeyang", "Thời tiết hôm nay thế nào?", "HSK 1"],
  ["这件衣服多少钱？", "zhè jiàn yīfu duōshao qián?", "zhe jian yifu duoshao qian", "Bộ quần áo này bao nhiêu tiền?", "HSK 1"],
  ["你们家里有几个人？", "nǐmen jiālǐ yǒu jǐ gè rén?", "nimen jiali you ji ge ren", "Nhà các bạn có mấy người?", "HSK 1"],
  ["请问你是哪国人？", "qǐngwèn nǐ shì nǎ guó rén?", "qingwen ni shi na guo ren", "Xin hỏi bạn là người nước nào?", "HSK 1"],
  ["你叫什么名字？", "nǐ jiào shénme míngzi?", "ni jiao shenme mingzi", "Bạn tên là gì?", "HSK 1"],
  ["你下午去哪儿？", "nǐ xiàwǔ qù nǎr?", "ni xiawu qu nar", "Buổi chiều bạn đi đâu?", "HSK 1"],
  ["我的手机在哪儿？", "wǒ de shǒujī zài nǎr?", "wo de shouji zai nar", "Điện thoại của tôi ở đâu?", "HSK 2"],
  ["桌子上的是什么？", "zhuōzi shàng shì shénme?", "zhuozi shang shi shenme", "Trên bàn là cái gì vậy?", "HSK 1"],
  ["门口的那个人是谁？", "ménkǒu de nà gè rén shì shuí?", "menkou de na ge ren shi shui", "Người ở ngoài cửa là ai thế?", "HSK 2"],
  ["我们下午去喝茶，好不好？", "wǒmen xiàwǔ qù hē chá, hǎo bu hǎo?", "women xiawu qu he cha hao bu hao", "Chiều nay chúng ta đi uống trà nhé, được không?", "HSK 1"],
  ["明天借我一本书，行不行？", "míngtiān jiè wǒ yì běn shū, xíng bù xíng?", "mingtian jie wo yi ben shu xing bu xing", "Ngày mai cho tôi mượn một cuốn sách, được chứ?", "HSK 2"],
  ["天黑了，我们回家吧。", "tiān hēi le, wǒmen huí jiā ba.", "tian hei le women hui jia ba", "Trời tối rồi, chúng ta về nhà thôi.", "HSK 2"],
  ["运动后我想喝水。", "yùndòng hòu wǒ xiǎng hē shuǐ.", "yundong hou wo xiang he shui", "Sau khi vận động tôi muốn uống nước.", "HSK 2"],
  ["中国人喜欢喝茶。", "zhōngguó rén xǐhuan hē chá.", "zhongguo ren xihuan he cha", "Người Trung Quốc thích uống trà.", "HSK 1"],
  ["已经是十二点半了，我们去吃饭吧。", "yǐjīng shì shí'èr diǎn bàn le, wǒmen qù chīfàn ba.", "yijing shi shi'er dian ban le women qu chifan ba", "Đã mười hai rưỡi rồi, chúng ta đi ăn cơm thôi.", "HSK 2"],
  ["爸爸正在给朋友打电话。", "bàba zhèngzài gěi péngyou dǎ diànhuà.", "baba zhengzai gei pengyou da dianhua", "Bố đang gọi điện thoại cho bạn.", "HSK 2"],
  ["弟弟在房间里安静地看书。", "dìdi zài fángjiān lǐ ānjìng de kàn shū.", "didi zai fangjian li anjing de kan shu", "Em trai đang đọc sách yên tĩnh trong phòng.", "HSK 2"],
  ["晚上我和家人一起看电视。", "wǎnshang wǒ hé jiārén yìqǐ kàn diànshì.", "wanshang wo he jiaren yiqi kan dianshi", "Buổi tối tôi cùng người thân xem ti vi.", "HSK 1"],
  ["周末我们去电影院看电影。", "zhōumò wǒmen qù diànyǐngyuàn kàn diànyǐng.", "zhoumo women qu dianyingyuan kan dianying", "Cuối tuần chúng ta đến rạp chiếu phim xem phim.", "HSK 2"],
  ["休息的时候，我喜欢听音乐。", "xiūxi de shíhou, wǒ xǐhuan tīng yīnyuè.", "xiuxi de shihou wo xihuan ting yinyue", "Lúc nghỉ ngơi, tôi thích nghe nhạc.", "HSK 2"],
  ["这里的苹果很新鲜，我们买水果吧。", "zhèlǐ de píngguǒ hěn xīnxiān, wǒmen mǎi shuǐguǒ ba.", "zheli de pingguo hen xinxian women mai shuiguo ba", "Táo ở đây rất tươi, chúng ta mua hoa quả nhé.", "HSK 3"],
  ["早上七点半，学生们去学校。", "zǎoshang qī diǎn bàn, xuéshēngmen qù xuéxiào.", "zaoshang qi dian ban xueshengmen qu xuexiao", "Sáng bảy rưỡi, các học sinh đi đến trường.", "HSK 1"],
  ["下午我有课，必须马上回学校。", "xiàwǔ wǒ yǒu kè, bìxū mǎshàng huí xuéxiào.", "xiawu wo you ke bixu mashang hui xuexiao", "Buổi chiều tôi có tiết, phải nhanh chóng về trường.", "HSK 3"],
  ["哥哥刚拿到驾照，会开车了。", "gēge gāng ná dào jiàzhào, huì kāichē le.", "gege gang na dao jiazhao hui kaiche le", "Anh trai vừa lấy bằng lái, biết lái xe rồi.", "HSK 3"],
  ["去北京出差，我们坐飞机去。", "qù běijīng chūchāi, wǒmen zuò fēijī qù.", "qu beijing chuchai women zuo feiji qu", "Đi Bắc Kinh công tác, chúng ta đi bằng máy bay.", "HSK 3"],
  ["下雨了，我们在路边坐出租车。", "xiàyǔ le, wǒmen zài lùbiān zuò chūzūchē.", "xiayu le women zai lubian zuo chuzuche", "Trời mưa rồi, chúng ta bắt taxi ở ven đường.", "HSK 2"],
  ["从这儿到上海，可以坐火车。", "cóng zhè'er dào shànghǎi, kěyǐ zuò huǒchē.", "cong zhe'er dao shanghai keyi zuo huoche", "Từ đây đến Thượng Hải, có thể đi tàu hỏa.", "HSK 2"],
  ["妈妈今天生病了，爸爸来做饭。", "māma jīntiān shēngbìng le, bàba lái zuò fàn.", "mama jintian shengbing le baba lai zuo fan", "Mẹ hôm nay ốm rồi, bố vào bếp nấu ăn.", "HSK 2"],
  ["姐姐在一家大公司工作。", "jiějie zài yì jiā dà gōngsī gōngzuò.", "jiejie zai yi jia da gongsi gongzuo", "Chị gái làm việc ở một công ty lớn.", "HSK 2"],
  ["我每天都花一个小时学习汉语。", "wǒ měitiān dōu huā yí gè xiǎoshí xuéxí hànyǔ.", "wo meitian dou hua yi ge xiaoshi xuexi hanyu", "Mỗi ngày tôi đều dành một tiếng để học tiếng Trung.", "HSK 2"],
  ["他的朋友会说汉语。", "tā de péngyou huì shuō hànyǔ.", "ta de pengyou hui shuo hanyu", "Bạn của anh ấy biết nói tiếng Trung.", "HSK 1"],
  ["练习写汉字需要很多时间。", "liànxí xiě hànzì xūyào hěn duō shíjiān.", "lianxi xie hanzi xuyao hen duo shijian", "Luyện viết chữ Hán cần rất nhiều thời gian.", "HSK 3"],
  ["哥哥现在在北京大学读书。", "gēge xiànzài zài běijīng dàxué dúshū.", "gege xianzai zai beijing daxue dushu", "Anh trai hiện đang học tập tại Đại học Bắc Kinh.", "HSK 2"],
  ["孩子十点钟就上床睡觉了。", "háizi shí diǎn zhōng jiù shàng chuáng shuìjiào le.", "haizi shi dian zhong jiu shang chuang shuijiao le", "Đứa trẻ mười giờ đúng là lên giường đi ngủ rồi.", "HSK 2"],
  ["工作累了，大家休息十分钟吧。", "gōngzuò lèi le, dàjiā xiūxi shí fēnzhōng ba.", "gongzuo lei le dajia xiuxi shi fenzhong ba", "Làm việc mệt rồi, mọi người nghỉ ngơi mười phút nhé.", "HSK 2"],
  ["初次见面，认识你很高兴。", "chūcì jiànmiàn, rènshi nǐ hěn gāoxìng.", "chuci jianmian renshi ni hen gaoxing", "Lần đầu gặp mặt, rất vui được quen biết bạn.", "HSK 2"],
  ["今天能来参加聚会，我很高兴。", "jīntiān néng lái cānjiā jùhuì, wǒ hěn gāoxìng.", "jintian neng lai canjia juhui wo hen gaoxing", "Hôm nay có thể đến tham gia buổi tiệc, tôi rất vui.", "HSK 3"],
  ["明天放假？太好了！", "míngtiān fàngjià? tài hǎo le!", "mingtian fangjia tai hao le", "Ngày mai được nghỉ lễ á? Tuyệt quá!", "HSK 2"],
  ["这双鞋我穿太大了。", "zhè shuāng xié wǒ chuān tài dà le.", "zhe shuang xie wo chuan tai da le", "Đôi giày này tôi đi bị rộng quá.", "HSK 2"],
  ["那个手机太贵了，我买不起。", "nà gè shǒujī tài guì le, wǒ mǎi bù qǐ.", "na ge shouji tai gui le wo mai bu qi", "Chiếc điện thoại kia đắt quá, tôi mua không nổi.", "HSK 3"],
  ["今天的作业太多了。", "jīntiān de zuòyè tài duō le.", "jintian de zuoye tai duo le", "Bài tập về nhà hôm nay nhiều quá.", "HSK 2"],
  ["我会说一点儿汉语。", "wǒ huì shuō yìdiǎnr hànyǔ.", "wo hui shuo yidianr hanyu", "Tôi biết nói một chút tiếng Trung.", "HSK 1"],
  ["请等我一会儿，马上就好。", "qǐng děng wǒ yí huìr, mǎshàng jiù hǎo.", "qing deng wo yi huir mashang jiu hao", "Xin đợi tôi một lát, xong ngay đây.", "HSK 2"],
  ["桌子上有一个苹果。", "zhuōzi shàng yǒu yí gè píngguǒ.", "zhuozi shang you yi ge pingguo", "Trên bàn có một quả táo.", "HSK 1"],
  ["请等我一下儿。", "qǐng děng wǒ yí xiàr.", "qing deng wo yi xiar", "Xin hãy đợi tôi một chút.", "HSK 2"],
  ["他来中国已经三年了。", "tā lái zhōngguó yǐjīng sān nián le.", "ta lai zhongguo yijing san nian le", "Anh ấy đến Trung Quốc đã được ba năm rồi.", "HSK 2"],
  ["我学汉语六个月了。", "wǒ xué hànyǔ liù gè yuè le.", "wo xue hanyu liu ge yue le", "Tôi học tiếng Trung được sáu tháng rồi.", "HSK 1"],
  ["离上课还有五分钟。", "lí shàngkè hái yǒu wǔ fēnzhōng.", "li shangke hai you wu fenzhong", "Cách giờ vào học vẫn còn năm phút.", "HSK 2"],
  ["现在是十点钟整。", "xiànzài shì shí diǎn zhōng zhěng.", "xianzai shi shi dian zhong zheng", "Bây giờ là đúng mười giờ.", "HSK 2"],
  ["今年是2026年。", "jīnnián shì èr líng èr liù nián.", "jinnian shi er ling er liu nian", "Năm nay là năm 2026.", "HSK 1"],
  ["明天天气怎么样？", "míngtiān tiānqì zěnmeyàng?", "mingtian tianqi zenmeyang", "Thời tiết ngày mai thế nào?", "HSK 1"],
  ["昨天我去商店买了很多东西。", "zuótiān wǒ qù shāngdiàn mǎi le hěn duō dōngxi.", "zuotian wo qu shangdian mai le hen duo dongxi", "Hôm qua tôi đi cửa hàng mua rất nhiều đồ.", "HSK 1"],
  ["今天是我的生日。", "jīntiān shì wǒ de shēngrì.", "jintian shi wo de shengri", "Hôm nay là sinh nhật của tôi.", "HSK 1"],
  ["上午我有两节汉语课。", "shàngwǔ wǒ yǒu liǎng jié hànyǔ kè.", "shangwu wo you liang jie hanyu ke", "Buổi sáng tôi có hai tiết tiếng Trung.", "HSK 2"],
  ["中午我在学校食堂吃饭。", "zhōngwǔ wǒ zài xuéxiào shítáng chīfàn.", "zhongwu wo zai xuexiao shitang chifan", "Buổi trưa tôi ăn cơm ở nhà ăn trường.", "HSK 2"],
  ["下午我们去打篮球，好吗？", "xiàwǔ wǒmen qù dǎ lánqiú, hǎo ma?", "xiawu women qu da lanqiu hao ma", "Buổi chiều chúng ta đi chơi bóng rổ nhé, được không?", "HSK 2"],
  ["晚上我七点回家。", "wǎnshang wǒ qī diǎn huí jiā.", "wanshang wo qi dian hui jia", "Buổi tối tôi về nhà lúc 7 giờ.", "HSK 1"],
  ["银行在学校的前面。", "yínháng zài xuéxiào de qiánmiàn.", "yinhang zai xuexiao de qianmian", "Ngân hàng ở phía trước trường học.", "HSK 2"],
  ["那个商店在医院的后面。", "nà gè shāngdiàn zài yīyuàn de hòumian.", "na ge shangdian zai yiyuan de houmian", "Cửa hàng kia ở phía sau bệnh viện.", "HSK 1"],
  ["杯子里面还有水吗？", "bēizi lǐmiàn hái yǒu shuǐ ma?", "beizi limian hai you shui ma", "Bên trong cốc vẫn còn nước không?", "HSK 1"],
  ["书上面有一只猫。", "shū shàngmiàn yǒu yì zhī māo.", "shu shangmian you yi zhi mao", "Bên trên cuốn sách có một con mèo.", "HSK 1"],
  ["椅子下面是什么？", "yǐzi xiàmiàn shì shénme?", "yizi xiamian shi shenme", "Bên dưới chiếc ghế là cái gì?", "HSK 1"],
  ["我很想去中国旅游。", "wǒ hěn xiǎng qù zhōngguó lǚyóu.", "wo hen xiang qu zhongguo luyou", "Tôi rất muốn đi du lịch Trung Quốc.", "HSK 2"],
  ["北京是中国的首都。", "běijīng shì zhōngguó de shǒudū.", "beijing shi zhongguo de shoudu", "Bắc Kinh là thủ đô của Trung Quốc.", "HSK 3"],
  ["离这儿不远有一个小商店。", "lí zhè'er bù yuǎn yǒu yí gè xiǎo shāngdiàn.", "li zhe'er bu yuan you yi ge xiao shangdian", "Cách đây không xa có một cửa hàng nhỏ.", "HSK 2"],
  ["我们的学校非常大。", "wǒmen de xuéxiào fēicháng dà.", "women de xuexiao feichang da", "Trường học của chúng tôi vô cùng lớn.", "HSK 2"],
  ["离春节还有几天，火车站人山人海。", "lí chūnjié hái yǒu jǐ tiān, huǒchēzhàn rénshānrénhǎi.", "li chunjie hai you ji tian huochezhan renshanrenhai", "Còn mấy ngày nữa là đến Tết, ga xe lửa đông nghịt người.", "HSK 4"],
  ["汉语是一门很有意思的语言。", "hànyǔ shì yì mén hěn yǒuyìsi de yǔyán.", "hanyu shi yi men hen youyisi de yuyan", "Tiếng Trung là một ngôn ngữ rất thú vị.", "HSK 3"],
  ["中国南方人主要吃米饭。", "zhōngguó nánfāng rén zhǔyào chī mǐfàn.", "zhongguo nanfang ren zhuyao chi mifan", "Người miền Nam Trung Quốc chủ yếu ăn cơm.", "HSK 3"],
  ["天热了，要多喝水。", "tiān rè le, yào duō hē shuǐ.", "tian re le yao duo he shui", "Trời nóng rồi, phải uống nhiều nước vào.", "HSK 1"],
  ["爸爸每天早晨都要喝一杯茶。", "bàba měitiān zǎochén dōu yào hē yì bēi chá.", "baba meitian zaochen dou yao he yi bei cha", "Bố mỗi ngày sáng sớm đều uống một cốc trà.", "HSK 2"],
  ["我家里养了一只黑色的猫。", "wǒ jiālǐ yǎng le yì zhī hēisè de māo.", "wo jiali yang le yi zhi heise de mao", "Nhà tôi nuôi một con mèo màu đen.", "HSK 2"],
  ["那只狗非常听话。", "nà zhī gǒu fēicháng tīnghuà.", "na zhi gou feichang tinghua", "Con chó kia cực kỳ nghe lời.", "HSK 3"],
  ["换季了，妈妈带我去买新衣服。", "huànjì le, māma dài wǒ qù mǎi xīn yīfu.", "huanji le mama dai wo qu mai xin yifu", "Đổi mùa rồi, mẹ dẫn tôi đi mua quần áo mới.", "HSK 3"],
  ["这个玻璃杯子很漂亮。", "zhè gè bōlí bēizi hěn piàoliang.", "zhe ge boli beizi hen piaoliang", "Cái cốc thủy tinh này rất đẹp.", "HSK 2"],
  ["笔记本电脑放在桌子上。", "bǐjìběn diànnǎo fàng zài zhuōzi shàng.", "bijiben diannao fang zai zhuozi shang", "Máy tính xách tay đặt ở trên bàn.", "HSK 2"],
];

/**
 * Tổng hợp các kho dữ liệu theo Độ Khó
 */
export const normalDifficultyPool: VocabularyEntry[] = [
  ...collocationsVocabulary,
  ...fixedExpressionsVocabulary,
];

export const hardDifficultyPool: VocabularyEntry[] = [
  ...sentencePatternsVocabulary,
  ...contextSentencesVocabulary,
];

export interface DifficultyPack {
  id: string;
  name: string;
  subtitle: string;
  bpm: string;
  tag: string;
  levelBadge: string;
  color: string;
  description: string;
  vocabulary: VocabularyEntry[];
}

export const normalPacks: DifficultyPack[] = [
  {
    id: 'normal-collocations',
    name: '搭配风暴',
    subtitle: 'Collocation Flow',
    bpm: '145',
    tag: 'Collocations',
    levelBadge: 'Bình thường',
    color: '#0ea5e9',
    description: 'Kết hợp từ thường gặp: Động-Tân, Động-Bổ, Định-Trung tự nhiên chuẩn bản xứ (60 mục).',
    vocabulary: collocationsVocabulary,
  },
  {
    id: 'normal-fixed-expressions',
    name: '成语典故',
    subtitle: 'Idioms & Expressions',
    bpm: '160',
    tag: 'Fixed Expressions',
    levelBadge: 'Bình thường',
    color: '#8b5cf6',
    description: 'Thành ngữ 4 chữ & quán ngữ khẩu ngữ giao tiếp thông dụng (44 mục).',
    vocabulary: fixedExpressionsVocabulary,
  },
  {
    id: 'normal-all',
    name: '中级精选',
    subtitle: 'Master Collocations',
    bpm: '165',
    tag: 'Tổng hợp Bậc Trung',
    levelBadge: 'Bình thường',
    color: '#f59e0b',
    description: 'Trộn ngẫu nhiên toàn bộ 104 mục Collocations và Thành ngữ / Quán ngữ.',
    vocabulary: normalDifficultyPool,
  },
];

export const hardPacks: DifficultyPack[] = [
  {
    id: 'hard-patterns',
    name: '句式天梯',
    subtitle: 'Grammar Patterns',
    bpm: '175',
    tag: 'Sentence Patterns',
    levelBadge: 'Khó',
    color: '#ec4899',
    description: 'Mẫu câu liên từ & cấu trúc ngữ pháp phức (虽然...但是, 因为...所以, 越来越..., chính phản) (26 mẫu).',
    vocabulary: sentencePatternsVocabulary,
  },
  {
    id: 'hard-context',
    name: '情境对话',
    subtitle: 'Context Sentences',
    bpm: '180',
    tag: 'Context Sentences',
    levelBadge: 'Khó',
    color: '#ef4444',
    description: 'Câu ngắn ngữ cảnh thực tế: mua sắm, hỏi đường, đặt vé, đàm thoại hằng ngày (95 câu).',
    vocabulary: contextSentencesVocabulary,
  },
  {
    id: 'hard-all',
    name: '高级风暴',
    subtitle: 'Ultimate Sentences',
    bpm: '188',
    tag: 'Tổng hợp Bậc Khó',
    levelBadge: 'Thử thách',
    color: '#dc2626',
    description: 'Đại chiến câu nâng cao: thử thách tốc độ phản xạ với toàn bộ 121 mẫu câu & ngữ cảnh.',
    vocabulary: hardDifficultyPool,
  },
];
