import type { VocabularyEntry } from './hsk2-vocabulary';

/**
 * CẤP ĐỘ BÌNH THƯỜNG: Collocations (Kết hợp từ thường gặp: Động-Tân, Động-Bổ, Định-Trung)
 * Tổng cộng: 288 mục
 */
export const collocationsVocabulary: VocabularyEntry[] = [
  ["喝茶", "hē chá", "he cha", "uống trà", "HSK 2"],
  ["看电影", "kàn diànyǐng", "kan dianying", "xem phim", "HSK 2"],
  ["打电话", "dǎ diànhuà", "da dianhua", "gọi điện thoại", "HSK 2"],
  ["吃米饭", "chī mǐfàn", "chi mifan", "ăn cơm trắng", "HSK 2"],
  ["听音乐", "tīng yīnyuè", "ting yinyue", "nghe nhạc", "HSK 2"],
  ["做作业", "zuò zuòyè", "zuo zuoye", "làm bài tập", "HSK 2"],
  ["去学校", "qù xuéxiào", "qu xuexiao", "đến trường học", "HSK 2"],
  ["买东西", "mǎi dōngxi", "mai dongxi", "mua sắm đồ đạc", "HSK 2"],
  ["学汉语", "xué hànyǔ", "xue hanyu", "học tiếng Trung", "HSK 2"],
  ["开汽车", "kāi qìchē", "kai qiche", "lái xe ô tô", "HSK 2"],
  ["洗衣服", "xǐ yīfu", "xi yifu", "giặt quần áo", "HSK 2"],
  ["跑步锻炼", "pǎobù duànliàn", "paobu duanlian", "chạy bộ tập thể dục", "HSK 3"],
  ["工作忙碌", "gōngzuò mánglù", "gongzuo manglu", "công việc bận rộn", "HSK 3"],
  ["打篮球", "dǎ lánqiú", "da lanqiu", "chơi bóng rổ", "HSK 2"],
  ["唱歌跳舞", "chànggē tiàowǔ", "changge tiaowu", "ca hát nhảy múa", "HSK 2"],
  ["漂亮衣服", "piàoliang yīfu", "piaoliang yifu", "quần áo đẹp", "HSK 2"],
  ["好朋友", "hǎo péngyou", "hao pengyou", "bạn bè tốt", "HSK 2"],
  ["新电脑", "xīn diànnǎo", "xin diannao", "máy tính mới", "HSK 2"],
  ["晴朗天气", "qínglǎng tiānqì", "qinglang tianqi", "thời tiết nắng đẹp", "HSK 3"],
  ["身体健康", "shēntǐ jiànkāng", "shenti jiankang", "sức khỏe dồi dào", "HSK 2"],
  ["认识朋友", "rènshi péngyou", "renshi pengyou", "làm quen bạn bè", "HSK 2"],
  ["写汉字", "xiě hànzì", "xie hanzi", "viết chữ Hán", "HSK 2"],
  ["看书学习", "kànshū xuéxí", "kanshu xuexi", "đọc sách học tập", "HSK 2"],
  ["坐飞机", "zuò fēijī", "zuo feiji", "đi máy bay", "HSK 2"],
  ["去医院", "qù yīyuàn", "qu yiyuan", "đến bệnh viện", "HSK 2"],
  ["吃早饭", "chī zǎofàn", "chi zaofan", "ăn bữa sáng", "HSK 2"],
  ["喝咖啡", "hē kāfēi", "he kafei", "uống cà phê", "HSK 2"],
  ["骑自行车", "qí zìxíngchē", "qi zixingche", "đi xe đạp", "HSK 2"],
  ["穿新衣服", "chuān xīn yīfu", "chuan xin yifu", "mặc quần áo mới", "HSK 2"],
  ["找工作", "zhǎo gōngzuò", "zhao gongzuo", "tìm việc làm", "HSK 2"],
  ["喝水", "hē shuǐ", "he shui", "uống nước", "HSK 1"],
  ["吃饭", "chī fàn", "chi fan", "ăn cơm, dùng bữa", "HSK 1"],
  ["看书", "kàn shū", "kan shu", "đọc sách", "HSK 1"],
  ["看电视", "kàn diànshì", "kan dianshi", "xem tivi", "HSK 1"],
  ["买水果", "mǎi shuǐguǒ", "mai shuiguo", "mua hoa quả / trái cây", "HSK 1"],
  ["回学校", "huí xuéxiào", "hui xuexiao", "quay lại trường / về trường", "HSK 1"],
  ["回家", "huí jiā", "hui jia", "về nhà", "HSK 1"],
  ["开车", "kāi chē", "kai che", "lái xe ô tô", "HSK 1"],
  ["坐出租车", "zuò chūzūchē", "zuo chuzuche", "đi xe taxi", "HSK 1"],
  ["坐火车", "zuò huǒchē", "zuo huoche", "đi tàu hỏa", "HSK 2"],
  ["做饭", "zuò fàn", "zuo fan", "nấu cơm / nấu ăn", "HSK 1"],
  ["学习汉语", "xuéxí hànyǔ", "xuexi hanyu", "học tiếng Trung", "HSK 1"],
  ["说汉语", "shuō hànyǔ", "shuo hanyu", "nói tiếng Trung", "HSK 1"],
  ["读书", "dú shū", "du shu", "đọc sách / đi học", "HSK 1"],
  ["睡觉", "shuì jiào", "shui jiao", "đi ngủ", "HSK 1"],
  ["休息", "xiū xi", "xiu xi", "nghỉ ngơi", "HSK 1"],
  ["认识你", "rènshi nǐ", "renshi ni", "quen biết bạn / rất vui được gặp bạn", "HSK 1"],
  ["很高兴", "hěn gāoxìng", "hen gaoxing", "rất vui mừng", "HSK 1"],
  ["太好了", "tài hǎo le", "tai hao le", "tuyệt quá, tốt quá", "HSK 1"],
  ["太大了", "tài dà le", "tai da le", "quá lớn / rộng quá", "HSK 1"],
  ["太贵了", "tài guì le", "tai gui le", "đắt quá", "HSK 2"],
  ["太多了", "tài duō le", "tai duo le", "nhiều quá", "HSK 1"],
  ["吃得好", "chī de hǎo", "chi de hao", "ăn ngon, ăn tốt", "HSK 2"],
  ["玩得很高兴", "wán de hěn gāoxìng", "wan de hen gaoxing", "chơi rất vui vẻ", "HSK 2"],
  ["听不懂", "tīng bù dǒng", "ting bu dong", "nghe không hiểu", "HSK 2"],
  ["写得很好", "xiě de hěn hǎo", "xie de hen hao", "viết rất đẹp / rất tốt", "HSK 2"],
  ["一点儿", "yì diǎnr", "yi dianr", "một chút, một ít", "HSK 1"],
  ["一会儿", "yí huìr", "yi huir", "một lát, chốc lát", "HSK 2"],
  ["一个", "yí gè", "yi ge", "một cái / một người", "HSK 1"],
  ["一下儿", "yí xiàr", "yi xiar", "một lát / thử làm trong chốc lát", "HSK 2"],
  ["生病", "shēng bìng", "sheng bing", "Bị bệnh, ốm", "HSK 3"],
  ["吃药", "chī yào", "chi yao", "Uống thuốc", "HSK 3"],
  ["跑步", "pǎo bù", "pao bu", "Chạy bộ", "HSK 3"],
  ["踢足球", "tī zú qiú", "ti zu qiu", "Đá bóng", "HSK 3"],
  ["游泳", "yóu yǒng", "you yong", "Bơi lội", "HSK 3"],
  ["旅游", "lǚ yóu", "lu you", "Du lịch", "HSK 3"],
  ["逛街", "guàng jiē", "guang jie", "Đi dạo phố, mua sắm", "HSK 3"],
  ["打扫房间", "dǎ sǎo fáng jiān", "da sao fang jian", "Dọn dẹp phòng", "HSK 3"],
  ["看病", "kàn bìng", "kan bing", "Khám bệnh", "HSK 3"],
  ["问路", "wèn lù", "wen lu", "Hỏi đường", "HSK 3"],
  ["迷路", "mí lù", "mi lu", "Lạc đường", "HSK 3"],
  ["迟到", "chí dào", "chi dao", "Đến muộn, trễ giờ", "HSK 3"],
  ["请假", "qǐng jià", "qing jia", "Xin nghỉ phép", "HSK 3"],
  ["开会", "kāi huì", "kai hui", "Họp", "HSK 3"],
  ["上班", "shàng bān", "shang ban", "Đi làm", "HSK 3"],
  ["下班", "xià bān", "xia ban", "Tan làm", "HSK 3"],
  ["放学", "fàng xué", "fang xue", "Tan trường", "HSK 3"],
  ["上课", "shàng kè", "shang ke", "Lên lớp, đi học", "HSK 3"],
  ["下课", "xià kè", "xia ke", "Tan học", "HSK 3"],
  ["考试", "kǎo shì", "kao shi", "Thi cử", "HSK 3"],
  ["及格", "jí gé", "ji ge", "Đạt điểm chuẩn, qua môn", "HSK 3"],
  ["毕业", "bì yè", "bi ye", "Tốt nghiệp", "HSK 3"],
  ["面试", "miàn shì", "mian shi", "Phỏng vấn", "HSK 3"],
  ["赚钱", "zhuàn qián", "zhuan qian", "Kiếm tiền", "HSK 3"],
  ["花钱", "huā qián", "hua qian", "Tiêu tiền", "HSK 3"],
  ["存钱", "cún qián", "cun qian", "Tiết kiệm tiền, gửi tiền", "HSK 3"],
  ["借钱", "jiè qián", "jie qian", "Mượn tiền / Cho mượn tiền", "HSK 3"],
  ["还钱", "huán qián", "huan qian", "Trả tiền", "HSK 3"],
  ["满意", "mǎn yì", "man yi", "Hài lòng", "HSK 3"],
  ["高兴", "gāo xìng", "gao xing", "Vui vẻ, vui mừng", "HSK 3"],
  ["生气", "shēng qì", "sheng qi", "Tức giận", "HSK 3"],
  ["担心", "dān xīn", "dan xin", "Lo lắng", "HSK 3"],
  ["着急", "zháo jí", "zhao ji", "Sốt ruột, lo lắng", "HSK 3"],
  ["难过", "nán guò", "nan guo", "Buồn bã, đau khổ", "HSK 3"],
  ["放心", "fàng xīn", "fang xin", "Yên tâm", "HSK 3"],
  ["感动", "gǎn dòng", "gan dong", "Cảm động", "HSK 3"],
  ["害怕", "hài pà", "hai pa", "Sợ hãi", "HSK 3"],
  ["觉得", "jué de", "jue de", "Cảm thấy", "HSK 3"],
  ["以为", "yǐ wéi", "yi wei", "Cứ tưởng rằng", "HSK 3"],
  ["希望", "xī wàng", "xi wang", "Hy vọng", "HSK 3"],
  ["打算", "dǎ suàn", "da suan", "Dự định", "HSK 3"],
  ["准备", "zhǔn bèi", "zhun bei", "Chuẩn bị", "HSK 3"],
  ["决定", "jué dìng", "jue ding", "Quyết định", "HSK 3"],
  ["同意", "tóng yì", "tong yi", "Đồng ý", "HSK 3"],
  ["反对", "fǎn duì", "fan dui", "Phản đối", "HSK 3"],
  ["帮忙", "bāng máng", "bang mang", "Giúp đỡ", "HSK 3"],
  ["照顾", "zhào gù", "zhao gu", "Chăm sóc", "HSK 3"],
  ["欢迎", "huān yíng", "huan ying", "Hoan nghênh, chào đón", "HSK 3"],
  ["谢谢", "xiè xie", "xie xie", "Cảm ơn", "HSK 3"],
  ["客气", "kè qi", "ke qi", "Khách sáo", "HSK 3"],
  ["对不起", "duì bu qǐ", "dui bu qi", "Xin lỗi", "HSK 3"],
  ["没关系", "méi guān xi", "mei guan xi", "Không sao cả", "HSK 3"],
  ["再见", "zài jiàn", "zai jian", "Tạm biệt", "HSK 3"],
  ["没问题", "méi wèn tí", "mei wen ti", "Không thành vấn đề, được chứ", "HSK 3"],
  ["不客气", "bù kè qi", "bu ke qi", "Không có gì (đáp lại lời cảm ơn)", "HSK 3"],
  ["差不多", "chà bu duō", "cha bu duo", "Gần như, xấp xỉ", "HSK 3"],
  ["多少钱", "duō shǎo qián", "duo shao qian", "Bao nhiêu tiền", "HSK 3"],
  ["几点钟", "jǐ diǎn zhōng", "ji dian zhong", "Mấy giờ", "HSK 3"],
  ["怎么样", "zěn me yàng", "zen me yang", "Thế nào", "HSK 3"],
  ["见面", "jiàn miàn", "jian mian", "Gặp mặt", "HSK 3"],
  ["聊天", "liáo tiān", "liao tian", "Trò chuyện, tán gẫu", "HSK 3"],
  ["散步", "sàn bù", "san bu", "Đi dạo", "HSK 3"],
  ["搬家", "bān jiā", "ban jia", "Chuyển nhà", "HSK 3"],
  ["租房", "zū fáng", "zu fang", "Thuê nhà", "HSK 3"],
  ["打扫卫生", "dǎ sǎo wèi shēng", "da sao wei sheng", "Dọn vệ sinh", "HSK 3"],
  ["洗脸", "xǐ liǎn", "xi lian", "Rửa mặt", "HSK 3"],
  ["刷牙", "shuā yá", "shua ya", "Đánh răng", "HSK 3"],
  ["理发", "lǐ fà", "li fa", "Cắt tóc", "HSK 3"],
  ["照相", "zhào xiàng", "zhao xiang", "Chụp ảnh", "HSK 3"],
  ["拍照", "pāi zhào", "pai zhao", "Chụp hình", "HSK 3"],
  ["上网", "shàng wǎng", "shang wang", "Lên mạng, lướt web", "HSK 3"],
  ["发邮件", "fā yóu jiàn", "fa you jian", "Gửi email", "HSK 3"],
  ["接电话", "jiē diàn huà", "jie dian hua", "Nghe điện thoại", "HSK 3"],
  ["回电话", "huí diàn huà", "hui dian hua", "Gọi điện thoại lại", "HSK 3"],
  ["发短信", "fā duǎn xìn", "fa duan xin", "Nhắn tin", "HSK 3"],
  ["看小说", "kàn xiǎo shuō", "kan xiao shuo", "Đọc tiểu thuyết", "HSK 3"],
  ["玩游戏", "wán yóu xì", "wan you xi", "Chơi trò chơi, chơi game", "HSK 3"],
  ["画画", "huà huà", "hua hua", "Vẽ tranh", "HSK 3"],
  ["写字", "xiě zì", "xie zi", "Viết chữ", "HSK 3"],
  ["复习功课", "fù xí gōng kè", "fu xi gong ke", "Ôn tập bài vở", "HSK 3"],
  ["查资料", "chá zī liào", "cha zi liao", "Tra cứu tài liệu", "HSK 3"],
  ["查字典", "chá zì diǎn", "cha zi dian", "Tra từ điển", "HSK 3"],
  ["问问题", "wèn wèn tí", "wen wen ti", "Đặt câu hỏi, hỏi bài", "HSK 3"],
  ["回答问题", "huí dá wèn tí", "hui da wen ti", "Trả lời câu hỏi", "HSK 3"],
  ["懂意思", "dǒng yì si", "dong yi si", "Hiểu ý nghĩa", "HSK 3"],
  ["发脾气", "fā pí qi", "fa pi qi", "Nổi giận, cáu kỉnh", "HSK 3"],
  ["开玩笑", "kāi wán xiào", "kai wan xiao", "Nói đùa, đùa cợt", "HSK 3"],
  ["讲笑话", "jiǎng xiào huà", "jiang xiao hua", "Kể chuyện cười", "HSK 3"],
  ["出主意", "chū zhǔ yi", "chu zhu yi", "Hiến kế, ra chủ ý", "HSK 3"],
  ["想办法", "xiǎng bàn fǎ", "xiang ban fa", "Nghĩ cách, tìm cách", "HSK 3"],
  ["下决定", "xià jué dìng", "xia jue ding", "Đưa ra quyết định", "HSK 3"],
  ["做准备", "zuò zhǔn bèi", "zuo zhun bei", "Làm công tác chuẩn bị", "HSK 3"],
  ["有经验", "yǒu jīng yàn", "you jing yan", "Có kinh nghiệm", "HSK 3"],
  ["有信心", "yǒu xìn xīn", "you xin xin", "Có lòng tin, tự tin", "HSK 3"],
  ["有兴趣", "yǒu xìng qù", "you xing qu", "Có hứng thú", "HSK 3"],
  ["感兴趣", "gǎn xìng qù", "gan xing qu", "Cảm thấy hứng thú", "HSK 3"],
  ["有道理", "yǒu dào li", "you dao li", "Có lý, hợp lý", "HSK 3"],
  ["起作用", "qǐ zuò yòng", "qi zuo yong", "Phát huy tác dụng", "HSK 3"],
  ["出问题", "chū wèn tí", "chu wen ti", "Xảy ra vấn đề, trục trặc", "HSK 3"],
  ["想念", "xiǎng niàn", "xiang nian", "Nhớ nhung", "HSK 3"],
  ["丢面子", "diū miàn zi", "diu mian zi", "Mất mặt", "HSK 3"],
  ["占便宜", "zhàn pián yí", "zhan pian yi", "Chiếm lợi, hời", "HSK 3"],
  ["受欢迎", "shòu huān yíng", "shou huan ying", "Được hoan nghênh, được yêu thích", "HSK 3"],
  ["受 影响", "shòu yǐng xiǎng", "shou ying xiang", "Bị ảnh hưởng", "HSK 3"],
  ["发烧", "fā shāo", "fa shao", "Bị sốt", "HSK 3"],
  ["感冒", "gǎn mào", "gan mao", "Bị cảm lạnh", "HSK 3"],
  ["咳嗽", "ké sou", "ke sou", "Ho", "HSK 3"],
  ["流鼻涕", "liú bí tì", "liu bi ti", "Sổ mũi", "HSK 3"],
  ["肚子疼", "dù zi téng", "du zi teng", "Đau bụng", "HSK 3"],
  ["头疼", "tóu téng", "tou teng", "Đau đầu", "HSK 3"],
  ["量体温", "liàng tǐ wēn", "liang ti wen", "Đo thân nhiệt", "HSK 3"],
  ["挂号", "guà hào", "gua hao", "Đăng ký khám bệnh (lấy số)", "HSK 3"],
  ["吃饱", "chī bǎo", "chi bao", "Ăn no", "HSK 3"],
  ["喝醉", "hē zuì", "he zui", "Say rượu", "HSK 3"],
  ["口渴", "kǒu kě", "kou ke", "Khát nước", "HSK 3"],
  ["饿肚子", "è dù zi", "e du zi", "Để bụng đói", "HSK 3"],
  ["点菜", "diǎn cài", "dian cai", "Gọi món", "HSK 3"],
  ["买单", "mǎi dān", "mai dan", "Thanh toán hóa đơn, trả tiền", "HSK 3"],
  ["结账", "jié zhàng", "jie zhang", "Kết toán, thanh toán", "HSK 3"],
  ["打包", "dǎ bāo", "da bao", "Gói mang về (thức ăn thừa)", "HSK 3"],
  ["排队", "pái duì", "pai dui", "Xếp hàng", "HSK 3"],
  ["买票", "mǎi piào", "mai piao", "Mua vé", "HSK 3"],
  ["检票", "jiǎn piào", "jian piao", "Soát vé", "HSK 3"],
  ["上车", "shàng chē", "shang che", "Lên xe", "HSK 3"],
  ["下车", "xià chē", "xia che", "Xuống xe", "HSK 3"],
  ["转车", "zhuǎn chē", "zhuan che", "Đổi xe, trung chuyển xe", "HSK 3"],
  ["换乘", "huàn chéng", "huan cheng", "Chuyển tuyến (tàu điện, xe buýt)", "HSK 3"],
  ["超重", "chāo zhòng", "chao zhong", "Quá cước, quá trọng lượng", "HSK 3"],
  ["登机", "dēng jī", "deng ji", "Lên máy bay", "HSK 3"],
  ["起飞", "qǐ fēi", "qi fei", "Cất cánh (máy bay)", "HSK 3"],
  ["降落", "jiàng luò", "jiang luo", "Hạ cánh", "HSK 3"],
  ["出差", "chū chāi", "chu chai", "Đi công tác", "HSK 3"],
  ["度假", "dù jià", "du jia", "Đi nghỉ mát, nghỉ dưỡng", "HSK 3"],
  ["照看", "zhào kàn", "zhao kan", "Trông nom, chăm sóc", "HSK 3"],
  ["打交道", "dǎ jiāo dào", "da jiao dao", "Giao thiệp, tiếp xúc", "HSK 3"],
  ["做生意", "zuò shēng yì", "zuo sheng yi", "Buôn bán, kinh doanh", "HSK 3"],
  ["开店", "kāi diàn", "kai dian", "Mở cửa hàng", "HSK 3"],
  ["营业", "yíng yè", "ying ye", "Kinh doanh, mở cửa phục vụ", "HSK 3"],
  ["打折", "dǎ zhé", "da zhe", "Giảm giá, chiết khấu", "HSK 3"],
  ["促销", "cù xiāo", "cu xiao", "Khuyến mãi, xúc tiến thương mại", "HSK 3"],
  ["免费", "miǎn fèi", "mian fei", "Miễn phí", "HSK 3"],
  ["收费", "shōu fèi", "shou fei", "Thu phí", "HSK 3"],
  ["刷卡", "shuā kǎ", "shua ka", "Quẹt thẻ", "HSK 3"],
  ["付现金", "fù xiàn jīn", "fu xian jin", "Trả tiền mặt", "HSK 3"],
  ["办卡", "bàn kǎ", "ban ka", "Làm thẻ thành viên, mở thẻ", "HSK 3"],
  ["充值", "chōng zhí", "chong zhi", "Nạp tiền (vào thẻ/tài khoản)", "HSK 3"],
  ["密码", "mì mǎ", "mi ma", "Mật mã, mật khẩu", "HSK 3"],
  ["取钱", "qǔ qián", "qu qian", "Rút tiền", "HSK 3"],
  ["签字", "qiān zì", "qian zi", "Ký tên", "HSK 3"],
  ["盖章", "gài zhāng", "gai zhang", "Đóng dấu", "HSK 3"],
  ["复印", "fù yìn", "fu yin", "Photo (tài liệu)", "HSK 3"],
  ["打印", "dǎ yìn", "da yin", "In ấn", "HSK 3"],
  ["发传真", "fā chuán zhēn", "fa chuan zhen", "Gửi fax", "HSK 3"],
  ["寄信", "jì xìn", "ji xin", "Gửi thư", "HSK 3"],
  ["收信", "shōu xìn", "shou xin", "Nhận thư", "HSK 3"],
  ["寄包裹", "jì bāo guǒ", "ji bao guo", "Gửi bưu phẩm, gửi kiện hàng", "HSK 3"],
  ["收快递", "shōu kuài dì", "shou kuai di", "Nhận hàng chuyển phát nhanh", "HSK 3"],
  ["留言", "liú yán", "liu yan", "Để lại lời nhắn", "HSK 3"],
  ["转告", "zhuǎn gào", "zhuan gao", "Nhắn lại, chuyển lời", "HSK 3"],
  ["联系", "lián xì", "lian xi", "Liên lạc", "HSK 3"],
  ["保持", "bǎo chí", "bao chi", "Duy trì, giữ gìn", "HSK 3"],
  ["习惯", "xí guàn", "xi guan", "Thói quen / Quen với", "HSK 3"],
  ["适应", "shì yìng", "shi ying", "Thích nghi", "HSK 3"],
  ["坚持", "jiān chí", "jian chi", "Kiên trì, kiên định", "HSK 3"],
  ["放弃", "fàng qì", "fang qi", "Từ bỏ", "HSK 3"],
  ["努力", "nǔ lì", "nu li", "Nỗ lực, cố gắng", "HSK 3"],
  ["小心", "xiǎo xīn", "xiao xin", "Cẩn thận", "HSK 3"],
  ["注意", "zhù yì", "zhu yi", "Chú ý, lưu ý", "HSK 3"],
  ["粗心", "cū xīn", "cu xin", "Sơ suất, bất cẩn, cẩu thả", "HSK 3"],
  ["认真", "rèn zhēn", "ren zhen", "Nghiêm túc, cẩn thận", "HSK 3"],
  ["负责", "fù zé", "fu ze", "Chịu trách nhiệm", "HSK 3"],
  ["靠谱", "kào pǔ", "kao pu", "Đáng tin cậy", "HSK 3"],
  ["省钱", "shěng qián", "sheng qian", "Tiết kiệm tiền", "HSK 3"],
  ["浪费", "làng fèi", "lang fei", "Lãng phí", "HSK 3"],
  ["吃苦", "chī kǔ", "chi ku", "Chịu khổ, nếm trải gian khổ", "HSK 3"],
  ["享福", "xiǎng fú", "xiang fu", "Hưởng phúc, hưởng thụ an nhàn", "HSK 3"],
  ["参观", "cān guān", "can guan", "Tham quan", "HSK 3"],
  ["游览", "yóu lǎn", "you lan", "Vãn cảnh, tham quan thắng cảnh", "HSK 3"],
  ["欣赏", "xīn shǎng", "xin shang", "Thưởng thức, ngắm nhìn", "HSK 3"],
  ["拍照留念", "pāi zhào liú niàn", "pai zhao liu nian", "Chụp ảnh lưu niệm", "HSK 3"],
  ["购买", "gòu mǎi", "gou mai", "Mua sắm (từ trang trọng)", "HSK 3"],
  ["挑选", "tiāo xuǎn", "tiao xuan", "Lựa chọn, chọn lựa", "HSK 3"],
  ["试穿", "shì chuān", "shi chuan", "Mặc thử (quần áo)", "HSK 3"],
  ["合身", "hé shēn", "he shen", "Vừa vặn người", "HSK 3"],
  ["付账", "fù zhàng", "fu zhang", "Trả tiền, thanh toán", "HSK 3"],
  ["找零", "zhǎo líng", "zhao ling", "Thối tiền thừa", "HSK 3"],
  ["发票", "fā piào", "fa piao", "Hóa đơn (đỏ/VAT)", "HSK 3"],
  ["特价", "tè jià", "te jia", "Giá đặc biệt, giá ưu đãi", "HSK 3"],
  ["质量", "zhì liàng", "zhi liang", "Chất lượng", "HSK 3"],
  ["品牌", "pǐn pái", "pin pai", "Thương hiệu", "HSK 3"],
  ["款式", "kuǎn shì", "kuan shi", "Kiểu dáng", "HSK 3"],
  ["尺码", "chǐ mǎ", "chi ma", "Kích cỡ, size", "HSK 3"],
  ["颜色", "yán sè", "yan se", "Màu sắc", "HSK 3"],
  ["退货", "tuì huò", "tui huo", "Trả lại hàng", "HSK 3"],
  ["换货", "huàn huò", "huan huo", "Đổi hàng", "HSK 3"],
  ["服务态度", "fú wù tài dù", "fu wu tai du", "Thái độ phục vụ", "HSK 3"],
  ["环境", "huán jìng", "huan jing", "Môi trường, không gian", "HSK 3"],
  ["干净", "gān jìng", "gan jing", "Sạch sẽ", "HSK 3"],
  ["热闹", "rè nao", "re nao", "Náo nhiệt, đông vui", "HSK 3"],
  ["安静", "ān jìng", "an jing", "Yên tĩnh", "HSK 3"],
  ["安全", "ān quán", "an quan", "An toàn", "HSK 3"],
  ["危险", "wēi xiǎn", "wei xian", "Nguy hiểm", "HSK 3"],
  ["方便", "fāng biàn", "fang bian", "Tiện lợi, thuận tiện", "HSK 3"],
  ["麻烦", "má fan", "ma fan", "Phiền phức / Làm phiền", "HSK 3"],
  ["顺利", "shùn lì", "shun li", "Thuận lợi", "HSK 3"],
  ["困难", "kùn nan", "kun nan", "Khó khăn", "HSK 3"],
  ["解决", "jiě jué", "jie jue", "Giải quyết", "HSK 3"],
  ["成功", "chéng gōng", "cheng gong", "Thành công", "HSK 3"],
  ["失败", "shī bài", "shi bai", "Thất bại", "HSK 3"],
  ["经验", "jīng yàn", "jing yan", "Kinh nghiệm", "HSK 3"],
  ["教训", "jiào xùn", "jiao xun", "Bài học kinh nghiệm (thường do sai lầm)", "HSK 3"],
  ["机会", "jī huì", "ji hui", "Cơ hội", "HSK 3"],
  ["选择", "xuǎn zé", "xuan ze", "Lựa chọn", "HSK 3"],
  ["意见", "yì jiàn", "yi jian", "Ý kiến", "HSK 3"],
  ["建议", "jiàn yì", "jian yi", "Đề nghị, lời khuyên", "HSK 3"],
  ["看法", "kàn fǎ", "kan fa", "Quan điểm, cách nhìn", "HSK 3"],
  ["态度", "tài dù", "tai du", "Thái độ", "HSK 3"],
  ["兴趣", "xìng qù", "xing qu", "Sở thích, hứng thú", "HSK 3"],
  ["爱好", "ài hào", "ai hao", "Sở thích", "HSK 3"],
  ["特点", "tè diǎn", "te dian", "Đặc điểm, điểm nổi bật", "HSK 3"],
  ["区别", "qū bié", "qu bie", "Sự khác biệt", "HSK 3"],
  ["相同", "xiāng tóng", "xiang tong", "Giống nhau", "HSK 3"],
  ["不同", "bù tóng", "bu tong", "Khác nhau", "HSK 3"],
  ["重要", "zhòng yào", "zhong yao", "Quan trọng", "HSK 3"],
  ["主要", "zhǔ yào", "zhu yao", "Chủ yếu, chính", "HSK 3"],
  ["一般", "yì bān", "yi ban", "Thông thường / Bình thường", "HSK 3"],
  ["特别", "tè bié", "te bie", "Đặc biệt", "HSK 3"],
  ["尤其", "yóu qí", "you qi", "Nhất là, đặc biệt là", "HSK 3"],
];

/**
 * CẤP ĐỘ BÌNH THƯỜNG: Fixed Expressions (Quán ngữ thông dụng & Thành ngữ 4 chữ & Cụm khẩu ngữ cố định)
 * Tổng cộng: 82 mục
 */
export const fixedExpressionsVocabulary: VocabularyEntry[] = [
  ["不客气", "bú kèqi", "bu keqi", "không có gì", "HSK 1"],
  ["对不起", "duìbuqǐ", "duibuqi", "xin lỗi", "HSK 1"],
  ["没关系", "méi guānxi", "mei guanxi", "không sao đâu", "HSK 1"],
  ["不好意思", "bù hǎo yìsi", "bu hao yisi", "ngại quá, xin thứ lỗi", "HSK 2"],
  ["没问题", "méi wèntí", "mei wenti", "không thành vấn đề", "HSK 2"],
  ["差不多", "chàbuduō", "chabuduo", "xấp xỉ, gần như nhau", "HSK 3"],
  ["算了吧", "suàn le ba", "suan le ba", "thôi bỏ qua đi", "HSK 3"],
  ["太棒了", "tài bàng le", "tai bang le", "tuyệt vời quá", "HSK 2"],
  ["开玩笑", "kāi wánxiào", "kai wanxiao", "nói đùa, trêu chọc", "HSK 3"],
  ["随随便便", "suísuí biànbiàn", "suisui bianbian", "tùy tiện, qua loa", "HSK 4"],
  ["各种各样", "gè zhǒng gè yàng", "ge zhong ge yang", "đủ mọi chủng loại", "HSK 3"],
  ["一心一意", "yì xīn yí yì", "yi xin yi yi", "một lòng một dạ", "HSK 4"],
  ["自由自在", "zì yóu zì zài", "zi you zi zai", "tự do tự tại", "HSK 4"],
  ["马到成功", "mǎ dào chéng gōng", "ma dao cheng gong", "mã đáo thành công", "HSK 4"],
  ["半途而废", "bàn tú ér fèi", "ban tu er fei", "bỏ cuộc giữa chừng", "HSK 4"],
  ["七上八下", "qī shàng bā xià", "qi shang ba xia", "thấp thỏm lo âu", "HSK 4"],
  ["自相矛盾", "zì xiāng máodùn", "zi xiang maodun", "tự mâu thuẫn", "HSK 4"],
  ["井底之蛙", "jǐng dǐ zhī wā", "jing di zhi wa", "ếch ngồi đáy giếng", "HSK 4"],
  ["不可思议", "bù kě sī yì", "bu ke si yi", "không thể tưởng tượng nổi", "HSK 4"],
  ["津津有味", "jīnjīn yǒu wèi", "jinjin you wei", "thích thú say mê", "HSK 4"],
  ["大吃一惊", "dà chī yì jīng", "da chi yi jing", "vô cùng kinh ngạc", "HSK 4"],
  ["千方百计", "qiān fāng bǎi jì", "qian fang bai ji", "trăm phương ngàn kế", "HSK 4"],
  ["全力以赴", "quán lì yǐ fù", "quan li yi fu", "dốc hết toàn lực", "HSK 4"],
  ["喜出望外", "xǐ chū wàng wài", "xi chu wang wai", "vui mừng khôn xiết", "HSK 4"],
  ["你好", "nǐ hǎo", "ni hao", "xin chào", "HSK 1"],
  ["再见", "zài jiàn", "zai jian", "tạm biệt", "HSK 1"],
  ["谢谢", "xièxie", "xiexie", "cảm ơn", "HSK 1"],
  ["没意见", "méi yìjiàn", "mei yijian", "không có ý kiến gì", "HSK 2"],
  ["怎么样", "zěnmeyàng", "zenmeyang", "thế nào, ra sao", "HSK 1"],
  ["多少钱", "duōshao qián", "duoshao qian", "bao nhiêu tiền", "HSK 1"],
  ["几点钟", "jǐ diǎn zhōng", "ji dian zhong", "mấy giờ", "HSK 1"],
  ["几个人", "jǐ gè rén", "ji ge ren", "mấy người", "HSK 1"],
  ["哪国人", "nǎ guó rén", "na guo ren", "người nước nào", "HSK 1"],
  ["叫什么", "jiào shénme", "jiao shenme", "tên là gì", "HSK 1"],
  ["去哪儿", "qù nǎr", "qu nar", "đi đâu", "HSK 1"],
  ["在哪儿", "zài nǎr", "zai nar", "ở đâu", "HSK 1"],
  ["是什么", "shì shénme", "shi shenme", "là cái gì", "HSK 1"],
  ["是谁", "shì shuí", "shi shui", "là ai", "HSK 1"],
  ["好不好", "hǎo bu hǎo", "hao bu hao", "được không, tốt không", "HSK 1"],
  ["行不行", "xíng bù xíng", "xing bu xing", "được hay không, có được không", "HSK 2"],
  ["是不是", "shì bú shì", "shi bu shi", "phải không, đúng không", "HSK 1"],
  ["能不能", "néng bù néng", "neng bu neng", "có thể... hay không", "HSK 1"],
  ["会不会", "huì bú huì", "hui bu hui", "có biết... hay không", "HSK 1"],
  ["有没有", "yǒu méi yǒu", "you mei you", "có... hay không", "HSK 1"],
  ["一路平安", "yī lù píng ān", "yi lu ping an", "Thượng lộ bình an, đi đường bình an", "HSK 3"],
  ["一路顺风", "yī lù shùn fēng", "yi lu shun feng", "Thuận buồm xuôi gió", "HSK 3"],
  ["恭喜发财", "gōng xǐ fā cái", "gong xi fa cai", "Cung hỉ phát tài", "HSK 3"],
  ["新年快乐", "xīn nián kuài lè", "xin nian kuai le", "Chúc mừng năm mới", "HSK 3"],
  ["生日快乐", "shēng rì kuài lè", "sheng ri kuai le", "Chúc mừng sinh nhật", "HSK 3"],
  ["一路走好", "yī lù zǒu hǎo", "yi lu zou hao", "Đi bình an (thường dùng trong tiễn đưa người mất hoặc đi xa)", "HSK 3"],
  ["不用谢", "bù yòng xiè", "bu yong xie", "Không cần khách sáo / Không có gì", "HSK 3"],
  ["没意思", "méi yì si", "mei yi si", "Nhàm chán, vô vị", "HSK 3"],
  ["有意思", "yǒu yì si", "you yi si", "Thú vị, hay", "HSK 3"],
  ["马马虎虎", "mǎ mǎ hū hū", "ma ma hu hu", "Tạm được, làng nhàng", "HSK 3"],
  ["多长时间", "duō cháng shí jiān", "duo chang shi jian", "Bao lâu (thời gian)", "HSK 3"],
  ["怎么走", "zěn me zǒu", "zen me zou", "Đi thế nào (hỏi đường)", "HSK 3"],
  ["为什么", "wèi shén me", "wei shen me", "Tại sao", "HSK 3"],
  ["看起来", "kàn qǐ lái", "kan qi lai", "Trông có vẻ, nhìn có vẻ", "HSK 3"],
  ["听起来", "tīng qǐ lái", "ting qi lai", "Nghe có vẻ", "HSK 3"],
  ["说实话", "shuō shí huà", "shuo shi hua", "Thành thật mà nói", "HSK 3"],
  ["一般来说", "yì bān lái shuō", "yi ban lai shuo", "Nói chung là", "HSK 3"],
  ["例如", "lì rú", "li ru", "Ví dụ như", "HSK 3"],
  ["比如", "bǐ rú", "bi ru", "Ví dụ", "HSK 3"],
  ["当然", "dāng rán", "dang ran", "Đương nhiên, tất nhiên", "HSK 3"],
  ["其实", "qí shí", "qi shi", "Thực ra, kỳ thực", "HSK 3"],
  ["马上", "mǎ shàng", "ma shang", "Ngay lập tức, tức thì", "HSK 3"],
  ["突然", "tū rán", "tu ran", "Đột nhiên", "HSK 3"],
  ["一直", "yì zhí", "yi zhi", "Cứ, luôn luôn, suốt", "HSK 3"],
  ["终于", "zhōng yú", "zhong yu", "Cuối cùng thì", "HSK 3"],
  ["加油", "jiā yóu", "jia you", "Cố lên!", "HSK 3"],
  ["经常", "jīng cháng", "jing chang", "Thường xuyên", "HSK 3"],
  ["常常", "cháng cháng", "chang chang", "Thường hay", "HSK 3"],
  ["有时候", "yǒu shí hou", "you shi hou", "Thỉnh thoảng, có lúc", "HSK 3"],
  ["偶尔", "ǒu'ěr", "ouer", "Thỉnh thoảng (tần suất thấp hơn)", "HSK 3"],
  ["总是", "zǒng shì", "zong shi", "Lúc nào cũng, luôn luôn", "HSK 3"],
  ["立刻", "lì kè", "li ke", "Lập tức, ngay tức khắc", "HSK 3"],
  ["赶快", "gǎn kuài", "gan kuai", "Nhanh chóng, mau lên", "HSK 3"],
  ["赶紧", "gǎn jǐn", "gan jin", "Tranh thủ, mau chóng", "HSK 3"],
  ["到底", "dào dǐ", "dao di", "Rốt cuộc, đến cùng", "HSK 3"],
  ["果然", "guǒ rán", "guo ran", "Quả nhiên, đúng như dự đoán", "HSK 3"],
  ["竟然", "jìng rán", "jing ran", "Lại có thể, lại (biểu thị sự bất ngờ)", "HSK 3"],
  ["甚至", "shèn zhì", "shen zhi", "Thậm chí", "HSK 3"],
];

/**
 * CẤP ĐỘ KHÓ: Sentence Patterns (Mẫu câu liên từ & Cấu trúc ngữ pháp / Chính phản)
 * Tổng cộng: 36 mẫu câu
 */
export const sentencePatternsVocabulary: VocabularyEntry[] = [
  ["虽然很忙，但是他很高兴。", "suīrán hěn máng, dànshì tā hěn gāoxìng.", "suiran hen mang danshi ta hen gaoxing", "Tuy rất bận nhưng anh ấy rất vui.", "HSK 3"],
  ["因为下雨，所以我们没去公园。", "yīnwèi xiàyǔ, suǒyǐ wǒmen méi qù gōngyuán.", "yinwei xiayu suoyi women mei qu gongyuan", "Vì trời mưa nên chúng tôi không đi công viên.", "HSK 2"],
  ["如果明天下雨，我们就不去。", "rúguǒ míngtiān xiàyǔ, wǒmen jiù bú qù.", "ruguo mingtian xiayu women jiu bu qu", "Nếu ngày mai trời mưa thì chúng ta không đi.", "HSK 3"],
  ["除了汉语以外，他还会说英语。", "chúle hànyǔ yǐwài, tā hái huì shuō yīngyǔ.", "chule hanyu yiwai ta hai hui shuo yingyu", "Ngoài tiếng Trung ra, anh ấy còn biết nói tiếng Anh.", "HSK 3"],
  ["他喜欢一边听音乐一边看书。", "tā xǐhuan yìbiān tīng yīnyuè yìbiān kànshū.", "ta xihuan yibian ting yinyue yibian kanshu", "Anh ấy thích vừa nghe nhạc vừa đọc sách.", "HSK 3"],
  ["他的汉语水平越来越高了。", "tā de hànyǔ shuǐpíng yuè lái yuè gāo le.", "ta de hanyu shuiping yue lai yue gao le", "Trình độ tiếng Trung của anh ấy ngày càng cao.", "HSK 3"],
  ["这个苹果又大又甜。", "zhè ge píngguǒ yòu dà yòu tián.", "zhe ge pingguo you da you tian", "Quả táo này vừa to lại vừa ngọt.", "HSK 3"],
  ["她不但漂亮，而且很聪明。", "tā búdàn piàoliang, érqiě hěn cōngming.", "ta budan piaoliang erqie hen congming", "Cô ấy không những xinh đẹp mà còn rất thông minh.", "HSK 3"],
  ["天气越来越热了。", "tiānqì yuè lái yuè rè le.", "tianqi yue lai yue re le", "Thời tiết càng ngày càng nóng rồi.", "HSK 3"],
  ["这里的风景太漂亮了！", "zhèlǐ de fēngjǐng tài piàoliang le!", "zheli de fengjing tai piaoliang le", "Phong cảnh ở đây đẹp quá!", "HSK 2"],
  ["你越努力，就会越幸运。", "nǐ yuè nǔlì, jiù huì yuè xìngyùn.", "ni yue nuli jiu hui yue xingyun", "Bạn càng nỗ lực thì sẽ càng may mắn.", "HSK 4"],
  ["只要坚持，就一定能成功。", "zhǐyào jiānchí, jiù yídìng néng chénggōng.", "zhiyao jianchi jiu yiding neng chenggong", "Chỉ cần kiên trì thì nhất định sẽ thành công.", "HSK 4"],
  ["无论多难，我都要学好中文。", "wúlùn duō nán, wǒ dōu yào xué hǎo zhōngwén.", "wulun duo nan wo dou yao xue hao zhongwen", "Dù khó thế nào tôi cũng phải học tốt tiếng Trung.", "HSK 4"],
  ["既然来了，就多玩几天吧。", "jìrán lái le, jiù duō wán jǐ tiān ba.", "jiran lai le jiu duo wan ji tian ba", "Đã đến rồi thì ở lại chơi thêm mấy ngày nhé.", "HSK 4"],
  ["即使下雨，比赛也照常进行。", "jíshǐ xiàyǔ, bǐsài yě zhàocháng jìnxíng.", "jishi xiayu bisai ye zhaochang jinxing", "Cho dù trời mưa thì cuộc thi vẫn diễn ra như thường.", "HSK 4"],
  ["大家如果没意见，我们就这么决定吧。", "dàjiā rúguǒ méi yìjiàn, wǒmen jiù zhème juéding ba.", "dajia ruguo mei yijian women jiu zheme jueding ba", "Mọi người nếu không có ý kiến gì, chúng ta quyết định vậy nhé.", "HSK 3"],
  ["他是不是你的汉语老师？", "tā shì bú shì nǐ de hànyǔ lǎoshī?", "ta shi bu shi ni de hanyu laoshi", "Anh ấy có phải là giáo viên tiếng Trung của bạn không?", "HSK 2"],
  ["这个字你能不能写？", "zhège zì nǐ néng bù néng xiě?", "zhege zi ni neng bu neng xie", "Chữ này bạn có viết được không?", "HSK 2"],
  ["你会不会做中国菜？", "nǐ huì bú huì zuò zhōngguó cài?", "ni hui bu hui zuo zhongguo cai", "Bạn có biết làm món ăn Trung Quốc không?", "HSK 2"],
  ["你有没有汉语字典？", "nǐ yǒu méi yǒu hànyǔ zìdiǎn?", "ni you mei you hanyu zidian", "Bạn có từ điển tiếng Trung không?", "HSK 2"],
  ["在这里我们住得好，吃得好。", "zài zhèli wǒmen zhù de hǎo, chī de hǎo.", "zai zheli women zhu de hao chi de hao", "Ở đây chúng tôi ở tốt, ăn ngon.", "HSK 2"],
  ["昨天我们去公园，玩得很高兴。", "zuótiān wǒmen qù gōngyuán, wán de hěn gāoxìng.", "zuotian women qu gongyuan wan de hen gaoxing", "Hôm qua chúng tôi đi công viên, chơi rất vui.", "HSK 2"],
  ["他说得太快了，我听不懂。", "tā shuō de tài kuài le, wǒ tīng bù dǒng.", "ta shuo de tai kuai le wo ting bu dong", "Anh ấy nói nhanh quá, tôi nghe không hiểu.", "HSK 2"],
  ["你的汉字写得很好。", "nǐ de hànzì xiě de hěn hǎo.", "ni de hanzi xie de hen hao", "Chữ Hán của bạn viết rất đẹp.", "HSK 2"],
  ["身体不舒服就要去医院。", "shēntǐ bù shūfu jiù yào qù yīyuàn.", "shenti bu shufu jiu yao qu yiyuan", "Cơ thể không khỏe là phải đi bệnh viện.", "HSK 2"],
  ["一天一个苹果，医生远离我。", "yì tiān yí gè píngguǒ, yīshēng yuánlí wǒ.", "yi tian yi ge pingguo yisheng yuanli wo", "Mỗi ngày một quả táo, bác sĩ tránh xa tôi.", "HSK 3"],
  ["因为...所以...", "yīn wèi... suǒ yǐ...", "yin wei suo yi", "Bởi vì... cho nên...", "HSK 3"],
  ["虽然...但是...", "suī rán... dàn shì...", "sui ran dan shi", "Mặc dù... nhưng...", "HSK 3"],
  ["不但...而且...", "bú dàn... ér qiě...", "bu dan er qie", "Không những... mà còn...", "HSK 3"],
  ["或者...或者...", "huò zhě... huò zhě...", "huo zhe huo zhe", "Hoặc là... hoặc là...", "HSK 3"],
  ["一边...一边...", "yī biān... yī biān...", "yi bian yi bian", "Vừa... vừa...", "HSK 3"],
  ["越...越...", "yuè... yuè...", "yue yue", "Càng... càng...", "HSK 3"],
  ["先...然后...", "xiān... rán hòu...", "xian ran hou", "Trước tiên... sau đó...", "HSK 3"],
  ["从...到...", "cóng... dào...", "cong dao", "Từ... đến...", "HSK 3"],
  ["比...得多", "bǐ... de duō", "bi de duo", "Hơn... rất nhiều (cấu trúc so sánh)", "HSK 3"],
  ["没有...那么...", "méi yǒu... nà me...", "mei you na me", "Không... bằng...", "HSK 3"],
];

/**
 * CẤP ĐỘ KHÓ: Context Sentences (Câu ngắn giao tiếp ngữ cảnh thực tế đời sống)
 * Tổng cộng: 388 câu ngữ cảnh
 */
export const contextSentencesVocabulary: VocabularyEntry[] = [
  ["请问去火车站应该怎么走？", "qǐngwèn qù huǒchēzhàn yīnggāi zěnme zǒu?", "qingwen qu huochezhan yinggai zenme zou", "Xin hỏi đi đến ga tàu hỏa đi đường nào?", "HSK 2"],
  ["这件衣服多少钱一件？", "zhè jiàn yīfu duōshao qián yí jiàn?", "zhe jian yifu duoshao qian yi jian", "Bộ quần áo này bao nhiêu tiền một bộ?", "HSK 2"],
  ["服务员，请给我们一份菜单。", "fúwùyuán, qǐng gěi wǒmen yí fèn càidān.", "fuwuyuan qing gei women yi fen caidan", "Phục vụ ơi, vui lòng cho chúng tôi một thực đơn.", "HSK 3"],
  ["我打算明年去北京大学留学。", "wǒ dǎsuàn míngnián qù běijīng dàxué liúxué.", "wo dasuan mingnian qu beijing daxue liuxue", "Tôi dự định năm sau đi du học Đại học Bắc Kinh.", "HSK 3"],
  ["飞机明天早上八点半起飞。", "fēijī míngtiān zǎoshang bā diǎn bàn qǐfēi.", "feiji mingtian zaoshang ba dian ban qifei", "Máy bay sáng mai 8 giờ rưỡi cất cánh.", "HSK 2"],
  ["你今天身体感觉怎么样了？", "nǐ jīntiān shēntǐ gǎnjué zěnmeyàng le?", "ni jintian shenti ganjue zenmeyang le", "Hôm nay trong người bạn cảm thấy thế nào rồi?", "HSK 2"],
  ["我们明天下午两点在图书馆见面。", "wǒmen míngtiān xiàwǔ liǎng diǎn zài túshūguǎn jiànmiàn.", "women mingtian xiawu liang dian zai tushuguan jianmian", "Chiều mai hai giờ chúng ta gặp nhau ở thư viện.", "HSK 3"],
  ["请问附近有中国银行吗？", "qǐngwèn fùjìn yǒu zhōngguó yínháng ma?", "qingwen fujin you zhongguo yinhang ma", "Xin hỏi gần đây có Ngân hàng Trung Quốc không?", "HSK 3"],
  ["这本书非常有意思，推荐你看。", "zhè běn shū fēicháng yǒu yìsi, tuījiàn nǐ kàn.", "zhe ben shu feichang you yisi tuijian ni kan", "Cuốn sách này rất hay, khuyên bạn nên đọc.", "HSK 3"],
  ["祝你生日快乐，学习进步！", "zhù nǐ shēngrì kuàilè, xuéxí jìnbù!", "zhu ni shengri kuaile xuexi jinbu", "Chúc bạn sinh nhật vui vẻ, học tập tiến bộ!", "HSK 2"],
  ["我想买两张去上海的高铁票。", "wǒ xiǎng mǎi liǎng zhāng qù shànghǎi de gāotiě piào.", "wo xiang mai liang zhang qu shanghai de gaotie piao", "Tôi muốn mua hai vé tàu cao tốc đi Thượng Hải.", "HSK 3"],
  ["今天的天气非常舒服，适合散步。", "jīntiān de tiānqì fēicháng shūfu, shìhé sànbù.", "jintian de tianqi feichang shufu shihe sanbu", "Thời tiết hôm nay rất dễ chịu, thích hợp đi dạo.", "HSK 3"],
  ["很高兴认识你，欢迎来到中国。", "hěn gāoxìng rènshi nǐ, huānyíng lái dào zhōngguó.", "hen gaoxing renshi ni huanying lai dao zhongguo", "Rất vui được quen bạn, chào mừng đến Trung Quốc.", "HSK 2"],
  ["医生说你需要多喝水多休息。", "yīshēng shuō nǐ xūyào duō hē shuǐ duō xiūxi.", "yisheng shuo ni xuyao duo he shui duo xiuxi", "Bác sĩ nói bạn cần uống nhiều nước và nghỉ ngơi.", "HSK 2"],
  ["这道中国菜味道非常地道。", "zhè dào zhōngguó cài wèidao fēicháng dìdao.", "zhe dao zhongguo cai weidao feichang didao", "Món ăn Trung Quốc này hương vị rất chuẩn vị.", "HSK 4"],
  ["老师，你好！", "lǎoshī, nǐ hǎo!", "laoshi ni hao", "Thưa thầy/cô, xin chào!", "HSK 1"],
  ["同学们，再见！", "tóngxuémen, zàijiàn!", "tongxuemen zaijian", "Các bạn học sinh, tạm biệt!", "HSK 1"],
  ["谢谢你帮我。", "xièxie nǐ bāng wǒ.", "xiexie ni bang wo", "Cảm ơn bạn đã giúp tôi.", "HSK 1"],
  ["不好意思，让您久等了。", "bù hǎoyìsi, ràng nín jiǔ děng le.", "bu haoyisi rang nin jiu deng le", "Ngại quá, để ngài phải đợi lâu rồi.", "HSK 2"],
  ["今天的天气怎么样？", "jīntiān de tiānqì zěnmeyàng?", "jintian de tianqi zenmeyang", "Thời tiết hôm nay thế nào?", "HSK 1"],
  ["这件衣服多少钱？", "zhè jiàn yīfu duōshao qián?", "zhe jian yifu duoshao qian", "Bộ quần áo này bao nhiêu tiền?", "HSK 1"],
  ["你们家里有几个人？", "nǐmen jiālǐ yǒu jǐ gè rén?", "nimen jiali you ji ge ren", "Nhà các bạn có mấy người?", "HSK 1"],
  ["请问你是哪国人？", "qǐngwèn nǐ shì nǎ guó rén?", "qingwen ni shi na guo ren", "Xin hỏi bạn là người nước nào?", "HSK 1"],
  ["你叫什么名字？", "nǐ jiào shénme míngzi?", "ni jiao shenme mingzi", "Bạn tên là gì?", "HSK 1"],
  ["你下午去哪儿？", "nǐ xiàwǔ qù nǎr?", "ni xiawu qu nar", "Buổi chiều bạn đi đâu?", "HSK 1"],
  ["我的手机在哪儿？", "wǒ de shǒujī zài nǎr?", "wo de shouji zai nar", "Điện thoại của tôi ở đâu?", "HSK 2"],
  ["桌子上的是什么？", "zhuōzi shàng shì shénme?", "zhuozi shang shi shenme", "Trên bàn là cái gì vậy?", "HSK 1"],
  ["门口的那个人是谁？", "ménkǒu de nà gè rén shì shuí?", "menkou de na ge ren shi shui", "Người ở ngoài cửa là ai thế?", "HSK 2"],
  ["我们下午去喝茶，好不好？", "wǒmen xiàwǔ qù hē chá, hǎo bu hǎo?", "women xiawu qu he cha hao bu hao", "Chiều nay chúng ta đi uống trà nhé, được không?", "HSK 1"],
  ["明天借我一本书，行不行？", "míngtiān jiè wǒ yì běn shū, xíng bù xíng?", "mingtian jie wo yi ben shu xing bu xing", "Ngày mai cho tôi mượn một cuốn sách, được chứ?", "HSK 2"],
  ["天黑了，我们回家吧。", "tiān hēi le, wǒmen huí jiā ba.", "tian hei le women hui jia ba", "Trời tối rồi, chúng ta về nhà thôi.", "HSK 2"],
  ["运动后我想喝水。", "yùndòng hòu wǒ xiǎng hē shuǐ.", "yundong hou wo xiang he shui", "Sau khi vận động tôi muốn uống nước.", "HSK 2"],
  ["中国人喜欢喝茶。", "zhōngguó rén xǐhuan hē chá.", "zhongguo ren xihuan he cha", "Người Trung Quốc thích uống trà.", "HSK 1"],
  ["爸爸正在给朋友打电话。", "bàba zhèngzài gěi péngyou dǎ diànhuà.", "baba zhengzai gei pengyou da dianhua", "Bố đang gọi điện thoại cho bạn.", "HSK 2"],
  ["弟弟在房间里安静地看书。", "dìdi zài fángjiān lǐ ānjìng de kàn shū.", "didi zai fangjian li anjing de kan shu", "Em trai đang đọc sách yên tĩnh trong phòng.", "HSK 2"],
  ["晚上我和家人一起看电视。", "wǎnshang wǒ hé jiārén yìqǐ kàn diànshì.", "wanshang wo he jiaren yiqi kan dianshi", "Buổi tối tôi cùng người thân xem ti vi.", "HSK 1"],
  ["周末我们去电影院看电影。", "zhōumò wǒmen qù diànyǐngyuàn kàn diànyǐng.", "zhoumo women qu dianyingyuan kan dianying", "Cuối tuần chúng ta đến rạp chiếu phim xem phim.", "HSK 2"],
  ["休息的时候，我喜欢听音乐。", "xiūxi de shíhou, wǒ xǐhuan tīng yīnyuè.", "xiuxi de shihou wo xihuan ting yinyue", "Lúc nghỉ ngơi, tôi thích nghe nhạc.", "HSK 2"],
  ["这里的苹果很新鲜，我们买水果吧。", "zhèlǐ de píngguǒ hěn xīnxiān, wǒmen mǎi shuǐguǒ ba.", "zheli de pingguo hen xinxian women mai shuiguo ba", "Táo ở đây rất tươi, chúng ta mua hoa quả nhé.", "HSK 3"],
  ["早上七点半，学生们去学校。", "zǎoshang qī diǎn bàn, xuéshēngmen qù xuéxiào.", "zaoshang qi dian ban xueshengmen qu xuexiao", "Sáng bảy rưỡi, các học sinh đi đến trường.", "HSK 1"],
  ["下午我有课，必须马上回学校。", "xiàwǔ wǒ yǒu kè, bìxū mǎshàng huí xuéxiào.", "xiawu wo you ke bixu mashang hui xuexiao", "Buổi chiều tôi có tiết, phải nhanh chóng về trường.", "HSK 3"],
  ["哥哥刚拿到驾照，会开车了。", "gēge gāng ná dào jiàzhào, huì kāichē le.", "gege gang na dao jiazhao hui kaiche le", "Anh trai vừa lấy bằng lái, biết lái xe rồi.", "HSK 3"],
  ["去北京出差，我们坐飞机去。", "qù běijīng chūchāi, wǒmen zuò fēijī qù.", "qu beijing chuchai women zuo feiji qu", "Đi Bắc Kinh công tác, chúng ta đi bằng máy bay.", "HSK 3"],
  ["下雨了，我们在路边坐出租车。", "xiàyǔ le, wǒmen zài lùbiān zuò chūzūchē.", "xiayu le women zai lubian zuo chuzuche", "Trời mưa rồi, chúng ta bắt taxi ở ven đường.", "HSK 2"],
  ["妈妈今天生病了，爸爸来做饭。", "māma jīntiān shēngbìng le, bàba lái zuò fàn.", "mama jintian shengbing le baba lai zuo fan", "Mẹ hôm nay ốm rồi, bố vào bếp nấu ăn.", "HSK 2"],
  ["姐姐在一家大公司工作。", "jiějie zài yì jiā dà gōngsī gōngzuò.", "jiejie zai yi jia da gongsi gongzuo", "Chị gái làm việc ở một công ty lớn.", "HSK 2"],
  ["我每天都花一个小时学习汉语。", "wǒ měitiān dōu huā yí gè xiǎoshí xuéxí hànyǔ.", "wo meitian dou hua yi ge xiaoshi xuexi hanyu", "Mỗi ngày tôi đều dành một tiếng để học tiếng Trung.", "HSK 2"],
  ["他的朋友会说汉语。", "tā de péngyou huì shuō hànyǔ.", "ta de pengyou hui shuo hanyu", "Bạn của anh ấy biết nói tiếng Trung.", "HSK 1"],
  ["练习写汉字需要很多时间。", "liànxí xiě hànzì xūyào hěn duō shíjiān.", "lianxi xie hanzi xuyao hen duo shijian", "Luyện viết chữ Hán cần rất nhiều thời gian.", "HSK 3"],
  ["哥哥现在在北京大学读书。", "gēge xiànzài zài běijīng dàxué dúshū.", "gege xianzai zai beijing daxue dushu", "Anh trai hiện đang học tập tại Đại học Bắc Kinh.", "HSK 2"],
  ["孩子十点钟就上床睡觉了。", "háizi shí diǎn zhōng jiù shàng chuáng shuìjiào le.", "haizi shi dian zhong jiu shang chuang shuijiao le", "Đứa trẻ mười giờ đúng là lên giường đi ngủ rồi.", "HSK 2"],
  ["工作累了，大家休息十分钟吧。", "gōngzuò lèi le, dàjiā xiūxi shí fēnzhōng ba.", "gongzuo lei le dajia xiuxi shi fenzhong ba", "Làm việc mệt rồi, mọi người nghỉ ngơi mười phút nhé.", "HSK 2"],
  ["初次见面，认识你很高兴。", "chūcì jiànmiàn, rènshi nǐ hěn gāoxìng.", "chuci jianmian renshi ni hen gaoxing", "Lần đầu gặp mặt, rất vui được quen biết bạn.", "HSK 2"],
  ["今天能来参加聚会，我很高兴。", "jīntiān néng lái cānjiā jùhuì, wǒ hěn gāoxìng.", "jintian neng lai canjia juhui wo hen gaoxing", "Hôm nay có thể đến tham gia buổi tiệc, tôi rất vui.", "HSK 3"],
  ["明天放假？太好了！", "míngtiān fàngjià? tài hǎo le!", "mingtian fangjia tai hao le", "Ngày mai được nghỉ lễ á? Tuyệt quá!", "HSK 2"],
  ["这双鞋我穿太大了。", "zhè shuāng xié wǒ chuān tài dà le.", "zhe shuang xie wo chuan tai da le", "Đôi giày này tôi đi bị rộng quá.", "HSK 2"],
  ["那个手机太贵了，我买不起。", "nà gè shǒujī tài guì le, wǒ mǎi bù qǐ.", "na ge shouji tai gui le wo mai bu qi", "Chiếc điện thoại kia đắt quá, tôi mua không nổi.", "HSK 3"],
  ["今天的作业太多了。", "jīntiān de zuòyè tài duō le.", "jintian de zuoye tai duo le", "Bài tập về nhà hôm nay nhiều quá.", "HSK 2"],
  ["我会说一点儿汉语。", "wǒ huì shuō yìdiǎnr hànyǔ.", "wo hui shuo yidianr hanyu", "Tôi biết nói một chút tiếng Trung.", "HSK 1"],
  ["请等我一会儿，马上就好。", "qǐng děng wǒ yí huìr, mǎshàng jiù hǎo.", "qing deng wo yi huir mashang jiu hao", "Xin đợi tôi một lát, xong ngay đây.", "HSK 2"],
  ["桌子上有一个苹果。", "zhuōzi shàng yǒu yí gè píngguǒ.", "zhuozi shang you yi ge pingguo", "Trên bàn có một quả táo.", "HSK 1"],
  ["请等我一下儿。", "qǐng děng wǒ yí xiàr.", "qing deng wo yi xiar", "Xin hãy đợi tôi một chút.", "HSK 2"],
  ["他来中国已经三年了。", "tā lái zhōngguó yǐjīng sān nián le.", "ta lai zhongguo yijing san nian le", "Anh ấy đến Trung Quốc đã được ba năm rồi.", "HSK 2"],
  ["我学汉语六个月了。", "wǒ xué hànyǔ liù gè yuè le.", "wo xue hanyu liu ge yue le", "Tôi học tiếng Trung được sáu tháng rồi.", "HSK 1"],
  ["离上课还有五分钟。", "lí shàngkè hái yǒu wǔ fēnzhōng.", "li shangke hai you wu fenzhong", "Cách giờ vào học vẫn còn năm phút.", "HSK 2"],
  ["现在是十点钟整。", "xiànzài shì shí diǎn zhōng zhěng.", "xianzai shi shi dian zhong zheng", "Bây giờ là đúng mười giờ.", "HSK 2"],
  ["今年是2026年。", "jīnnián shì èr líng èr liù nián.", "jinnian shi er ling er liu nian", "Năm nay là năm 2026.", "HSK 1"],
  ["明天天气怎么样？", "míngtiān tiānqì zěnmeyàng?", "mingtian tianqi zenmeyang", "Thời tiết ngày mai thế nào?", "HSK 1"],
  ["昨天我去商店买了很多东西。", "zuótiān wǒ qù shāngdiàn mǎi le hěn duō dōngxi.", "zuotian wo qu shangdian mai le hen duo dongxi", "Hôm qua tôi đi cửa hàng mua rất nhiều đồ.", "HSK 1"],
  ["今天是我的生日。", "jīntiān shì wǒ de shēngrì.", "jintian shi wo de shengri", "Hôm nay là sinh nhật của tôi.", "HSK 1"],
  ["上午我有两节汉语课。", "shàngwǔ wǒ yǒu liǎng jié hànyǔ kè.", "shangwu wo you liang jie hanyu ke", "Buổi sáng tôi có hai tiết tiếng Trung.", "HSK 2"],
  ["中午我在学校食堂吃饭。", "zhōngwǔ wǒ zài xuéxiào shítáng chīfàn.", "zhongwu wo zai xuexiao shitang chifan", "Buổi trưa tôi ăn cơm ở nhà ăn trường.", "HSK 2"],
  ["下午我们去打篮球，好吗？", "xiàwǔ wǒmen qù dǎ lánqiú, hǎo ma?", "xiawu women qu da lanqiu hao ma", "Buổi chiều chúng ta đi chơi bóng rổ nhé, được không?", "HSK 2"],
  ["晚上我七点回家。", "wǎnshang wǒ qī diǎn huí jiā.", "wanshang wo qi dian hui jia", "Buổi tối tôi về nhà lúc 7 giờ.", "HSK 1"],
  ["银行在学校的前面。", "yínháng zài xuéxiào de qiánmiàn.", "yinhang zai xuexiao de qianmian", "Ngân hàng ở phía trước trường học.", "HSK 2"],
  ["那个商店在医院的后面。", "nà gè shāngdiàn zài yīyuàn de hòumian.", "na ge shangdian zai yiyuan de houmian", "Cửa hàng kia ở phía sau bệnh viện.", "HSK 1"],
  ["杯子里面还有水吗？", "bēizi lǐmiàn hái yǒu shuǐ ma?", "beizi limian hai you shui ma", "Bên trong cốc vẫn còn nước không?", "HSK 1"],
  ["书上面有一只猫。", "shū shàngmiàn yǒu yì zhī māo.", "shu shangmian you yi zhi mao", "Bên trên cuốn sách có một con mèo.", "HSK 1"],
  ["椅子下面是什么？", "yǐzi xiàmiàn shì shénme?", "yizi xiamian shi shenme", "Bên dưới chiếc ghế là cái gì?", "HSK 1"],
  ["我很想去中国旅游。", "wǒ hěn xiǎng qù zhōngguó lǚyóu.", "wo hen xiang qu zhongguo luyou", "Tôi rất muốn đi du lịch Trung Quốc.", "HSK 2"],
  ["北京是中国的首都。", "běijīng shì zhōngguó de shǒudū.", "beijing shi zhongguo de shoudu", "Bắc Kinh là thủ đô của Trung Quốc.", "HSK 3"],
  ["我们的学校非常大。", "wǒmen de xuéxiào fēicháng dà.", "women de xuexiao feichang da", "Trường học của chúng tôi vô cùng lớn.", "HSK 2"],
  ["离春节还有几天，火车站人山人海。", "lí chūnjié hái yǒu jǐ tiān, huǒchēzhàn rénshānrénhǎi.", "li chunjie hai you ji tian huochezhan renshanrenhai", "Còn mấy ngày nữa là đến Tết, ga xe lửa đông nghịt người.", "HSK 4"],
  ["汉语是一门很有意思的语言。", "hànyǔ shì yì mén hěn yǒuyìsi de yǔyán.", "hanyu shi yi men hen youyisi de yuyan", "Tiếng Trung là một ngôn ngữ rất thú vị.", "HSK 3"],
  ["中国南方人主要吃米饭。", "zhōngguó nánfāng rén zhǔyào chī mǐfàn.", "zhongguo nanfang ren zhuyao chi mifan", "Người miền Nam Trung Quốc chủ yếu ăn cơm.", "HSK 3"],
  ["天热了，要多喝水。", "tiān rè le, yào duō hē shuǐ.", "tian re le yao duo he shui", "Trời nóng rồi, phải uống nhiều nước vào.", "HSK 1"],
  ["爸爸每天早晨都要喝一杯茶。", "bàba měitiān zǎochén dōu yào hē yì bēi chá.", "baba meitian zaochen dou yao he yi bei cha", "Bố mỗi ngày sáng sớm đều uống một cốc trà.", "HSK 2"],
  ["我家里养了一只黑色的猫。", "wǒ jiālǐ yǎng le yì zhī hēisè de māo.", "wo jiali yang le yi zhi heise de mao", "Nhà tôi nuôi một con mèo màu đen.", "HSK 2"],
  ["那只狗非常听话。", "nà zhī gǒu fēicháng tīnghuà.", "na zhi gou feichang tinghua", "Con chó kia cực kỳ nghe lời.", "HSK 3"],
  ["换季了，妈妈带我去买新衣服。", "huànjì le, māma dài wǒ qù mǎi xīn yīfu.", "huanji le mama dai wo qu mai xin yifu", "Đổi mùa rồi, mẹ dẫn tôi đi mua quần áo mới.", "HSK 3"],
  ["这个玻璃杯子很漂亮。", "zhè gè bōlí bēizi hěn piàoliang.", "zhe ge boli beizi hen piaoliang", "Cái cốc thủy tinh này rất đẹp.", "HSK 2"],
  ["笔记本电脑放在桌子上。", "bǐjìběn diànnǎo fàng zài zhuōzi shàng.", "bijiben diannao fang zai zhuozi shang", "Máy tính xách tay đặt ở trên bàn.", "HSK 2"],
  ["昨天我生病了，所以没去上学。", "zuótiān wǒ shēngbìng le, suǒyǐ méi qù shàngxué.", "zuotian wo shengbing le suoyi mei qu shangxue", "Hôm qua tôi bị ốm nên không đến trường.", "HSK 3"],
  ["医生叫他一天吃三次药。", "yīshēng jiào tā yī tiān chī sān cì yào.", "yisheng jiao ta yi tian chi san ci yao", "Bác sĩ bảo anh ấy uống thuốc ba lần một ngày.", "HSK 3"],
  ["你累了就早点儿休息吧。", "nǐ lèi le jiù zǎo diǎn 儿 xiū xi ba.", "ni lei le jiu zao dian 儿 xiu xi ba", "Cậu mệt thì đi nghỉ sớm đi.", "HSK 3"],
  ["他每天早上都去公园跑步。", "tā 每 tiān zǎoshang dōu qù gōngyuán pǎobù.", "ta 每 tian zaoshang dou qu gongyuan paobu", "Anh ấy đi chạy bộ ở công viên mỗi buổi sáng.", "HSK 3"],
  ["下午我们一起去踢足球怎么样？", "xiàwǔ wǒmen yìqǐ qù tī zúqiú zěnmeyàng?", "xiawu women yiqi qu ti zuqiu zenmeyang", "Chiều nay chúng ta cùng đi đá bóng thế nào?", "HSK 3"],
  ["我弟弟特别喜欢打篮球。", "wǒ 弟 弟 tèbié xǐhuan dǎ lánqiú.", "wo 弟 弟 tebie xihuan da lanqiu", "Em trai tôi đặc biệt thích chơi bóng rổ.", "HSK 3"],
  ["夏天很多人喜欢去海边游泳。", "xiàtiān hěn duō rén xǐhuan qù 海 边 yóuyǒng.", "xiatian hen duo ren xihuan qu 海 边 youyong", "Mùa hè rất nhiều người thích ra biển bơi.", "HSK 3"],
  ["暑假我想去云南旅游。", "暑 jià wǒ xiǎng qù 云 nán lǚyóu.", "暑 jia wo xiang qu 云 nan luyou", "Kỳ nghỉ hè tôi muốn đi du lịch Vân Nam.", "HSK 3"],
  ["妈妈去超市买东西了。", "māma qù chāoshì mǎi dôngxi le.", "mama qu chaoshi mai dongxi le", "Mẹ đi siêu thị mua đồ rồi.", "HSK 3"],
  ["周末我和朋友去逛街。", "zhōu 末 wǒ hé péngyou qù guàng jiē.", "zhou 末 wo he pengyou qu guang jie", "Cuối tuần tôi và bạn đi dạo phố.", "HSK 3"],
  ["今天晚上我来做饭。", "jīntiān wǎnshang wǒ lái zuòfàn.", "jintian wanshang wo lai zuofan", "Tối nay để tôi nấu ăn cho.", "HSK 3"],
  ["吃完饭后，她开始洗衣服。", "chī wán fàn 后, tā kāishǐ xǐ yīfu.", "chi wan fan 后 ta kaishi xi yifu", "Ăn cơm xong, cô ấy bắt đầu giặt quần áo.", "HSK 3"],
  ["星期六我要在家打扫房间。", "xīngqī liù wǒ 要 zài jiā dǎ sǎo fáng jiān.", "xingqi liu wo 要 zai jia da sao fang jian", "Thứ Bảy tôi phải ở nhà dọn dẹp phòng.", "HSK 3"],
  ["哥哥发烧了，妈妈带他去看病。", "哥 哥 fā shāo le, māma dài tā qù kàn bìng.", "哥 哥 fa shao le mama dai ta qu kan bing", "Anh trai bị sốt, mẹ đưa anh ấy đi khám bệnh.", "HSK 3"],
  ["我迷路了，只好向路人问路。", "wǒ mí lù le, 只 hǎo 向 lù rén wèn lù.", "wo mi lu le 只 hao 向 lu ren wen lu", "Tôi bị lạc đường, đành phải hỏi đường người qua đường.", "HSK 3"],
  ["第一次来北京，我差点儿迷路了。", "第 yī cì lái běijīng, wǒ chāi diǎn 儿 mí lù le.", "第 yi ci lai beijing wo chai dian 儿 mi lu le", "Lần đầu đến Bắc Kinh, tôi suýt thì lạc đường.", "HSK 3"],
  ["因为堵车，他今天上班迟到了。", "yīnwèi 堵 chē, tā jīntiān shàngbān chídào le.", "yinwei 堵 che ta jintian shangban chidao le", "Vì tắc đường, hôm nay anh ấy đi làm muộn.", "HSK 3"],
  ["他身体不舒服，向老板请假了。", "tā shēntǐ bù shūfu, 向 lǎobǎn qǐng jià le.", "ta shenti bu shufu 向 laoban qing jia le", "Anh ấy không khỏe nên đã xin nghỉ phép với sếp.", "HSK 3"],
  ["经理正在里面开会，请稍等。", "jīnglǐ zhèngzài lǐmiàn kāihuì, qǐng 稍 děng.", "jingli zhengzai limian kaihui qing 稍 deng", "Giám đốc đang họp ở bên trong, xin vui lòng đợi một chút.", "HSK 3"],
  ["我爸爸每天早上八点去上班。", "wǒ bàba 每 tiān zǎoshang bā diǎn qù shàngbān.", "wo baba 每 tian zaoshang ba dian qu shangban", "Bố tôi hàng ngày đi làm lúc 8 giờ sáng.", "HSK 3"],
  ["你几点下班？我们一起走吧。", "nǐ jǐ diǎn xià bān? wǒmen yìqǐ zǒu ba.", "ni ji dian xia ban women yiqi zou ba", "Mấy giờ cậu tan làm? Chúng ta cùng về nhé.", "HSK 3"],
  ["下午四点半学生们就放学了.", "xiàwǔ sì diǎn bàn 学 生 们 jiù fàng xué le.", "xiawu si dian ban 学 生 们 jiu fang xue le", "4 giờ rưỡi chiều học sinh tan trường.", "HSK 3"],
  ["铃声响了，老师开始上课。", "铃 声 响 le, lǎoshī kāishǐ shàng kè.", "铃 声 响 le laoshi kaishi shang ke", "Chuông reo rồi, giáo viên bắt đầu lên lớp.", "HSK 3"],
  ["下课后，同学们都去操场了。", "xià kè 后, tóngxué 们 dōu qù 操 场 le.", "xia ke 后 tongxue 们 dou qu 操 场 le", "Tan học xong, các bạn học sinh đều ra sân trường.", "HSK 3"],
  ["明天有汉语考试，我要好好复习。", "míngtiān yǒu hànyǔ kǎoshì, wǒ 要 hǎo hǎo fùxí.", "mingtian you hanyu kaoshi wo 要 hao hao fuxi", "Ngày mai có bài thi tiếng Trung, tôi phải ôn tập thật kỹ.", "HSK 3"],
  ["这次数学很难，但我还是及格了。", "zhè cì 数 学 hěn nan, dàn wǒ háishì jí gé le.", "zhe ci 数 学 hen nan dan wo haishi ji ge le", "Môn toán lần này rất khó, nhưng tôi vẫn qua.", "HSK 3"],
  ["他明年就要从大学毕业了。", "tā 明 nián jiù 要 cóng dà 学 bìyè le.", "ta 明 nian jiu 要 cong da 学 biye le", "Anh ấy năm sau sẽ tốt nghiệp đại học.", "HSK 3"],
  ["哥哥找工作很顺利，已经入职了。", "哥 哥 zhǎo gōngzuò hěn shùn lì, yǐjīng 入 职 le.", "哥 哥 zhao gongzuo hen shun li yijing 入 职 le", "Anh trai tìm việc rất thuận lợi, đã vào làm rồi.", "HSK 3"],
  ["明天我要去一家大公司面试。", "míngtiān wǒ 要 qù yī jiā dà gōngsī miàn shì.", "mingtian wo 要 qu yi jia da gongsi mian shi", "Ngày mai tôi phải đi phỏng vấn ở một công ty lớn.", "HSK 3"],
  ["他努力工作是为了多赚钱。", "tā nǔlì gōngzuò shì wèile duō zhuàn qián.", "ta nuli gongzuo shi weile duo zhuan qian", "Anh ấy chăm chỉ làm việc là để kiếm nhiều tiền hơn.", "HSK 3"],
  ["年轻人要学会理财，不要乱花钱。", "niánqīng rén 要 xuéhuì lǐ 财, bù 要 乱 huā qián.", "nianqing ren 要 xuehui li 财 bu 要 乱 hua qian", "Người trẻ phải học cách quản lý tài chính, đừng tiêu tiền bừa bãi.", "HSK 3"],
  ["每个月我都把一部分工资存起来。", "每 gè yuè wǒ dōu bǎ yī 部 fēn 工 资 cún qǐlái.", "每 ge yue wo dou ba yi 部 fen 工 资 cun qilai", "Mỗi tháng tôi đều cất đi một phần tiền lương.", "HSK 3"],
  ["他买手机不够钱，向我借钱。", "tā mǎi shǒujī bù 够 qián, 向 wǒ jiè qián.", "ta mai shouji bu 够 qian 向 wo jie qian", "Anh ấy mua điện thoại không đủ tiền nên mượn tiền tôi.", "HSK 3"],
  ["发工资后，他马上把钱还给我了。", "fā 工 资 后, tā mǎshàng bǎ qián huán gěi wǒ le.", "fa 工 资 后 ta mashang ba qian huan gei wo le", "Nhận lương xong, anh ấy trả lại tiền cho tôi ngay.", "HSK 3"],
  ["老师对我的作业非常满意。", "lǎoshī duì wǒ de zuòyè 非 常 mǎnyì.", "laoshi dui wo de zuoye 非 常 manyi", "Giáo viên rất hài lòng với bài tập của tôi.", "HSK 3"],
  ["听到这个好消息，大家都很高兴。", "tīng dào zhè gè hǎo 消 xi, dàjiā dōu hěn gāoxìng.", "ting dao zhe ge hao 消 xi dajia dou hen gaoxing", "Nghe tin tốt này, mọi người đều rất vui.", "HSK 3"],
  ["你别为这点小事生气了。", "nǐ bié 为 zhè diǎn xiǎo 事 shēngqì le.", "ni bie 为 zhe dian xiao 事 shengqi le", "Cậu đừng vì chút chuyện nhỏ này mà tức giận nữa.", "HSK 3"],
  ["妈妈很担心我在外面的安全。", "māma hěn dānxīn wǒ zài wàimiàn de ānquán.", "mama hen danxin wo zai waimian de anquan", "Mẹ rất lo lắng cho sự an toàn của tôi khi ở bên ngoài.", "HSK 3"],
  ["找不到护照，他急得直着急。", "zhǎo bù dào 护 zhào, tā 急 de 直 zháo jí.", "zhao bu dao 护 zhao ta 急 de 直 zhao ji", "Không tìm thấy hộ chiếu, anh ấy sốt ruột không thôi.", "HSK 3"],
  ["考试没考好，他心里很难难过。", "kǎoshì méi kǎo hǎo, tā xīn lǐ hěn nan nánguò.", "kaoshi mei kao hao ta xin li hen nan nanguo", "Thi không tốt, trong lòng anh ấy rất buồn.", "HSK 3"],
  ["有你在，我就放心了。", "yǒu nǐ zài, wǒ jiù fàngxīn le.", "you ni zai wo jiu fangxin le", "Có cậu ở đây, tôi yên tâm rồi.", "HSK 3"],
  ["她的故事让所有人都很感动。", "tā de gùshi ràng 所 yǒu rén dōu hěn gǎndòng.", "ta de gushi rang 所 you ren dou hen gandong", "Câu chuyện của cô ấy làm tất cả mọi người đều rất cảm động.", "HSK 3"],
  ["妹妹一个人在家觉得很害怕。", "妹 妹 yí gè rén zài jiā jué de hěn hàipà.", "妹 妹 yi ge ren zai jia jue de hen haipa", "Em gái ở nhà một mình cảm thấy rất sợ.", "HSK 3"],
  ["我觉得这本书非常有意思。", "wǒ jué de zhè běn shū 非 常 yǒu yìsi.", "wo jue de zhe ben shu 非 常 you yisi", "Tôi cảm thấy cuốn sách này vô cùng thú vị.", "HSK 3"],
  ["我以为他走了，原来还在。", "wǒ yǐ wéi tā zǒu le, 原 lái huán zài.", "wo yi wei ta zou le 原 lai huan zai", "Tôi cứ tưởng anh ấy đi rồi, hóa ra vẫn còn đây.", "HSK 3"],
  ["希望明天下雨能停。", "xīwàng míngtiān xiàyǔ néng 停.", "xiwang mingtian xiayu neng 停", "Hy vọng ngày mai trời ngớt mưa.", "HSK 3"],
  ["你寒假有什么打算？", "nǐ hánjià yǒu shénme dǎsuàn?", "ni hanjia you shenme dasuan", "Kỳ nghỉ đông cậu có dự định gì không?", "HSK 3"],
  ["我们正在准备 考试。", "wǒmen zhèngzài zhǔnbèi kǎoshì.", "women zhengzai zhunbei kaoshi", "Chúng tôi đang chuẩn bị cho kỳ thi.", "HSK 3"],
  ["他决定去北京学习汉语。", "tā juédìng qù běijīng xuéxí hànyǔ.", "ta jueding qu beijing xuexi hanyu", "Anh ấy quyết định đến Bắc Kinh học tiếng Trung.", "HSK 3"],
  ["爸爸同意我去参加夏令营。", "bàba tóngyì wǒ qù cānjiā 夏 令 营.", "baba tongyi wo qu canjia 夏 令 营", "Bố đồng ý cho tôi đi tham gia trại hè.", "HSK 3"],
  ["大家的意见一致，没有人反对。", "dàjiā de yìjiàn yī 致, méi yǒu rén fǎn duì.", "dajia de yijian yi 致 mei you ren fan dui", "Ý kiến mọi người đồng nhất, không ai phản đối cả.", "HSK 3"],
  ["谢谢你帮我这个大忙。", "xièxie nǐ bāng wǒ zhè gè dà 忙.", "xiexie ni bang wo zhe ge da 忙", "Cảm ơn bạn đã giúp tôi một việc lớn này.", "HSK 3"],
  ["谢谢你在医院照顾我。", "xièxie nǐ zài yīyuàn zhào gù wǒ.", "xiexie ni zai yiyuan zhao gu wo", "Cảm ơn bạn đã chăm sóc tôi ở bệnh viện.", "HSK 3"],
  ["欢迎光临，请问要点什么？", "huānyíng guāng 临, qǐng 问 要 diǎn shénme?", "huanying guang 临 qing 问 要 dian shenme", "Kính chào quý khách, xin hỏi quý khách muốn dùng gì?", "HSK 3"],
  ["非常谢谢你的热情招待。", "非 常 xièxie nǐ de rèqíng 招 待.", "非 常 xiexie ni de reqing 招 待", "Vô cùng cảm ơn sự tiếp đón nhiệt tình của bạn.", "HSK 3"],
  ["别那么客气，这是我应该做的。", "bié nàme kè qi, zhè shì wǒ yīnggāi zuò de.", "bie name ke qi zhe shi wo yinggai zuo de", "Đừng khách sáo thế, đây là việc tôi nên làm.", "HSK 3"],
  ["对不起，我来晚了。", "duìbuqǐ, wǒ lái wǎn le.", "duibuqi wo lai wan le", "Xin lỗi, tôi đến muộn.", "HSK 3"],
  ["对不起！ 没关系。", "duìbuqǐ! méi guānxi.", "duibuqi mei guanxi", "Xin lỗi! - Không sao đâu.", "HSK 3"],
  ["时间不早了，我们再见吧。", "shíjiān bù zǎo le, wǒmen zàijiàn ba.", "shijian bu zao le women zaijian ba", "Trời muộn rồi, chúng ta tạm biệt nhé.", "HSK 3"],
  ["祝你一路平安，到了给我发短信。", "祝 nǐ yī lù píng ān, dào le gěi wǒ fā duǎn xìn.", "祝 ni yi lu ping an dao le gei wo fa duan xin", "Chúc cậu đi đường bình an, đến nơi nhắn tin cho tôi nhé.", "HSK 3"],
  ["祝他乘飞机一路顺风。", "祝 tā chéng fēijī yī lù shùn fēng.", "祝 ta cheng feiji yi lu shun feng", "Chúc anh ấy đi máy bay thuận buồm xuôi gió.", "HSK 3"],
  ["过年时大家常常说“恭喜发财”。", "guònián 时 dàjiā cháng cháng shuō gōng xǐ fā cái.", "guonian 时 dajia chang chang shuo gong xi fa cai", "Vào dịp Tết mọi người thường nói \"Cung hỉ phát tài\".", "HSK 3"],
  ["祝爷爷奶奶新年快乐，身体健康。", "祝 yéye nǎinai xīn nián kuài lè, shēntǐ jiànkāng.", "祝 yeye nainai xin nian kuai le shenti jiankang", "Chúc ông bà năm mới vui vẻ, sức khỏe dồi dào.", "HSK 3"],
  ["祝你生日快乐，天天开心！", "祝 nǐ shēng rì kuài lè, tiān tiān kāi xīn!", "祝 ni sheng ri kuai le tian tian kai xin", "Chúc bạn sinh nhật vui vẻ, ngày nào cũng vui tươi!", "HSK 3"],
  ["親友们含泪送别，祝他一路走好。", "親 yǒu 们 含 泪 sòng bié, 祝 tā yī lù zǒu hǎo.", "親 you 们 含 泪 song bie 祝 ta yi lu zou hao", "Người thân bạn bè ngấn lệ tiễn biệt, chúc ông đi bình an.", "HSK 3"],
  ["能帮我个忙吗？ 没问题。", "néng bāng wǒ gè 忙 ma? méi wèntí.", "neng bang wo ge 忙 ma mei wenti", "Giúp tôi một việc được không? - Không thành vấn đề.", "HSK 3"],
  ["谢谢你！ 不用谢。", "xièxie nǐ! bù yòng xiè.", "xiexie ni bu yong xie", "Cảm ơn bạn! - Không có chi.", "HSK 3"],
  ["太感谢了。 不客气。", "tài gǎnxiè le. bú kèqi.", "tai ganxie le bu keqi", "Cảm ơn nhiều lắm. - Không có chi.", "HSK 3"],
  ["今天的电影真没意思，我想回家。", "jīntiān de diànyǐng zhēn méiyìsi, wǒ xiǎng huí jiā.", "jintian de dianying zhen meiyisi wo xiang hui jia", "Bộ phim hôm nay chán thật đấy, tôi muốn về nhà.", "HSK 3"],
  ["这本小说越看越有意思。", "zhè běn xiǎo shuō yuè kàn yuè yǒu yìsi.", "zhe ben xiao shuo yue kan yue you yisi", "Cuốn tiểu thuyết này càng đọc càng thấy thú vị.", "HSK 3"],
  ["我们的意见差不多，可以合作。", "wǒmen de yìjiàn chàbuduō, kě yǐ hézuò.", "women de yijian chabuduo ke yi hezuo", "Ý kiến của chúng ta gần như giống nhau, có thể hợp tác.", "HSK 3"],
  ["你汉语水平怎么样？ 马马虎虎。", "nǐ hànyǔ shuǐ 平 zěnmeyàng? mǎ mǎ hū hū.", "ni hanyu shui 平 zenmeyang ma ma hu hu", "Trình độ tiếng Trung của cậu thế nào? - Tạm được thôi.", "HSK 3"],
  ["从这里到机场要多长时间？", "cóng zhè lǐ dào jīchǎng 要 duō cháng shí jiān?", "cong zhe li dao jichang 要 duo chang shi jian", "Từ đây ra sân bay mất bao lâu?", "HSK 3"],
  ["师傅，这件衣服多少钱？", "师 傅, zhè jiàn yīfu duōshao qián?", "师 傅 zhe jian yifu duoshao qian", "Anh ơi, chiếc áo này bao nhiêu tiền?", "HSK 3"],
  ["请问现在是几点钟？", "qǐng 问 xiànzài shì jǐ diǎn zhōng?", "qing 问 xianzai shi ji dian zhong", "Xin hỏi bây giờ là mấy giờ rồi?", "HSK 3"],
  ["请问去火车站怎么走？", "qǐng 问 qù 火 chēzhàn zěn me zǒu?", "qing 问 qu 火 chezhan zen me zou", "Xin hỏi đi ga tàu hỏa đi thế nào?", "HSK 3"],
  ["你今天感觉身体怎么样？", "nǐ jīntiān gǎnjué shēntǐ zěnmeyàng?", "ni jintian ganjue shenti zenmeyang", "Hôm nay cậu cảm thấy trong người thế nào?", "HSK 3"],
  ["为什么你今天不上班？", "wèishénme nǐ jīntiān bù shàngbān?", "weishenme ni jintian bu shangban", "Tại sao hôm nay cậu không đi làm?", "HSK 3"],
  ["因为下雨，所以我们取消了爬山。", "yīnwèi xiàyǔ, suǒyǐ wǒmen 取 消 le páshān.", "yinwei xiayu suoyi women 取 消 le pashan", "Bởi vì trời mưa cho nên chúng tôi đã hủy lịch leo núi.", "HSK 3"],
  ["虽然很累，但是他还是完成了工作。", "suīrán hěn lèi, dànshì tā háishì wánchéng le gōngzuò.", "suiran hen lei danshi ta haishi wancheng le gongzuo", "Mặc dù rất mệt nhưng anh ấy vẫn hoàn thành công việc.", "HSK 3"],
  ["她不但会唱歌，而且会跳舞。", "tā bù dàn huì chànggē, ér 且 huì tiàowǔ.", "ta bu dan hui changge er 且 hui tiaowu", "Cô ấy không những biết hát mà còn biết múa.", "HSK 3"],
  ["周末我打算在家看书或者看电影。", "zhōu 末 wǒ dǎsuàn zài jiā kàn shū huòzhě kàn diànyǐng.", "zhou 末 wo dasuan zai jia kan shu huozhe kan dianying", "Cuối tuần tôi dự định ở nhà đọc sách hoặc xem phim.", "HSK 3"],
  ["他喜欢一边 听音乐一边 做作业。", "tā xǐhuan yìbiān tīng yīnyuè yìbiān zuò zuòyè.", "ta xihuan yibian ting yinyue yibian zuo zuoye", "Cậu ấy thích vừa nghe nhạc vừa làm bài tập.", "HSK 3"],
  ["越学汉语，我觉得越有意思。", "yuè xué hànyǔ, wǒ jué de yuè yǒu yìsi.", "yue xue hanyu wo jue de yue you yisi", "Càng học tiếng Trung, tôi càng thấy thú vị.", "HSK 3"],
  ["先洗手，然后再吃饭。", "xiān xǐ shǒu, ránhòu zài chī fàn.", "xian xi shou ranhou zai chi fan", "Rửa tay trước, sau đó mới ăn cơm.", "HSK 3"],
  ["银行营业时间是从周一到周五。", "yínháng yíng yè shíjiān shì cóng zhōu yī dào zhōu wǔ.", "yinhang ying ye shijian shi cong zhou yi dao zhou wu", "Thời gian làm việc của ngân hàng là từ thứ Hai đến thứ Sáu.", "HSK 3"],
  ["今天的气温比昨天冷得多。", "jīntiān de qì 温 bǐ zuótiān lěng de duō.", "jintian de qi 温 bi zuotian leng de duo", "Nhiệt độ hôm nay lạnh hơn hôm qua rất nhiều.", "HSK 3"],
  ["弟弟没有哥哥那么高。", "弟 弟 méi yǒu 哥 哥 nàme gāo.", "弟 弟 mei you 哥 哥 name gao", "Em trai không cao bằng anh trai.", "HSK 3"],
  ["这个主意听起来不错。", "zhè gè zhǔ yì tīng qǐ lái búcuò.", "zhe ge zhu yi ting qi lai bucuo", "Ý kiến này nghe có vẻ hay đấy.", "HSK 3"],
  ["说实话，这道菜我不太喜欢吃。", "shuō shí huà, zhè 道 cài wǒ bù tài xǐhuan chī.", "shuo shi hua zhe 道 cai wo bu tai xihuan chi", "Thành thật mà nói, món này tôi không thích ăn cho lắm.", "HSK 3"],
  ["一般来说，周末人会比较多。", "yì bān lái shuō, zhōu 末 rén huì bǐjiào duō.", "yi ban lai shuo zhou 末 ren hui bijiao duo", "Nói chung là, cuối tuần người sẽ khá đông.", "HSK 3"],
  ["我喜欢吃很多水果，例如苹果和香蕉。", "wǒ xǐhuan chī hěn duō shuǐ guǒ, lì rú píngguǒ hé 香 蕉.", "wo xihuan chi hen duo shui guo li ru pingguo he 香 蕉", "Tôi thích ăn rất nhiều loại hoa quả, ví dụ như táo và chuối.", "HSK 3"],
  ["很多运动我都喜欢，比如游泳和跑步。", "hěn duō yùndòng wǒ dōu xǐhuan, bǐrú yóuyǒng hé pǎobù.", "hen duo yundong wo dou xihuan biru youyong he paobu", "Rất nhiều môn thể thao tôi đều thích, ví dụ như bơi lội và chạy bộ.", "HSK 3"],
  ["明天你去吗？ 当然去。", "míngtiān nǐ qù ma? dāng rán qù.", "mingtian ni qu ma dang ran qu", "Ngày mai cậu đi không? - Đương nhiên là đi.", "HSK 3"],
  ["其实我早就知道了这个消息。", "qíshí wǒ zǎo jiù zhīdào le zhè gè 消 xi.", "qishi wo zao jiu zhidao le zhe ge 消 xi", "Thực ra tôi đã biết tin này từ sớm rồi.", "HSK 3"],
  ["别急，我马上就来。", "bié 急, wǒ mǎshàng jiù lái.", "bie 急 wo mashang jiu lai", "Đừng vội, tôi đến ngay đây.", "HSK 3"],
  ["突然下起了大雨，大家赶紧跑。", "tūrán xià qǐ le dà 雨, dàjiā gǎn jǐn pǎo.", "turan xia qi le da 雨 dajia gan jin pao", "Đột nhiên trời đổ mưa lớn, mọi người nhanh chóng chạy.", "HSK 3"],
  ["他一直在外面等我。", "tā yìzhí zài wàimiàn děng wǒ.", "ta yizhi zai waimian deng wo", "Anh ấy cứ đứng ở bên ngoài đợi tôi.", "HSK 3"],
  ["经过努力，他终于考上了大学。", "jīngguò nǔlì, tā zhōng yú kǎo shàng le dà 学.", "jingguo nuli ta zhong yu kao shang le da 学", "Trải qua sự nỗ lực, cuối cùng anh ấy cũng thi đỗ đại học.", "HSK 3"],
  ["我们好久没见面了，周末一起喝一杯吧。", "wǒmen hǎo jiǔ méi jiànmiàn le, zhōu 末 yìqǐ hē yī bēi ba.", "women hao jiu mei jianmian le zhou 末 yiqi he yi bei ba", "Chúng ta lâu lắm không gặp nhau rồi, cuối tuần cùng đi uống nước nhé.", "HSK 3"],
  ["晚饭后，全家人坐在一起聊天。", "wǎn fàn 后, quán jiā rén zuò zài yìqǐ liáo tiān.", "wan fan 后 quan jia ren zuo zai yiqi liao tian", "Sau bữa tối, cả nhà ngồi quây quần lại với nhau trò chuyện.", "HSK 3"],
  ["晚饭后去公园散步是一个好习惯。", "wǎn fàn 后 qù gōngyuán sànbù shì yí gè hǎo xíguàn.", "wan fan 后 qu gongyuan sanbu shi yi ge hao xiguan", "Sau bữa tối đi dạo công viên là một thói quen tốt.", "HSK 3"],
  ["下个月我要搬家到市中心去。", "xià gè yuè wǒ 要 bān jiā dào 市 中 xīn qù.", "xia ge yue wo 要 ban jia dao 市 中 xin qu", "Tháng sau tôi phải chuyển nhà ra trung tâm thành phố.", "HSK 3"],
  ["刚工作的时候，他在公司附近租房。", "刚 gōngzuò de shíhou, tā zài gōngsī fùjìn zū fáng.", "刚 gongzuo de shihou ta zai gongsi fujin zu fang", "Hồi mới đi làm, anh ấy thuê nhà ở gần công ty.", "HSK 3"],
  ["母亲周末总是把家里打扫得干干净净。", "母 亲 zhōu 末 zǒng shì bǎ jiā lǐ dǎsǎo de gān gānjìng 净.", "母 亲 zhou 末 zong shi ba jia li dasao de gan ganjing 净", "Mẹ cuối tuần nào cũng dọn dẹp nhà cửa sạch sẽ.", "HSK 3"],
  ["每天早上起床后，他先刷牙再洗脸。", "每 tiān zǎoshang qǐchuáng 后, tā xiān shuā yá zài xǐ liǎn.", "每 tian zaoshang qichuang 后 ta xian shua ya zai xi lian", "Mỗi sáng sau khi ngủ dậy, anh ấy đánh răng rồi mới rửa mặt.", "HSK 3"],
  ["睡觉前别忘了刷牙。", "shuìjiào 前 bié wàng le shuā yá.", "shuijiao 前 bie wang le shua ya", "Trước khi đi ngủ đừng quên đánh răng nhé.", "HSK 3"],
  ["你的头发太长了，该去理发了。", "nǐ de tóufa tài cháng le, 该 qù lǐ fà le.", "ni de toufa tai chang le 该 qu li fa le", "Tóc của cậu dài quá rồi, nên đi cắt tóc thôi.", "HSK 3"],
  ["游客们在长城前停下来照相。", "yóu 客 们 zài cháng 城 前 停 xiàlái zhào xiàng.", "you 客 们 zai chang 城 前 停 xialai zhao xiang", "Du khách dừng lại trước Vạn Lý Trường Thành để chụp ảnh.", "HSK 3"],
  ["这里的风景很美，我们一起拍照吧。", "zhè lǐ de 风 景 hěn 美, wǒmen yìqǐ pāi zhào ba.", "zhe li de 风 景 hen 美 women yiqi pai zhao ba", "Phong cảnh ở đây rất đẹp, chúng ta cùng chụp ảnh đi.", "HSK 3"],
  ["弟弟吃完饭就在房间里上网。", "弟 弟 chī wán fàn jiù zài 房 jiān lǐ shàngwǎng.", "弟 弟 chi wan fan jiu zai 房 jian li shangwang", "Em trai ăn cơm xong là lên mạng trong phòng.", "HSK 3"],
  ["请把这份报告发给我。", "qǐng bǎ zhè fèn bàogào fā gěi wǒ.", "qing ba zhe fen baogao fa gei wo", "Xin hãy gửi báo cáo này cho tôi.", "HSK 3"],
  ["妈妈，我到学校了，给您打电话报平安。", "māma, wǒ dào xuéxiào le, gěi 您 dǎ diànhuà 报 平 ān.", "mama wo dao xuexiao le gei 您 da dianhua 报 平 an", "Mẹ ơi, con đến trường rồi, gọi điện báo bình an cho mẹ đây.", "HSK 3"],
  ["他正在开车，没法接电话。", "tā zhèngzài kāichē, méi 法 jiē diàn huà.", "ta zhengzai kaiche mei 法 jie dian hua", "Anh ấy đang lái xe, không thể nghe điện thoại.", "HSK 3"],
  ["看到未接来电，他马上回了一个电话。", "kàn dào 未 jiē lái 电, tā mǎshàng huí le yí gè 电 话.", "kan dao 未 jie lai 电 ta mashang hui le yi ge 电 话", "Thấy cuộc gọi nhỡ, anh ấy lập tức gọi lại.", "HSK 3"],
  ["有事请给我发短信，我可能听不到电话。", "yǒu 事 qǐng gěi wǒ fā duǎn xìn, wǒ kěnéng tīng bù dào 电 话.", "you 事 qing gei wo fa duan xin wo keneng ting bu dao 电 话", "Có việc gì hãy nhắn tin cho tôi, tôi có thể không nghe thấy điện thoại.", "HSK 3"],
  ["累的时候，我喜欢闭上眼睛听音乐。", "lèi de shíhou, wǒ xǐhuan 闭 shàng 眼 睛 tīng yīnyuè.", "lei de shihou wo xihuan 闭 shang 眼 睛 ting yinyue", "Những lúc mệt mỏi, tôi thích nhắm mắt nghe nhạc.", "HSK 3"],
  ["妹妹特别喜欢在睡前看小说。", "妹 妹 tèbié xǐhuan zài shuì 前 kàn xiǎo shuō.", "妹 妹 tebie xihuan zai shui 前 kan xiao shuo", "Em gái đặc biệt thích đọc tiểu thuyết trước khi đi ngủ.", "HSK 3"],
  ["爷爷晚饭后习惯坐着看电视。", "yéye wǎn fàn 后 xíguàn zuò zhe kàn diànshì.", "yeye wan fan 后 xiguan zuo zhe kan dianshi", "Ông nội sau bữa tối có thói quen ngồi xem tivi.", "HSK 3"],
  ["周末我们去电影院看电影吧。", "zhōu 末 wǒmen qù diànyǐng 院 kàn diànyǐng ba.", "zhou 末 women qu dianying 院 kan dianying ba", "Cuối tuần chúng ta ra rạp xem phim đi.", "HSK 3"],
  ["小孩不能把太多时间花在玩游戏上。", "xiǎo 孩 bùnéng bǎ tài duō shíjiān huā zài wán yóu xì shàng.", "xiao 孩 buneng ba tai duo shijian hua zai wan you xi shang", "Trẻ con không được dành quá nhiều thời gian vào việc chơi game.", "HSK 3"],
  ["她从小就展现出了画画的天赋。", "tā cóng xiǎo jiù 展 现 chū le huàhuà de tiān 赋.", "ta cong xiao jiu 展 现 chu le huahua de tian 赋", "Cô ấy từ nhỏ đã bộc lộ thiên hướng vẽ tranh.", "HSK 3"],
  ["刚开始学汉字时，写字要一笔一画。", "刚 kāishǐ 学 汉 zì 时, xiězì 要 yī bǐ yī huà.", "刚 kaishi 学 汉 zi 时 xiezi 要 yi bi yi hua", "Mới bắt đầu học chữ Hán, viết chữ phải từng nét một.", "HSK 3"],
  ["放学回家后，他先做作业再玩。", "fàng xué huí jiā 后, tā xiān zuò zuòyè zài wán.", "fang xue hui jia 后 ta xian zuo zuoye zai wan", "Tan học về nhà, anh ấy làm bài tập xong rồi mới chơi.", "HSK 3"],
  ["考试前几天，大家都在紧张地复习功课。", "kǎoshì 前 jǐ tiān, dàjiā dōu zài jǐnzhāng de fù xí gōng kè.", "kaoshi 前 ji tian dajia dou zai jinzhang de fu xi gong ke", "Mấy ngày trước kỳ thi, mọi người đều đang ôn tập bài vở căng thẳng.", "HSK 3"],
  ["写论文需要去图书馆查很多资料。", "xiě 论 文 xūyào qù túshūguǎn 查 hěn duō 资 料.", "xie 论 文 xuyao qu tushuguan 查 hen duo 资 料", "Viết luận văn cần phải đến thư viện tra cứu rất nhiều tài liệu.", "HSK 3"],
  ["遇到不会的生词，要习惯查字典。", "yùdào bù huì de 生 cí, 要 xíguàn chá zì diǎn.", "yudao bu hui de 生 ci 要 xiguan cha zi dian", "Gặp từ mới không biết, phải tập thói quen tra từ điển.", "HSK 3"],
  ["课堂上不懂的地方，下课后可以向老师问问题。", "课 堂 shàng bù dǒng de dìfang, xià kè 后 kě yǐ 向 lǎoshī wèn wèn tí.", "课 堂 shang bu dong de difang xia ke 后 ke yi 向 laoshi wen wen ti", "Chỗ nào trên lớp không hiểu, tan học có thể hỏi giáo viên.", "HSK 3"],
  ["老师点了他的名字，让他回答问题。", "lǎoshī diǎn le tā de míngzi, ràng tā huí dá wèn tí.", "laoshi dian le ta de mingzi rang ta hui da wen ti", "Giáo viên gọi tên anh ấy, bảo anh ấy trả lời câu hỏi.", "HSK 3"],
  ["这句话我看了好几遍才懂其中的意思。", "zhè jù 话 wǒ kàn le hǎo jǐ 遍 cái dǒng 其 中 de yìsi.", "zhe ju 话 wo kan le hao ji 遍 cai dong 其 中 de yisi", "Câu này tôi đọc mấy lần mới hiểu ý nghĩa bên trong.", "HSK 3"],
  ["遇到事情要冷静，不要动不动就发脾气。", "yùdào shìqíng 要 lěng jìng, bù 要 dòng bù dòng jiù fā pí qi.", "yudao shiqing 要 leng jing bu 要 dong bu dong jiu fa pi qi", "Gặp chuyện phải bình tĩnh, đừng hở một tí là nổi giận.", "HSK 3"],
  ["我只是跟你开玩笑，你别当真。", "wǒ 只 shì gēn nǐ kāi wánxiào, nǐ bié dāng zhēn.", "wo 只 shi gen ni kai wanxiao ni bie dang zhen", "Tôi chỉ đùa với cậu thôi, đừng tưởng thật nhé.", "HSK 3"],
  ["导游一路上给我们讲了很多好玩的笑话。", "导 yóu yī lùshang gěi wǒmen jiǎng le hěn duō hǎo wán de xiào 话.", "导 you yi lushang gei women jiang le hen duo hao wan de xiao 话", "Hướng dẫn viên dọc đường kể cho chúng tôi nghe rất nhiều câu chuyện cười hay.", "HSK 3"],
  ["大家都在为活动方案出主意。", "dàjiā dōu zài 为 huódòng fāng 案 chū zhǔ yi.", "dajia dou zai 为 huodong fang 案 chu zhu yi", "Mọi người đều đang hiến kế cho phương án hoạt động.", "HSK 3"],
  ["遇到困难不要怕，要积极想办法解决。", "yùdào kùnnan bù 要 pà, 要 jījí xiǎng bàn fǎ jiějué.", "yudao kunnan bu 要 pa 要 jiji xiang ban fa jiejue", "Gặp khó khăn đừng sợ, phải tích cực tìm cách giải quyết.", "HSK 3"],
  ["这件事情太重大了，我需要时间下决定。", "zhè jiàn shìqíng tài 重 dà le, wǒ xūyào shíjiān xià jué dìng.", "zhe jian shiqing tai 重 da le wo xuyao shijian xia jue ding", "Việc này quá lớn, tôi cần thời gian để đưa ra quyết định.", "HSK 3"],
  ["机会总是留给做好准备的人。", "jīhuì zǒng shì liú gěi zuò hǎo zhǔnbèi de rén.", "jihui zong shi liu gei zuo hao zhunbei de ren", "Cơ hội luôn dành cho những người đã chuẩn bị sẵn sàng.", "HSK 3"],
  ["这位老教授教学经验非常丰富。", "zhè wèi lǎo jiāo 授 jiāo 学 jīngyàn 非 常 fēngfù.", "zhe wei lao jiao 授 jiao 学 jingyan 非 常 fengfu", "Vị giáo sư lớn tuổi này có kinh nghiệm giảng dạy vô cùng phong phú.", "HSK 3"],
  ["只要我们努力，就一定对考试有信心。", "只 要 wǒmen nǔlì, jiù yídìng duì kǎoshì yǒu xìn xīn.", "只 要 women nuli jiu yiding dui kaoshi you xin xin", "Chỉ cần chúng ta nỗ lực, nhất định sẽ có lòng tin với kỳ thi.", "HSK 3"],
  ["我对中国历史非常有兴趣。", "wǒ duì zhōngguó lìshǐ 非 常 yǒu xìng qù.", "wo dui zhongguo lishi 非 常 you xing qu", "Tôi vô cùng có hứng thú với lịch sử Trung Quốc.", "HSK 3"],
  ["孩子们对科学实验很感兴趣。", "孩 子 们 duì kēxué 实 验 hěn gǎn xìngqù.", "孩 子 们 dui kexue 实 验 hen gan xingqu", "Lũ trẻ rất có hứng thú với các thí nghiệm khoa học.", "HSK 3"],
  ["你说的这番话确实很有道理。", "nǐ shuō de zhè 番 话 确 实 hěn yǒu dào li.", "ni shuo de zhe 番 话 确 实 hen you dao li", "Những lời cậu nói quả thực rất có lý.", "HSK 3"],
  ["这件事跟我没关系，我不知道。", "zhè jiàn 事 gēn wǒ méi guānxi, wǒ bù zhīdào.", "zhe jian 事 gen wo mei guanxi wo bu zhidao", "Việc này không liên quan gì đến tôi, tôi không biết.", "HSK 3"],
  ["吃完药后，病情终于起作用了，不那么烧了。", "chī wán yào 后, bìng 情 zhōng yú qǐ zuò yòng le, bù nàme shāo le.", "chi wan yao 后 bing 情 zhong yu qi zuo yong le bu name shao le", "Uống thuốc xong, bệnh tình cuối cùng cũng phát huy tác dụng, không còn sốt cao nữa.", "HSK 3"],
  ["电脑突然黑屏了，可能是硬件出问题了。", "diànnǎo tūrán 黑 屏 le, kěnéng shì 硬 jiàn chū wèn tí le.", "diannao turan 黑 屏 le keneng shi 硬 jian chu wen ti le", "Máy tính đột nhiên tối màn hình, có thể phần cứng đã xảy ra vấn đề.", "HSK 3"],
  ["在外地读书的时候，我常常想念家乡的饭菜。", "zài wàidì dúshū de shíhou, wǒ cháng cháng xiǎng niàn jiā 乡 de fàn cài.", "zai waidi dushu de shihou wo chang chang xiang nian jia 乡 de fan cai", "Những lúc đi học xa nhà, tôi thường nhớ cơm nhà nấu.", "HSK 3"],
  ["当众答错问题让他觉得很丢面子。", "dāng 众 答 cuò wèntí ràng tā jué de hěn diū miàn zi.", "dang 众 答 cuo wenti rang ta jue de hen diu mian zi", "Trả lời sai câu hỏi trước đám đông khiến anh ấy cảm thấy rất mất mặt.", "HSK 3"],
  ["做人要诚实，不要老想着去占便宜。", "zuò rén 要 chéngshí, bù 要 lǎo xiǎng zhe qù zhàn pián yí.", "zuo ren 要 chengshi bu 要 lao xiang zhe qu zhan pian yi", "Làm người phải thành thật, đừng lúc nào cũng nghĩ đến chuyện chiếm lợi.", "HSK 3"],
  ["这款新手机在年轻人群中非常受欢迎。", "zhè 款 xīn shǒujī zài niánqīng rén 群 中 非 常 shòu huān yíng.", "zhe 款 xin shouji zai nianqing ren 群 中 非 常 shou huan ying", "Mẫu điện thoại mới này rất được giới trẻ yêu thích.", "HSK 3"],
  ["航班因大 雾而受了影响。", "航 bān 因 dà 雾 ér shòu le yǐngxiǎng.", "航 ban 因 da 雾 er shou le yingxiang", "Chuyến bay bị ảnh hưởng bởi sương mù dày đặc.", "HSK 3"],
  ["孩子昨晚开始发烧，妈妈急忙带他去医院。", "孩 子 昨 wǎn kāishǐ fā shāo, māma 急 忙 dài tā qù yīyuàn.", "孩 子 昨 wan kaishi fa shao mama 急 忙 dai ta qu yiyuan", "Đứa trẻ tối qua bắt đầu sốt, mẹ vội vàng đưa đi bệnh viện.", "HSK 3"],
  ["天气变冷了，出门多穿点，小心感冒。", "tiānqì 变 lěng le, chūmén duō chuān diǎn, xiǎoxīn gǎnmào.", "tianqi 变 leng le chumen duo chuan dian xiaoxin ganmao", "Thời tiết trở lạnh rồi, ra đường mặc ấm vào, cẩn thận kẻo cảm cúm.", "HSK 3"],
  ["他咳嗽得很厉害，连觉都睡不好。", "tā ké sou de hěn 厉 害, 连 jiào dōu shuì bù hǎo.", "ta ke sou de hen 厉 害 连 jiao dou shui bu hao", "Anh ấy ho rất dữ dội, đến ngủ cũng không ngon giấc.", "HSK 3"],
  ["感冒的症状包括打喷嚏和流鼻涕。", "gǎnmào de 症 状 bāokuò dǎ 喷 嚏 hé liú bí tì.", "ganmao de 症 状 baokuo da 喷 嚏 he liu bi ti", "Triệu chứng của cảm lạnh bao gồm hắt hơi và sổ mũi.", "HSK 3"],
  ["吃了不干净的冷饮，他开始肚子疼。", "chī le bù gānjìng de lěng 饮, tā kāishǐ dù zi téng.", "chi le bu ganjing de leng 饮 ta kaishi du zi teng", "Ăn đồ lạnh không sạch sẽ, anh ấy bắt đầu đau bụng.", "HSK 3"],
  ["工作压力太大了，导致他最近经常头疼。", "gōngzuò 压 lì tài dà le, dǎozhì tā zuìjìn jīngcháng tóu téng.", "gongzuo 压 li tai da le daozhi ta zuijin jingchang tou teng", "Áp lực công việc lớn quá khiến anh ấy dạo này hay bị đau đầu.", "HSK 3"],
  ["护士拿来温度计给他量体温。", "hùshi ná lái wēndù jì gěi tā liàng tǐ wēn.", "hushi na lai wendu ji gei ta liang ti wen", "Y tá mang nhiệt kế đến đo thân nhiệt cho anh ấy.", "HSK 3"],
  ["去医院看病前，先要在窗口排队挂号。", "qù yīyuàn kàn bìng 前, xiān 要 zài chuāng 口 pái duì guà hào.", "qu yiyuan kan bing 前 xian 要 zai chuang 口 pai dui gua hao", "Trước khi đi khám bệnh ở viện, phải xếp hàng lấy số ở quầy trước.", "HSK 3"],
  ["午饭吃饱了，下午才有力气工作。", "午 fàn chī bǎo le, xiàwǔ cái yǒu lì qì gōngzuò.", "午 fan chi bao le xiawu cai you li qi gongzuo", "Buổi trưa ăn no rồi, chiều mới có sức làm việc.", "HSK 3"],
  ["聚会上他喝了太多酒，结果喝醉了。", "聚 huì shàng tā hē le tài duō jiǔ, jiéguǒ hē zuì le.", "聚 hui shang ta he le tai duo jiu jieguo he zui le", "Trong buổi tụ tập anh ấy uống nhiều rượu quá, kết quả là say mèm.", "HSK 3"],
  ["爬完山后大家都很累，也很口渴。", "pá wán 山 后 dàjiā dōu hěn lèi, 也 hěn kǒu kě.", "pa wan 山 后 dajia dou hen lei 也 hen kou ke", "Leo núi xong mọi người đều rất mệt và khát nước.", "HSK 3"],
  ["减肥也不能饿肚子，那样对身体不好。", "减 肥 也 bùnéng è dù zi, nàyàng duì shēntǐ bù hǎo.", "减 肥 也 buneng e du zi nayang dui shenti bu hao", "Giảm cân cũng không thể để bụng đói, như thế không tốt cho cơ thể.", "HSK 3"],
  ["服务员，请拿菜单来，我们要点菜。", "fúwùyuán, qǐng ná càidān lái, wǒmen 要 diǎn cài.", "fuwuyuan qing na caidan lai women 要 dian cai", "Phục vụ ơi, mang thực đơn ra đây, chúng tôi gọi món.", "HSK 3"],
  ["这顿我来买单。 别介，今天我请客。", "zhè 顿 wǒ lái mǎi dān. bié 介, jīntiān wǒ qǐng 客.", "zhe 顿 wo lai mai dan bie 介 jintian wo qing 客", "Bữa này để tôi thanh toán. - Đừng khách sáo, hôm nay tôi mời.", "HSK 3"],
  ["吃完饭后，爸爸去柜台结账。", "chī wán fàn 后, bàba qù 柜 台 jié zhàng.", "chi wan fan 后 baba qu 柜 台 jie zhang", "Ăn cơm xong, bố ra quầy thu ngân thanh toán.", "HSK 3"],
  ["菜点多了吃不完，我们打包带走吧。", "cài diǎn duō le chī bù wán, wǒmen dǎ bāo dàizǒu ba.", "cai dian duo le chi bu wan women da bao daizou ba", "Gọi nhiều món ăn không hết, chúng ta gói mang về nhé.", "HSK 3"],
  ["买票的人太多了，大家都在耐心地排队。", "mǎi piào de rén tài duō le, dàjiā dōu zài 耐 xīn de pái duì.", "mai piao de ren tai duo le dajia dou zai 耐 xin de pai dui", "Người mua hàng đông quá, mọi người đều đang kiên nhẫn xếp hàng.", "HSK 3"],
  ["进游乐园之前，需要先去窗口买票。", "jìn yóu 乐 园 zhī 前, xūyào xiān qù chuāng 口 mǎi piào.", "jin you 乐 园 zhi 前 xuyao xian qu chuang 口 mai piao", "Trước khi vào khu vui chơi, cần phải ra quầy mua vé trước.", "HSK 3"],
  ["列车员正在车门口认真检票。", "列 chē 员 zhèngzài chē ménkǒu rènzhēn jiǎn piào.", "列 che 员 zhengzai che menkou renzhen jian piao", "Nhân viên đường sắt đang nghiêm túc soát vé ở cửa toa tàu.", "HSK 3"],
  ["听到发车铃声，旅客们赶紧上车。", "tīng dào fā chē 铃 声, 旅 客 们 gǎn jǐn shàng chē.", "ting dao fa che 铃 声 旅 客 们 gan jin shang che", "Nghe tiếng chuông xuất phát, hành khách vội vàng lên xe.", "HSK 3"],
  ["下一站就要下车了，请提前准备。", "xià yī 站 jiù 要 xià chē le, qǐng tí 前 zhǔnbèi.", "xia yi 站 jiu 要 xia che le qing ti 前 zhunbei", "Trạm tới là phải xuống xe rồi, xin chuẩn bị trước.", "HSK 3"],
  ["去那个小镇没有直达车，需要在中途转车。", "qù nà gè xiǎo 镇 méi yǒu 直 达 chē, xūyào zài 中 tú zhuǎn chē.", "qu na ge xiao 镇 mei you 直 达 che xuyao zai 中 tu zhuan che", "Đi thị trấn đó không có xe đi thẳng, cần phải đổi xe dọc đường.", "HSK 3"],
  ["在前面的地铁站换乘二号线。", "zài qiánmiàn de dìtiě 站 huàn chéng èr hào 线.", "zai qianmian de ditie 站 huan cheng er hao 线", "Đổi sang tuyến số 2 tại ga tàu điện ngầm phía trước.", "HSK 3"],
  ["乘客们请注意，前往北京的航班现在开始登机。", "chéng 客 们 qǐng zhù yì, 前 wǎng běijīng de 航 bān xiànzài kāishǐ dēng jī.", "cheng 客 们 qing zhu yi 前 wang beijing de 航 ban xianzai kaishi deng ji", "Hành khách xin lưu ý, chuyến bay đi Bắc Kinh bây giờ bắt đầu lên máy bay.", "HSK 3"],
  ["飞机因为天气原因推迟了起飞时间。", "fēijī yīnwèi tiānqì 原 因 推 chí le qǐfēi shíjiān.", "feiji yinwei tianqi 原 因 推 chi le qifei shijian", "Máy bay vì lý do thời tiết nên đã hoãn thời gian cất cánh.", "HSK 3"],
  ["飞机平稳地降落在机场跑道上。", "fēijī 平 稳 de jiàngluò zài jīchǎng pǎo 道 shàng.", "feiji 平 稳 de jiangluo zai jichang pao 道 shang", "Máy bay hạ cánh êm ái trên đường băng sân bay.", "HSK 3"],
  ["经理下周要 出差 去上海三天。", "jīnglǐ xià zhōu 要 chū chāi qù shàng 海 sān tiān.", "jingli xia zhou 要 chu chai qu shang 海 san tian", "Giám đốc tuần sau phải đi công tác ở Thượng Hải ba ngày.", "HSK 3"],
  ["全家人计划去海边 度假 一周。", "quán jiā rén jìhuà qù 海 边 dù jià yī zhōu.", "quan jia ren jihua qu 海 边 du jia yi zhou", "Cả nhà lên kế hoạch đi biển nghỉ mát một tuần.", "HSK 3"],
  ["妈妈去买菜时，让我 照看 一下弟弟。", "māma qù mǎi cài 时, ràng wǒ zhào kàn yī xià 弟 弟.", "mama qu mai cai 时 rang wo zhao kan yi xia 弟 弟", "Lúc mẹ đi chợ mua đồ, bảo tôi trông nom em trai một lát.", "HSK 3"],
  ["做销售工作需要经常跟不同的人 打交道。", "zuò xiāo 售 gōngzuò xūyào jīngcháng gēn bùtóng de rén dǎ jiāo dào.", "zuo xiao 售 gongzuo xuyao jingchang gen butong de ren da jiao dao", "Làm công việc kinh doanh cần phải thường xuyên giao thiệp với những người khác nhau.", "HSK 3"],
  ["叔叔年轻时去外 语城市 做生意。", "shūshu niánqīng 时 qù wài 语 chéngshì zuò shēng yì.", "shushu nianqing 时 qu wai 语 chengshi zuo sheng yi", "Hồi trẻ chú đi thành phố lớn buôn bán.", "HSK 3"],
  ["他攒够了钱，准备在步行街 开店。", "tā 攒 够 le qián, zhǔnbèi zài 步 xíng jiē kāi diàn.", "ta 攒 够 le qian zhunbei zai 步 xing jie kai dian", "Anh ấy tiết kiệm đủ tiền, chuẩn bị mở cửa hàng ở phố đi bộ.", "HSK 3"],
  ["这家超市全天二十四小时 营业。", "zhè jiā chāoshì quán tiān èr shí sì xiǎoshí yíng yè.", "zhe jia chaoshi quan tian er shi si xiaoshi ying ye", "Siêu thị này mở cửa phục vụ suốt 24 tiếng.", "HSK 3"],
  ["换季的时候，商场里的衣服都在 打折。", "huàn 季 de shíhou, shāngchǎng lǐ de yīfu dōu zài dǎ zhé.", "huan 季 de shihou shangchang li de yifu dou zai da zhe", "Vào lúc giao mùa, quần áo trong trung tâm thương mại đều giảm giá.", "HSK 3"],
  ["店庆期间有很大的 促销 活动。", "店 庆 期 jiān yǒu hěn dà de cù xiāo huódòng.", "店 庆 期 jian you hen da de cu xiao huodong", "Nhân dịp kỷ niệm thành lập quán có hoạt động khuyến mãi rất lớn.", "HSK 3"],
  ["博物馆周一对外 免费 开放。", "博 物 馆 zhōu yī duì wài miǎn fèi kāifàng.", "博 物 馆 zhou yi dui wai mian fei kaifang", "Bảo tàng mở cửa miễn phí cho công chúng vào thứ Hai.", "HSK 3"],
  ["这个停车场是按小时 收费 的。", "zhè gè 停 chē 场 shì 按 xiǎoshí shōu fèi de.", "zhe ge 停 che 场 shi 按 xiaoshi shou fei de", "Bãi gửi xe này thu phí theo giờ.", "HSK 3"],
  ["先生，请问您付现金还是 刷卡？", "xiānsheng, qǐng 问 您 fù xiàn jīn háishì shuā kǎ?", "xiansheng qing 问 您 fu xian jin haishi shua ka", "Thưa anh, anh trả tiền mặt hay quẹt thẻ?", "HSK 3"],
  ["现在很少人出门 付现金 了，大家都用手机。", "xiànzài hěn shǎo rén chūmén fù xiàn jīn le, dàjiā dōu yòng shǒujī.", "xianzai hen shao ren chumen fu xian jin le dajia dou yong shouji", "Bây giờ rất ít người ra đường trả tiền mặt, ai cũng dùng điện thoại.", "HSK 3"],
  ["健身房现在 办卡 有优惠。", "健 shēn 房 xiànzài bàn kǎ yǒu 优 惠.", "健 shen 房 xianzai ban ka you 优 惠", "Phòng tập gym bây giờ làm thẻ có ưu đãi.", "HSK 3"],
  ["公交卡里的钱用完了，需要去 充值。", "公 交 kǎ lǐ de qián yòng wán le, xūyào qù chōng zhí.", "公 交 ka li de qian yong wan le xuyao qu chong zhi", "Tiền trong thẻ xe buýt dùng hết rồi, cần phải đi nạp tiền.", "HSK 3"],
  ["输入正确的 密码 才能取钱。", "输 入 zhèngquè de mì mǎ cái néng qǔ qián.", "输 入 zhengque de mi ma cai neng qu qian", "Nhập đúng mật khẩu mới có thể rút tiền.", "HSK 3"],
  ["顺路去 ATM 机 取 一点儿 钱。", "shùn lù qù A T M jī 取 yì diǎnr qián.", "shun lu qu a t m ji 取 yi dianr qian", "Tiện đường ghé qua cây ATM rút một ít tiền.", "HSK 3"],
  ["年底发了奖金，爸爸带去银行 存钱。", "nián dǐ fā le 奖 金, bàba dài qù yínháng cún qián.", "nian di fa le 奖 金 baba dai qu yinhang cun qian", "Cuối năm phát tiền thưởng, bố mang ra ngân hàng gửi tiết kiệm.", "HSK 3"],
  ["请在合同的最后一页 签字。", "qǐng zài hétong de zuì 后 yī 页 qiān zì.", "qing zai hetong de zui 后 yi 页 qian zi", "Xin hãy ký tên vào trang cuối cùng của hợp đồng.", "HSK 3"],
  ["这份文件还需要领导 盖章 才能生效。", "zhè fèn 文 jiàn huán xūyào lǐngdǎo gài zhāng cái néng 生 效.", "zhe fen 文 jian huan xuyao lingdao gai zhang cai neng 生 效", "Tài liệu này còn cần lãnh đạo đóng dấu mới có hiệu lực.", "HSK 3"],
  ["报名需要身份证复印件，我去前面 复印。", "bàomíng xūyào shēn fèn 证 fù yìn jiàn, wǒ qù qiánmiàn fù yìn.", "baoming xuyao shen fen 证 fu yin jian wo qu qianmian fu yin", "Đăng ký cần bản sao căn cước công dân, tôi ra phía trước photo đây.", "HSK 3"],
  ["报告已经写好了，现在把它 打印 出来。", "bàogào yǐjīng xiě hǎo le, xiànzài bǎ tā dǎ yìn chūlái.", "baogao yijing xie hao le xianzai ba ta da yin chulai", "Báo cáo đã viết xong rồi, bây giờ in nó ra thôi.", "HSK 3"],
  ["请把这份合同给对方 发 一个 传真。", "qǐng bǎ zhè fèn hétong gěi duì fāng fā yí gè chuán zhēn.", "qing ba zhe fen hetong gei dui fang fa yi ge chuan zhen", "Xin hãy gửi một bản fax hợp đồng này cho phía đối phương.", "HSK 3"],
  ["爷爷习惯用手写信并去邮局 寄信。", "yéye xíguàn yòng shǒu xiě xìn 并 qù 邮 局 jì xìn.", "yeye xiguan yong shou xie xin 并 qu 邮 局 ji xin", "Ông nội có thói quen viết thư tay rồi ra bưu điện gửi thư.", "HSK 3"],
  ["能在这个时代 收 到一封亲笔 信 觉得很温暖。", "néng zài zhè gè 时 代 收 dào yī 封 亲 bǐ xìn jué de hěn 温 暖.", "neng zai zhe ge 时 代 收 dao yi 封 亲 bi xin jue de hen 温 暖", "Có thể nhận được một bức thư tay trong thời đại này cảm thấy rất ấm áp.", "HSK 3"],
  ["妈妈做了一些家乡菜让我 寄包裹 给哥哥。", "māma zuò le yìxiē jiā 乡 cài ràng wǒ jì bāo guǒ gěi 哥 哥.", "mama zuo le yixie jia 乡 cai rang wo ji bao guo gei 哥 哥", "Mẹ làm một ít món ăn quê hương bảo tôi gửi bưu kiện cho anh hai.", "HSK 3"],
  ["网上买的东西到了，我要去楼下 收快递。", "wǎngshàng mǎi de dōngxi dào le, wǒ 要 qù lóu xià shōu kuài dì.", "wangshang mai de dongxi dao le wo 要 qu lou xia shou kuai di", "Đồ mua trên mạng đến rồi, tôi phải xuống lầu nhận hàng chuyển phát nhanh.", "HSK 3"],
  ["经理不在办公室，您有什么话可以 留言。", "jīnglǐ bù zài bàngōngshì, 您 yǒu shénme 话 kě yǐ liú yán.", "jingli bu zai bangongshi 您 you shenme 话 ke yi liu yan", "Giám đốc không có ở phòng làm việc, anh có lời gì có thể để lại lời nhắn.", "HSK 3"],
  ["麻烦你帮我 转告 他，明天会议取消了。", "máfan nǐ bāng wǒ zhuǎn gào tā, míngtiān huìyì 取 消 le.", "mafan ni bang wo zhuan gao ta mingtian huiyi 取 消 le", "Làm phiền bạn chuyển lời giúp tôi cho anh ấy, buổi họp ngày mai bị hủy rồi.", "HSK 3"],
  ["毕业后我们还要保持 联系 呀。", "bìyè 后 wǒmen huán 要 bǎo chí liánxì 呀.", "biye 后 women huan 要 bao chi lianxi 呀", "Tốt nghiệp xong chúng ta vẫn phải giữ liên lạc đấy nhé.", "HSK 3"],
  ["每天运动可以 保持 身体健康。", "每 tiān yùndòng kě yǐ bǎo chí shēntǐ jiànkāng.", "每 tian yundong ke yi bao chi shenti jiankang", "Mỗi ngày vận động có thể duy trì sức khỏe cơ thể.", "HSK 3"],
  ["我已经 习惯 了早睡早起的生活。", "wǒ yǐjīng xíguàn le zǎo shuì zǎo qǐ de 生 huó.", "wo yijing xiguan le zao shui zao qi de 生 huo", "Tôi đã quen với cuộc sống ngủ sớm dậy sớm rồi.", "HSK 3"],
  ["刚到一个新环境，需要一点时间去 适应。", "刚 dào yí gè xīn huánjìng, xūyào yī diǎn shíjiān qù shì yìng.", "刚 dao yi ge xin huanjing xuyao yi dian shijian qu shi ying", "Mới đến một môi trường mới, cần một chút thời gian để thích nghi.", "HSK 3"],
  ["学习外语最重要的是每天 坚持。", "xuéxí wài 语 zuì zhòngyào de shì 每 tiān jiān chí.", "xuexi wai 语 zui zhongyao de shi 每 tian jian chi", "Học ngoại ngữ điều quan trọng nhất là mỗi ngày đều kiên trì.", "HSK 3"],
  ["遇到困难不要轻言 放弃。", "yùdào kùnnan bù 要 轻 言 fàngqì.", "yudao kunnan bu 要 轻 言 fangqi", "Gặp khó khăn đừng vội thốt lên từ bỏ.", "HSK 3"],
  ["只要你足够 努力，梦想一定会实现。", "只 要 nǐ 足 够 nǔlì, 梦 xiǎng yídìng huì shíxiàn.", "只 要 ni 足 够 nuli 梦 xiang yiding hui shixian", "Chỉ cần bạn đủ nỗ lực, ước mơ nhất định sẽ thành hiện thực.", "HSK 3"],
  ["比赛马上开始，大家一起喊 加油！", "bǐsài mǎshàng kāishǐ, dàjiā yìqǐ 喊 jiā yóu!", "bisai mashang kaishi dajia yiqi 喊 jia you", "Cuộc thi sắp bắt đầu rồi, mọi người cùng hô cố lên!", "HSK 3"],
  ["路面结冰了，走路要 小心。", "lù 面 jié 冰 le, zǒulù 要 xiǎoxīn.", "lu 面 jie 冰 le zoulu 要 xiaoxin", "Mặt đường đóng băng rồi, đi đứng phải cẩn thận.", "HSK 3"],
  ["开车时请务必 注意 交通安全。", "kāichē 时 qǐng 务 必 zhù yì 交 tōng ānquán.", "kaiche 时 qing 务 必 zhu yi 交 tong anquan", "Lái xe xin hãy chú ý an toàn giao thông.", "HSK 3"],
  ["有我在这里帮衬，你大可 放心。", "yǒu wǒ zài zhè lǐ bāng 衬, nǐ dà kě fàngxīn.", "you wo zai zhe li bang 衬 ni da ke fangxin", "Có tôi ở đây giúp đỡ, cậu hoàn toàn có thể yên tâm.", "HSK 3"],
  ["因为他做题太 粗心 了，所以丢了很多分。", "yīnwèi tā zuò tí tài cū xīn le, suǒyǐ diū le hěn duō fēn.", "yinwei ta zuo ti tai cu xin le suoyi diu le hen duo fen", "Vì anh ấy làm bài quá cẩu thả nên đã mất rất nhiều điểm.", "HSK 3"],
  ["他是一个做事非常 认真 的人。", "tā shì yí gè zuò 事 非 常 rènzhēn de rén.", "ta shi yi ge zuo 事 非 常 renzhen de ren", "Anh ấy là một người làm việc vô cùng nghiêm túc.", "HSK 3"],
  ["这个项目由我来全面 负责。", "zhè gè 项 目 yóu wǒ lái quán 面 fùzé.", "zhe ge 项 目 you wo lai quan 面 fuze", "Dự án này do tôi toàn quyền chịu trách nhiệm.", "HSK 3"],
  ["把任务交给他，我觉得挺 靠谱 的。", "bǎ rènwù 交 gěi tā, wǒ jué de 挺 kào pǔ de.", "ba renwu 交 gei ta wo jue de 挺 kao pu de", "Giao nhiệm vụ cho anh ấy, tôi thấy khá đáng tin cậy.", "HSK 3"],
  ["自己在家做饭比去外面吃更 省钱。", "zìjǐ zài jiā zuòfàn bǐ qù wàimiàn chī gèng shěng qián.", "ziji zai jia zuofan bi qu waimian chi geng sheng qian", "Tự nấu ăn ở nhà tiết kiệm tiền hơn ra ngoài ăn.", "HSK 3"],
  ["水是宝贵的资源，不能随便 浪费。", "shuǐ shì 宝 guì de 资 源, bùnéng suíbiàn làngfèi.", "shui shi 宝 gui de 资 源 buneng suibian langfei", "Nước là tài nguyên quý giá, không thể lãng phí bừa bãi.", "HSK 3"],
  ["年轻人多 吃苦 对将来有好处。", "niánqīng rén duō chī kǔ duì jiānglái yǒu hǎo 处.", "nianqing ren duo chi ku dui jianglai you hao 处", "Người trẻ chịu khó chịu khổ một chút sẽ có lợi cho tương lai.", "HSK 3"],
  ["爷爷奶奶辛苦了一辈子，现在该退休 享福 了。", "yéye nǎinai 辛 kǔ le yī 辈 子, xiànzài 该 tuì xiū xiǎng fú le.", "yeye nainai 辛 ku le yi 辈 子 xianzai 该 tui xiu xiang fu le", "Ông bà vất vả cả đời, bây giờ nên về hưu hưởng phúc rồi.", "HSK 3"],
  ["国庆节假期，很多人选择出门 旅游。", "guó 庆 Jié jià 期, hěn duō rén xuǎnzé chūmén lǚyóu.", "guo 庆 jie jia 期 hen duo ren xuanze chumen luyou", "Dịp nghỉ lễ Quốc khánh, rất nhiều người chọn đi du lịch.", "HSK 3"],
  ["明天学校组织同学们去博物馆 参观。", "míngtiān xuéxiào 组 织 tóngxué 们 qù 博 物 馆 cānguān.", "mingtian xuexiao 组 织 tongxue 们 qu 博 物 馆 canguan", "Ngày mai nhà trường tổ chức cho học sinh đi tham quan bảo tàng.", "HSK 3"],
  ["游客们在导游的带领下 游览 古镇。", "yóu 客 们 zài 导 yóu de dài 领 xià yóu lǎn 古 镇.", "you 客 们 zai 导 you de dai 领 xia you lan 古 镇", "Du khách dưới sự dẫn dắt của hướng dẫn viên đi vãn cảnh trấn cổ.", "HSK 3"],
  ["坐在窗前一边喝茶一边 欣赏 夜景。", "zuò zài chuāng 前 yìbiān hē chá yìbiān xīn shǎng 夜 景.", "zuo zai chuang 前 yibian he cha yibian xin shang 夜 景", "Ngồi bên cửa sổ vừa uống trà vừa thưởng thức cảnh đêm.", "HSK 3"],
  ["毕业典礼上，大家纷纷合影 拍照留念。", "bìyè 典 礼 shàng, dàjiā 纷 纷 合 影 pāi zhào liú niàn.", "biye 典 礼 shang dajia 纷 纷 合 影 pai zhao liu nian", "Trong lễ tốt nghiệp, mọi người tấp nập chụp ảnh lưu niệm cùng nhau.", "HSK 3"],
  ["顾客在超市里自由 购买 所需物品。", "顾 客 zài chāoshì lǐ zì yóu gòu mǎi 所 需 物 品.", "顾 客 zai chaoshi li zi you gou mai 所 需 物 品", "Khách hàng tự do mua sắm các vật phẩm cần thiết trong siêu thị.", "HSK 3"],
  ["她在柜台前仔细 挑选 喜欢的衣服。", "tā zài 柜 台 前 仔 细 tiāo xuǎn xǐhuan de yīfu.", "ta zai 柜 台 前 仔 细 tiao xuan xihuan de yifu", "Cô ấy tỉ mỉ lựa chọn bộ quần áo mình thích trước quầy hàng.", "HSK 3"],
  ["这件裙子很好看，我可以 试穿 一下吗?", "zhè jiàn qúnzi hěn hǎo kàn, wǒ kě yǐ shì chuān yī xià ma?", "zhe jian qunzi hen hao kan wo ke yi shi chuan yi xia ma", "Chiếc váy này đẹp quá, tôi có thể mặc thử một chút được không?", "HSK 3"],
  ["这套西装穿在他身上非常 合身。", "zhè 套 xī 装 chuān zài tā shēn shàng 非 常 hé shēn.", "zhe 套 xi 装 chuan zai ta shen shang 非 常 he shen", "Bộ vest này mặc lên người anh ấy vô cùng vừa vặn.", "HSK 3"],
  ["买完东西后，他在收银台 付账。", "mǎi wán dōngxi 后, tā zài 收 银 台 fù zhàng.", "mai wan dongxi 后 ta zai 收 银 台 fu zhang", "Mua đồ xong, anh ấy trả tiền tại quầy thu ngân.", "HSK 3"],
  ["售货员数好钱，把 找零 递给顾客。", "售 货 员 数 hǎo qián, bǎ zhǎo líng dì gěi 顾 客.", "售 货 员 数 hao qian ba zhao ling di gei 顾 客", "Nhân viên bán hàng đếm tiền xong, đưa tiền thối lại cho khách.", "HSK 3"],
  ["消费完后，记得向商家索要 发票。", "消 fèi wán 后, jìde 向 商 jiā 索 要 fā piào.", "消 fei wan 后 jide 向 商 jia 索 要 fa piao", "Tiêu dùng xong, nhớ đòi hóa đơn từ người bán hàng.", "HSK 3"],
  ["这种水果今天在做 特价 促销。", "zhè zhǒng shuǐ guǒ jīntiān zài zuò tè jià cù xiāo.", "zhe zhong shui guo jintian zai zuo te jia cu xiao", "Loại hoa quả này hôm nay đang bán giá ưu đãi.", "HSK 3"],
  ["这件衣服虽然便宜，但是 质量 很好。", "zhè jiàn yīfu suīrán piányi, dànshì zhìliàng hěn hǎo.", "zhe jian yifu suiran pianyi danshi zhiliang hen hao", "Bộ váy này tuy rẻ nhưng chất lượng rất tốt.", "HSK 3"],
  ["他买鞋子只选自己熟悉的 品牌。", "tā mǎi xié 子 只 xuǎn zìjǐ shú 悉 de pǐn pái.", "ta mai xie 子 只 xuan ziji shu 悉 de pin pai", "Anh ấy mua giày chỉ chọn thương hiệu quen thuộc của mình.", "HSK 3"],
  ["今年流行这种简约风格的 款式。", "jīn nián liú xíng zhè zhǒng 简 约 风 gé de kuǎn shì.", "jin nian liu xing zhe zhong 简 约 风 ge de kuan shi", "Năm nay thịnh hành kiểu dáng phong cách tối giản này.", "HSK 3"],
  ["请问这双鞋有我的 尺码 吗？", "qǐng 问 zhè shuāng xié yǒu wǒ de chǐ mǎ ma?", "qing 问 zhe shuang xie you wo de chi ma ma", "Xin hỏi đôi giày này có size của tôi không?", "HSK 3"],
  ["这款包包有黑色和红色两种 颜色。", "zhè 款 bāo bāo yǒu hēisè hé hóngsè liǎng zhǒng yánsè.", "zhe 款 bao bao you heise he hongse liang zhong yanse", "Mẫu túi xách này có hai màu là đen và đỏ.", "HSK 3"],
  ["顾客对这次购物服务表示很 满意。", "顾 客 duì zhè cì gòuwù fúwù biǎoshì hěn mǎnyì.", "顾 客 dui zhe ci gouwu fuwu biaoshi hen manyi", "Khách hàng bày tỏ rất hài lòng với dịch vụ mua sắm lần này.", "HSK 3"],
  ["发现商品有质量问题，可以申请 退货。", "fāxiàn 商 品 yǒu zhìliàng wèntí, kě yǐ shēnqǐng tuì huò.", "faxian 商 品 you zhiliang wenti ke yi shenqing tui huo", "Phát hiện hàng hóa có vấn đề về chất lượng, có thể xin trả hàng.", "HSK 3"],
  ["码数买大了，我想去店里 换货。", "mǎ 数 mǎi dà le, wǒ xiǎng qù 店 lǐ huàn huò.", "ma 数 mai da le wo xiang qu 店 li huan huo", "Mua size to quá, tôi muốn ra cửa hàng đổi hàng.", "HSK 3"],
  ["这家餐馆不仅菜好吃，而且 服务态度 很好。", "zhè jiā 餐 馆 bù 仅 cài hǎochī, ér 且 fú wù tài dù hěn hǎo.", "zhe jia 餐 馆 bu 仅 cai haochi er 且 fu wu tai du hen hao", "Quán ăn này không chỉ món ăn ngon mà thái độ phục vụ cũng rất tốt.", "HSK 3"],
  ["咖啡馆的 环境 很安静，适合看书。", "kāfēi 馆 de huánjìng hěn ānjìng, 适 合 kàn shū.", "kafei 馆 de huanjing hen anjing 适 合 kan shu", "Không gian quán cà phê rất yên tĩnh, thích hợp để đọc sách.", "HSK 3"],
  ["房间被打扫得一尘不染，非常 干净。", "房 jiān bèi dǎsǎo de yī 尘 bù 染, 非 常 gānjìng.", "房 jian bei dasao de yi 尘 bu 染 非 常 ganjing", "Phòng được dọn dẹp sạch tinh tươm, vô cùng sạch sẽ.", "HSK 3"],
  ["节日期间的街道上人山人海，十分 热闹。", "jiérì 期 jiān de jiēdào shàng rén 山 rén 海, shífēn rè nao.", "jieri 期 jian de jiedao shang ren 山 ren 海 shifen re nao", "Đường phố trong dịp lễ hội đông nghịt người, vô cùng náo nhiệt.", "HSK 3"],
  ["图书馆里请保持 安静，不要大声说话。", "túshūguǎn lǐ qǐng bǎo chí ānjìng, bù 要 dà 声 shuō 话.", "tushuguan li qing bao chi anjing bu 要 da 声 shuo 话", "Trong thư viện xin giữ yên tĩnh, đừng nói chuyện lớn tiếng.", "HSK 3"],
  ["晚上出门要注意自己的人身 安全。", "wǎnshang chūmén 要 zhù yì zìjǐ de rén shēn ānquán.", "wanshang chumen 要 zhu yi ziji de ren shen anquan", "Ra đường buổi tối phải chú ý an toàn tính mạng của bản thân.", "HSK 3"],
  ["别去那个偏 僻的地方，太 危险 了。", "bié qù nà gè 偏 僻 de dìfang, tài wēixiǎn le.", "bie qu na ge 偏 僻 de difang tai weixian le", "Đừng đến chỗ hẻo lánh đó, nguy hiểm lắm.", "HSK 3"],
  ["住在地铁站旁边出行非常 方便。", "zhù zài dìtiě 站 pángbiān chū xíng 非 常 fāngbiàn.", "zhu zai ditie 站 pangbian chu xing 非 常 fangbian", "Sống cạnh ga tàu điện ngầm đi lại vô cùng thuận tiện.", "HSK 3"],
  ["这件事处理起来有点 麻烦。", "zhè jiàn 事 chǔlǐ qǐlái yǒu diǎn máfan.", "zhe jian 事 chuli qilai you dian mafan", "Sự việc này xử lý hơi phiền phức một chút.", "HSK 3"],
  ["祝你的求职面试一切 顺利。", "祝 nǐ de 求 职 miàn shì yī 切 shùn lì.", "祝 ni de 求 职 mian shi yi 切 shun li", "Chúc buổi phỏng vấn xin việc của cậu mọi sự thuận lợi.", "HSK 3"],
  ["人生总会遇到各种各样的 困难。", "rén 生 总 huì yùdào gè zhǒng gè yàng de kùnnan.", "ren 生 总 hui yudao ge zhong ge yang de kunnan", "Cuộc đời kiểu gì cũng sẽ gặp phải đủ thứ khó khăn.", "HSK 3"],
  ["大家齐心协力把问题 解决 了。", "dàjiā 齐 xīn 协 lì bǎ wèntí jiějué le.", "dajia 齐 xin 协 li ba wenti jiejue le", "Mọi người đồng sức đồng lòng giải quyết xong vấn đề rồi.", "HSK 3"],
  ["经过不懈努力，实验终于取得了 成功。", "jīngguò bù 懈 nǔlì, 实 验 zhōng yú 取 de le chénggōng.", "jingguo bu 懈 nuli 实 验 zhong yu 取 de le chenggong", "Trải qua sự nỗ lực không ngừng, thí nghiệm cuối cùng đã thu được thành công.", "HSK 3"],
  ["失败 是成功之母，不要灰心。", "shībài shì chénggōng zhī 母, bù 要 灰 xīn.", "shibai shi chenggong zhi 母 bu 要 灰 xin", "Thất bại là mẹ thành công, đừng nản lòng.", "HSK 3"],
  ["失败并不可怕，可怕的是不能从中吸取 经验。", "shībài 并 bù kě pà, kě pà de shì bùnéng cóng 中 吸 取 jīngyàn.", "shibai 并 bu ke pa ke pa de shi buneng cong 中 吸 取 jingyan", "Thất bại không đáng sợ, đáng sợ là không thể rút ra kinh nghiệm từ đó.", "HSK 3"],
  ["我们要记住这次深刻的 教训。", "wǒmen 要 jìzhù zhè cì 深 刻 de jiào xùn.", "women 要 jizhu zhe ci 深 刻 de jiao xun", "Chúng ta phải ghi nhớ bài học sâu sắc lần này.", "HSK 3"],
  ["遇到好的 机会 一定要紧紧抓住。", "yùdào hǎo de jīhuì yídìng yàojǐn 紧 抓 zhù.", "yudao hao de jihui yiding yaojin 紧 抓 zhu", "Gặp được cơ hội tốt nhất định phải nắm bắt thật chặt.", "HSK 3"],
  ["人生面临着许多重要的 选择。", "rén 生 面 临 zhe 许 duō zhòngyào de xuǎnzé.", "ren 生 面 临 zhe 许 duo zhongyao de xuanze", "Cuộc đời đối mặt với rất nhiều lựa chọn quan trọng.", "HSK 3"],
  ["这个方案已经敲定了，不能再更改 决定。", "zhè gè fāng 案 yǐjīng 敲 定 le, bùnéng zài gèng 改 juédìng.", "zhe ge fang 案 yijing 敲 定 le buneng zai geng 改 jueding", "Phương án này đã chốt rồi, không thể thay đổi quyết định nữa.", "HSK 3"],
  ["大家对这个计划有什么不同的 意见 吗？", "dàjiā duì zhè gè jìhuà yǒu shénme bùtóng de yìjiàn ma?", "dajia dui zhe ge jihua you shenme butong de yijian ma", "Mọi người có ý kiến gì khác về kế hoạch này không?", "HSK 3"],
  ["老师给我提出了一些很好的 建议。", "lǎoshī gěi wǒ tí chū le yìxiē hěn hǎo de jiànyì.", "laoshi gei wo ti chu le yixie hen hao de jianyi", "Giáo viên đưa ra cho tôi một số lời khuyên rất hay.", "HSK 3"],
  ["关于这件事，你有什么独特的 看法 吗？", "guānyú zhè jiàn 事, nǐ yǒu shénme 独 特 de kànfǎ ma?", "guanyu zhe jian 事 ni you shenme 独 特 de kanfa ma", "Về việc này, cậu có quan điểm độc đáo nào không?", "HSK 3"],
  ["学习一门新语言，端正的 态度 很关键。", "xuéxí yī mén xīn 语 言, 端 zhèng de tài dù hěn guān 键.", "xuexi yi men xin 语 言 端 zheng de tai du hen guan 键", "Học một ngôn ngữ mới, thái độ đúng đắn là rất then chốt.", "HSK 3"],
  ["培养广泛的 兴趣 有助于个人成长。", "péiyǎng 广 泛 de xìngqù yǒu 助 于 gè rén chéngzhǎng.", "peiyang 广 泛 de xingqu you 助 于 ge ren chengzhang", "Nuôi dưỡng sở thích rộng rãi có ích cho sự phát triển cá nhân.", "HSK 3"],
  ["我的业余 爱好 是看书和听音乐。", "wǒ de 业 余 àihào shì kàn shū hé tīng yīnyuè.", "wo de 业 余 aihao shi kan shu he ting yinyue", "Sở thích lúc rảnh rỗi của tôi là đọc sách và nghe nhạc.", "HSK 3"],
  ["早睡早起是一个良好的生活 习惯。", "zǎo shuì zǎo qǐ shì yí gè 良 hǎo de 生 huó xíguàn.", "zao shui zao qi shi yi ge 良 hao de 生 huo xiguan", "Ngủ sớm dậy sớm là một thói quen sinh hoạt tốt.", "HSK 3"],
  ["这道菜最大的 特点 是酸辣可口。", "zhè 道 cài zuì dà de tè diǎn shì 酸 辣 kě 口.", "zhe 道 cai zui da de te dian shi 酸 辣 ke 口", "Đặc điểm lớn nhất của món ăn này là chua cay vừa miệng.", "HSK 3"],
  ["这两个词的意思有什么 区别 呢？", "zhè liǎng gè cí de yìsi yǒu shénme qū bié ne?", "zhe liang ge ci de yisi you shenme qu bie ne", "Ý nghĩa của hai từ này có sự khác biệt gì vậy?", "HSK 3"],
  ["他们的爱好和性格有很多 相同 の地方。", "tā 们 de àihào hé xìnggé yǒu hěn duō xiāng tóng の dìfang.", "ta 们 de aihao he xingge you hen duo xiang tong の difang", "Sở thích và tính cách của họ có rất nhiều điểm giống nhau.", "HSK 3"],
  ["每个人的审美观点都有所 不同。", "每 gè rén de 审 美 观 diǎn dōu yǒu 所 bùtóng.", "每 ge ren de 审 美 观 dian dou you 所 butong", "Quan điểm thẩm mỹ của mỗi người đều có sự khác nhau nhất định.", "HSK 3"],
  ["记住，健康永远是第一位最 重要 的事。", "jìzhù, jiànkāng 永 yuǎn shì 第 yī wèi zuì zhòngyào de 事.", "jizhu jiankang 永 yuan shi 第 yi wei zui zhongyao de 事", "Hãy nhớ rằng, sức khỏe mãi mãi là điều quan trọng hàng đầu.", "HSK 3"],
  ["我们公司 主要 经营电子产品。", "wǒmen gōngsī zhǔyào 经 营 电 子 产 品.", "women gongsi zhuyao 经 营 电 子 产 品", "Công ty chúng tôi chủ yếu kinh doanh sản phẩm điện tử.", "HSK 3"],
  ["一般 情况下，我不接受晚上加班。", "yìbān qíngkuàng xià, wǒ bù jiē shòu wǎnshang jiā bān.", "yiban qingkuang xia wo bu jie shou wanshang jia ban", "Trong trường hợp thông thường, tôi không nhận tăng ca buổi tối.", "HSK 3"],
  ["今天的晚霞看起来 特别 美丽。", "jīntiān de wǎn 霞 kàn qǐ lái tèbié 美 丽.", "jintian de wan 霞 kan qi lai tebie 美 丽", "Ánh chiều tà hôm nay trông đặc biệt đẹp.", "HSK 3"],
  ["我喜欢各种水果，尤其是西瓜。", "wǒ xǐhuan gèzhǒng shuǐ guǒ, yóu qí shì xī 瓜.", "wo xihuan gezhong shui guo you qi shi xi 瓜", "Tôi thích các loại hoa quả, nhất là dưa hấu.", "HSK 3"],
  ["周末我 经常 去图书馆看书。", "zhōu 末 wǒ jīngcháng qù túshūguǎn kàn shū.", "zhou 末 wo jingchang qu tushuguan kan shu", "Cuối tuần tôi thường xuyên đến thư viện đọc sách.", "HSK 3"],
  ["他 常常 帮助班里有困难的同学。", "tā cháng cháng bāngzhù bān lǐ yǒu kùnnan de tóngxué.", "ta chang chang bangzhu ban li you kunnan de tongxue", "Cậu ấy thường hay giúp đỡ các bạn có hoàn cảnh khó khăn trong lớp.", "HSK 3"],
  ["有时候压力大的时候，我会去跑步发泄。", "yǒu shí hou 压 lì dà de shíhou, wǒ huì qù pǎobù fā 泄.", "you shi hou 压 li da de shihou wo hui qu paobu fa 泄", "Có lúc áp lực lớn, tôi sẽ đi chạy bộ để giải tỏa.", "HSK 3"],
  ["他平时很忙，偶尔周末会陪家人去郊游。", "tā 平 时 hěn 忙, ǒu'ěr zhōu 末 huì 陪 jiā rén qù 郊 yóu.", "ta 平 时 hen 忙 ouer zhou 末 hui 陪 jia ren qu 郊 you", "Anh ấy ngày thường rất bận, thỉnh thoảng cuối tuần sẽ cùng người nhà đi dã ngoại.", "HSK 3"],
  ["妈妈 总是 担心我吃不饱穿不暖。", "māma zǒng shì dānxīn wǒ chī bù bǎo chuān bù 暖.", "mama zong shi danxin wo chi bu bao chuan bu 暖", "Mẹ lúc nào cũng lo lắng tôi ăn không no mặc không ấm.", "HSK 3"],
  ["外面 一直 在下雨，没有停过。", "wàimiàn yìzhí zài xiàyǔ, méi yǒu 停 guo.", "waimian yizhi zai xiayu mei you 停 guo", "Bên ngoài cứ mưa hoài không ngớt.", "HSK 3"],
  ["集合时间到了，大家 马上 出发吧。", "集 合 shíjiān dào le, dàjiā mǎshàng chūfā ba.", "集 合 shijian dao le dajia mashang chufa ba", "Đến giờ tập trung rồi, mọi người xuất phát ngay thôi.", "HSK 3"],
  ["听到命令后，士兵们 立刻 行动起来。", "tīng dào mìng 令 后, 士 兵 们 lì kè xíng dòng qǐlái.", "ting dao ming 令 后 士 兵 们 li ke xing dong qilai", "Nghe thấy mệnh lệnh, các binh sĩ lập tức hành động.", "HSK 3"],
  ["快迟到了，你 赶快 把鞋穿上。", "kuài chídào le, nǐ gǎn kuài bǎ xié chuān shàng.", "kuai chidao le ni gan kuai ba xie chuan shang", "Sắp muộn rồi, cậu mau mang giày vào đi.", "HSK 3"],
  ["天快黑了，我们 赶紧 往回走吧。", "tiān kuài 黑 le, wǒmen gǎn jǐn wǎng huí zǒu ba.", "tian kuai 黑 le women gan jin wang hui zou ba", "Trời sắp tối rồi, chúng ta mau chóng quay về đi.", "HSK 3"],
  ["经过无数次的试验，他们 终于 成功了。", "jīngguò wú 数 cì de shì 验, tā 们 zhōng yú chénggōng le.", "jingguo wu 数 ci de shi 验 ta 们 zhong yu chenggong le", "Trải qua vô số lần thí nghiệm, cuối cùng họ cũng thành công.", "HSK 3"],
  ["这件事你 到底 是怎么想的？", "zhè jiàn 事 nǐ dàodǐ shì zěnme xiǎng de?", "zhe jian 事 ni daodi shi zenme xiang de", "Việc này rốt cuộc cậu nghĩ thế nào?", "HSK 3"],
  ["其实他并没有恶意，只是说话直率。", "qíshí tā 并 méi yǒu 恶 yì, 只 shì shuō 话 直 率.", "qishi ta 并 mei you 恶 yi 只 shi shuo 话 直 率", "Thực ra anh ấy không có ý ác gì, chỉ là ăn nói thẳng thắn thôi.", "HSK 3"],
  ["天气预报说今天有雨，下午 果然 下雨了。", "tiānqì 预 报 shuō jīntiān yǒu 雨, xiàwǔ guǒrán xiàyǔ le.", "tianqi 预 报 shuo jintian you 雨 xiawu guoran xiayu le", "Dự báo thời tiết nói hôm nay có mưa, buổi chiều quả nhiên mưa rồi.", "HSK 3"],
  ["他用了不到一个月的时间，竟然 把汉语考过了。", "tā yòng le bù dào yí gè yuè de shíjiān, jìng rán bǎ hànyǔ kǎo guo le.", "ta yong le bu dao yi ge yue de shijian jing ran ba hanyu kao guo le", "Anh ấy dùng chưa đầy một tháng mà lại có thể thi đậu tiếng Trung.", "HSK 3"],
  ["他忙得连饭都顾不上吃，甚至 连水都没喝。", "tā 忙 de 连 fàn dōu 顾 bù shàng chī, shèn zhì 连 shuǐ dōu méi hē.", "ta 忙 de 连 fan dou 顾 bu shang chi shen zhi 连 shui dou mei he", "Anh ấy bận đến mức cơm còn không kịp ăn, thậm chí nước cũng chưa uống.", "HSK 3"],
];

/**
 * Tổng hợp các kho dữ liệu theo Độ Khó
 */
export const normalDifficultyPool: VocabularyEntry[] = [
  ...collocationsVocabulary,
  ...fixedExpressionsVocabulary,
];

export const hardDifficultyPool: VocabularyEntry[] = [
  ...sentencePatternsVocabulary,
  ...contextSentencesVocabulary,
];

export interface DifficultyPack {
  id: string;
  name: string;
  subtitle: string;
  bpm: string;
  tag: string;
  levelBadge: string;
  color: string;
  description: string;
  vocabulary: VocabularyEntry[];
}

export const normalPacks: DifficultyPack[] = [
  {
    id: 'normal-collocations',
    name: '搭配风暴',
    subtitle: 'Collocation Flow',
    bpm: '145',
    tag: 'Collocations',
    levelBadge: 'Bình thường',
    color: '#0ea5e9',
    description: 'Kết hợp từ thường gặp: Động-Tân, Động-Bổ, Định-Trung tự nhiên chuẩn bản xứ (288 mục).',
    vocabulary: collocationsVocabulary,
  },
  {
    id: 'normal-fixed-expressions',
    name: '成语典故',
    subtitle: 'Idioms & Expressions',
    bpm: '160',
    tag: 'Fixed Expressions',
    levelBadge: 'Bình thường',
    color: '#8b5cf6',
    description: 'Thành ngữ 4 chữ & quán ngữ khẩu ngữ giao tiếp thông dụng (82 mục).',
    vocabulary: fixedExpressionsVocabulary,
  },
  {
    id: 'normal-all',
    name: '中级精选',
    subtitle: 'Master Collocations',
    bpm: '165',
    tag: 'Tổng hợp Bậc Trung',
    levelBadge: 'Bình thường',
    color: '#f59e0b',
    description: 'Trộn ngẫu nhiên toàn bộ 370 mục Collocations và Thành ngữ / Quán ngữ.',
    vocabulary: normalDifficultyPool,
  },
];

export const hardPacks: DifficultyPack[] = [
  {
    id: 'hard-patterns',
    name: '句式天梯',
    subtitle: 'Grammar Patterns',
    bpm: '175',
    tag: 'Sentence Patterns',
    levelBadge: 'Khó',
    color: '#ec4899',
    description: 'Mẫu câu liên từ & cấu trúc ngữ pháp phức (虽然...但是, 因为...所以, 越来越..., chính phản) (36 mẫu).',
    vocabulary: sentencePatternsVocabulary,
  },
  {
    id: 'hard-context',
    name: '情境对话',
    subtitle: 'Context Sentences',
    bpm: '180',
    tag: 'Context Sentences',
    levelBadge: 'Khó',
    color: '#ef4444',
    description: 'Câu ngắn ngữ cảnh thực tế: mua sắm, hỏi đường, đặt vé, đàm thoại hằng ngày (388 câu).',
    vocabulary: contextSentencesVocabulary,
  },
  {
    id: 'hard-all',
    name: '高级风暴',
    subtitle: 'Ultimate Sentences',
    bpm: '188',
    tag: 'Tổng hợp Bậc Khó',
    levelBadge: 'Thử thách',
    color: '#dc2626',
    description: 'Đại chiến câu nâng cao: thử thách tốc độ phản xạ với toàn bộ 424 mẫu câu & ngữ cảnh.',
    vocabulary: hardDifficultyPool,
  },
];
