import type { VocabularyEntry } from './hsk2-vocabulary';

export const hsk1Vocabulary: VocabularyEntry[] = [
['爱','ài','ai','yêu','HSK 1'],['八','bā','ba','số 8','HSK 1'],['爸爸','bàba','baba','bố','HSK 1'],['杯子','bēizi','beizi','cái cốc','HSK 1'],['北京','běijīng','beijing','bắc kinh','HSK 1'],['本','běn','ben','quyển','HSK 1'],['不','bù','bu','không','HSK 1'],['不客气','bú kèqi','bu keqi','không có gì','HSK 1'],['菜','cài','cai','món ăn/rau','HSK 1'],['茶','chá','cha','trà','HSK 1'],
['吃','chī','chi','ăn','HSK 1'],['出租车','chūzūchē','chuzuche','taxi','HSK 1'],['打电话','dǎ diànhuà','da dianhua','gọi điện thoại','HSK 1'],['大','dà','da','to/lớn','HSK 1'],['的','de','de','của','HSK 1'],['点','diǎn','dian','giờ','HSK 1'],['电脑','diànnǎo','diannao','máy tính','HSK 1'],['电视','diànshì','dianshi','tivi','HSK 1'],['电影','diànyǐng','dianying','phim','HSK 1'],['东西','dōngxi','dongxi','đồ vật','HSK 1'],
['都','dōu','dou','đều','HSK 1'],['读','dú','du','đọc','HSK 1'],['对不起','duìbuqǐ','duibuqi','xin lỗi','HSK 1'],['多','duō','duo','nhiều','HSK 1'],['多少','duōshao','duoshao','bao nhiêu','HSK 1'],['儿子','érzi','erzi','con trai','HSK 1'],['二','èr','er','số 2','HSK 1'],['饭','fàn','fan','cơm','HSK 1'],['飞机','fēijī','feiji','máy bay','HSK 1'],['分钟','fēnzhōng','fenzhong','phút','HSK 1'],
['高','gāo','gao','cao','HSK 1'],['高兴','gāoxìng','gaoxing','vui vẻ','HSK 1'],['个','gè','ge','cái/chiếc','HSK 1'],['工作','gōngzuò','gongzuo','công việc','HSK 1'],['狗','gǒu','gou','con chó','HSK 1'],['汉语','hànyǔ','hanyu','tiếng Trung','HSK 1'],['好','hǎo','hao','tốt/ngon','HSK 1'],['号','hào','hao','số/ngày','HSK 1'],['喝','hē','he','uống','HSK 1'],['和','hé','he','và','HSK 1'],
['很','hěn','hen','rất','HSK 1'],['后面','hòumiàn','houmian','phía sau','HSK 1'],['回','huí','hui','về','HSK 1'],['会','huì','hui','biết','HSK 1'],['几','jǐ','ji','mấy','HSK 1'],['家','jiā','jia','nhà/gia đình','HSK 1'],['叫','jiào','jiao','gọi là','HSK 1'],['今天','jīntiān','jintian','hôm nay','HSK 1'],['九','jiǔ','jiu','số 9','HSK 1'],['开','kāi','kai','mở/lái','HSK 1'],
['看','kàn','kan','nhìn/xem','HSK 1'],['看见','kànjiàn','kanjian','nhìn thấy','HSK 1'],['块','kuài','kuai','đồng','HSK 1'],['来','lái','lai','đến','HSK 1'],['老师','lǎoshī','laoshi','giáo viên','HSK 1'],['了','le','le','rồi','HSK 1'],['冷','lěng','leng','lạnh','HSK 1'],['里','lǐ','li','trong','HSK 1'],['六','liù','liu','số 6','HSK 1'],['妈妈','māma','mama','mẹ','HSK 1'],
['吗','ma','ma','không?','HSK 1'],['买','mǎi','mai','mua','HSK 1'],['猫','māo','mao','con mèo','HSK 1'],['没','méi','mei','không','HSK 1'],['没关系','méi guānxi','mei guanxi','không sao','HSK 1'],['米饭','mǐfàn','mifan','cơm trắng','HSK 1'],['名字','míngzi','mingzi','tên','HSK 1'],['明天','míngtiān','mingtian','ngày mai','HSK 1'],['哪','nǎ','na','nào','HSK 1'],['哪儿','nǎr','nar','ở đâu','HSK 1'],
['那','nà','na','đó/kia','HSK 1'],['呢','ne','ne','nhé/thế còn','HSK 1'],['能','néng','neng','có thể','HSK 1'],['你','nǐ','ni','bạn','HSK 1'],['年','nián','nian','năm','HSK 1'],['女儿','nǚ’ér','nuer','con gái','HSK 1'],['朋友','péngyou','pengyou','bạn bè','HSK 1'],['漂亮','piàoliang','piaoliang','đẹp','HSK 1'],['苹果','píngguǒ','pingguo','quả táo','HSK 1'],['七','qī','qi','số 7','HSK 1'],
['钱','qián','qian','tiền','HSK 1'],['前面','qiánmiàn','qianmian','phía trước','HSK 1'],['请','qǐng','qing','mời','HSK 1'],['去','qù','qu','đi','HSK 1'],['热','rè','re','nóng','HSK 1'],['人','rén','ren','người','HSK 1'],['认识','rènshi','renshi','quen biết','HSK 1'],['三','sān','san','số 3','HSK 1'],['商店','shāngdiàn','shangdian','cửa hàng','HSK 1'],['上','shàng','shang','trên','HSK 1'],
['上午','shàngwǔ','shangwu','buổi sáng','HSK 1'],['少','shǎo','shao','ít','HSK 1'],['谁','shéi','shei','ai','HSK 1'],['什么','shénme','shenme','cái gì','HSK 1'],['十','shí','shi','số 10','HSK 1'],['时候','shíhou','shihou','lúc/khi','HSK 1'],['是','shì','shi','là','HSK 1'],['书','shū','shu','sách','HSK 1'],['水','shuǐ','shui','nước','HSK 1'],['睡觉','shuìjiào','shuijiao','ngủ','HSK 1'],
['说','shuō','shuo','nói','HSK 1'],['四','sì','si','số 4','HSK 1'],['岁','suì','sui','tuổi','HSK 1'],['他','tā','ta','anh ấy','HSK 1'],['她','tā','ta','cô ấy','HSK 1'],['太','tài','tai','quá','HSK 1'],['天气','tiānqì','tianqi','thời tiết','HSK 1'],['听','tīng','ting','nghe','HSK 1'],['同学','tóngxué','tongxue','bạn học','HSK 1'],['喂','wèi','wei','alo','HSK 1'],
['我','wǒ','wo','tôi','HSK 1'],['我们','wǒmen','women','chúng tôi','HSK 1'],['五','wǔ','wu','số 5','HSK 1'],['喜欢','xǐhuan','xihuan','thích','HSK 1'],['下','xià','xia','dưới','HSK 1'],['下午','xiàwǔ','xiawu','buổi chiều','HSK 1'],['下雨','xiàyǔ','xiayu','mưa','HSK 1'],['先生','xiānsheng','xiansheng','ông/ngài','HSK 1'],['现在','xiànzài','xianzai','bây giờ','HSK 1'],['想','xiǎng','xiang','muốn/nhớ','HSK 1'],
['小','xiǎo','xiao','nhỏ','HSK 1'],['小姐','xiǎojiě','xiaojie','cô gái','HSK 1'],['写','xiě','xie','viết','HSK 1'],['谢谢','xièxie','xiexie','cảm ơn','HSK 1'],['星期','xīngqī','xingqi','tuần','HSK 1'],['学习','xuéxí','xuexi','học tập','HSK 1'],['学校','xuéxiào','xuexiao','trường học','HSK 1'],['一','yī','yi','số 1','HSK 1'],['衣服','yīfu','yifu','quần áo','HSK 1'],['医生','yīshēng','yisheng','bác sĩ','HSK 1'],
['医院','yīyuàn','yiyuan','bệnh viện','HSK 1'],['椅子','yǐzi','yizi','cái ghế','HSK 1'],['有','yǒu','you','có','HSK 1'],['月','yuè','yue','tháng','HSK 1'],['在','zài','zai','ở/tại','HSK 1'],['再见','zàijiàn','zaijian','tạm biệt','HSK 1'],['怎么','zěnme','zenme','sao/làm sao','HSK 1'],['怎么样','zěnmeyàng','zenmeyang','thế nào','HSK 1'],['这','zhè','zhe','đây/này','HSK 1'],['中国','zhōngguó','zhongguo','Trung Quốc','HSK 1'],
['中午','zhōngwǔ','zhongwu','buổi trưa','HSK 1'],['住','zhù','zhu','ở/cư trú','HSK 1'],['桌子','zhuōzi','zhuozi','cái bàn','HSK 1'],['字','zì','zi','chữ','HSK 1'],['昨天','zuótiān','zuotian','hôm qua','HSK 1'],['做','zuò','zuo','làm','HSK 1'],['坐','zuò','zuo','ngồi','HSK 1'],['看书','kàn shū','kan shu','đọc sách','HSK 1'],['听音乐','tīng yīnyuè','ting yinyue','nghe nhạc','HSK 1'],['学汉语','xué hànyǔ','xue hanyu','học tiếng Trung','HSK 1'],
['三年','sān nián','san nian','ba năm','HSK 1'],['六个月','liù gè yuè','liu ge yue','sáu tháng','HSK 1'],['五分钟','wǔ fēn zhōng','wu fen zhong','năm phút','HSK 1'],['十点钟','shí diǎn zhōng','shi dian zhong','mười giờ đúng','HSK 1'],['今年','jīn nián','jin nian','năm nay','HSK 1'],['中国菜','zhōngguó cài','zhongguo cai','món ăn Trung Quốc','HSK 1'],['一个','yí gè','yi ge','một cái / một người','HSK 1'],['一下儿','yí xiàr','yi xiar','một lát / thử chút','HSK 1'],
];

