export type VocabularyEntry = readonly [
  hanzi: string,
  pinyin: string,
  typing: string,
  meaning: string,
  level: 'HSK 1' | 'HSK 2' | 'HSK 3',
];

export const hsk2Vocabulary: VocabularyEntry[] = [
  ['不好意思', 'bù hǎo yì si', 'bu hao yi si', 'ngại quá, xin lỗi', 'HSK 2'],
  ['新年', 'xīnnián', 'xinnian', 'năm mới', 'HSK 2'],
  ['蛋糕', 'dàngāo', 'dangao', 'bánh kem, bánh ngọt', 'HSK 2'],
  ['床', 'chuáng', 'chuang', 'giường', 'HSK 2'],
  ['鱼', 'yú', 'yu', 'cá', 'HSK 2'],
  ['肉', 'ròu', 'rou', 'thịt', 'HSK 2'],
  ['手', 'shǒu', 'shou', 'tay', 'HSK 2'],
  ['头', 'tóu', 'tou', 'đầu', 'HSK 2'],
  ['身体', 'shēntǐ', 'shenti', 'cơ thể, sức khỏe', 'HSK 2'],
  ['裤子', 'kùzi', 'kuzi', 'quần', 'HSK 2'],
  ['书包', 'shūbāo', 'shubao', 'cặp sách', 'HSK 2'],
  ['本子', 'běnzi', 'benzi', 'quyển vở', 'HSK 2'],
  ['笔', 'bǐ', 'bi', 'bút, nét chữ', 'HSK 2'],
  ['词', 'cí', 'ci', 'từ', 'HSK 2'],
  ['题', 'tí', 'ti', 'câu hỏi, đề bài', 'HSK 2'],
  ['门', 'mén', 'men', 'cửa', 'HSK 2'],
  ['爷爷', 'yéye', 'yeye', 'ông nội', 'HSK 2'],
  ['奶奶', 'nǎinai', 'nainai', 'bà nội', 'HSK 2'],
  ['小孩儿', 'xiǎoháir', 'xiaohair', 'trẻ nhỏ, con cái', 'HSK 2'],
  ['女孩儿', 'nǚháir', 'nvhair', 'bé gái, thiếu nữ', 'HSK 2'],
  ['男孩儿', 'nánháir', 'nanhair', 'bé trai, cậu con trai', 'HSK 2'],
  ['妻子', 'qīzi', 'qizi', 'vợ', 'HSK 2'],
  ['丈夫', 'zhàngfu', 'zhangfu', 'chồng', 'HSK 2'],
  ['礼物', 'lǐwù', 'liwu', 'món quà', 'HSK 2'],
  ['手表', 'shǒubiǎo', 'shoubiao', 'đồng hồ đeo tay', 'HSK 2'],
  ['花', 'huā', 'hua', 'hoa; tiêu, tốn', 'HSK 2'],
  ['咖啡', 'kāfēi', 'kafei', 'cà phê', 'HSK 2'],
  ['奶茶', 'nǎichá', 'naicha', 'trà sữa', 'HSK 2'],
  ['北京烤鸭', 'běijīng kǎoyā', 'beijing kaoya', 'vịt quay Bắc Kinh', 'HSK 2'],
  ['票', 'piào', 'piao', 'vé', 'HSK 2'],
  ['商场', 'shāngchǎng', 'shangchang', 'trung tâm thương mại', 'HSK 2'],
  ['药店', 'yàodiàn', 'yaodian', 'hiệu thuốc', 'HSK 2'],
  ['酒店', 'jiǔdiàn', 'jiudian', 'khách sạn', 'HSK 2'],
  ['车站', 'chēzhàn', 'chezhan', 'trạm xe, bến xe', 'HSK 2'],
  ['机场', 'jīchǎng', 'jichang', 'sân bay', 'HSK 2'],
  ['教室', 'jiàoshì', 'jiaoshi', 'phòng học, lớp học', 'HSK 2'],
  ['楼', 'lóu', 'lou', 'tòa nhà, tầng lầu', 'HSK 2'],
  ['房子', 'fángzi', 'fangzi', 'căn nhà, căn hộ', 'HSK 2'],
  ['北京大学', 'běijīng dàxué', 'beijing daxue', 'Đại học Bắc Kinh', 'HSK 2'],
  ['高中', 'gāozhōng', 'gaozhong', 'trường trung học phổ thông', 'HSK 2'],
  ['班', 'bān', 'ban', 'lớp học', 'HSK 2'],
  ['外国', 'wàiguó', 'waiguo', 'nước ngoài', 'HSK 2'],
  ['门口', 'ménkǒu', 'menkou', 'cửa ra vào, cổng', 'HSK 2'],
  ['外面', 'wàimiàn', 'waimian', 'bên ngoài', 'HSK 2'],
  ['外边', 'wàibian', 'waibian', 'bên ngoài', 'HSK 2'],
  ['里面', 'lǐmiàn', 'limian', 'bên trong', 'HSK 2'],
  ['里边', 'lǐbian', 'libian', 'bên trong', 'HSK 2'],
  ['上面', 'shàngmiàn', 'shangmian', 'phía trên, bề mặt', 'HSK 2'],
  ['前面', 'qiánmian', 'qianmian', 'phía trước', 'HSK 2'],
  ['左边', 'zuǒbian', 'zuobian', 'bên trái', 'HSK 2'],
  ['右边', 'yòubian', 'youbian', 'bên phải', 'HSK 2'],
  ['旁边', 'pángbiān', 'pangbian', 'bên cạnh', 'HSK 2'],
  ['路上', 'lùshang', 'lushang', 'trên đường', 'HSK 2'],
  ['路', 'lù', 'lu', 'con đường', 'HSK 2'],
  ['地铁', 'dìtiě', 'ditie', 'tàu điện ngầm', 'HSK 2'],
  ['公交车', 'gōngjiāochē', 'gongjiaoche', 'xe buýt', 'HSK 2'],
  ['机票', 'jīpiào', 'jipiao', 'vé máy bay', 'HSK 2'],
  ['门票', 'ménpiào', 'menpiao', 'vé vào cổng', 'HSK 2'],
  ['姓名', 'xìngmíng', 'xingming', 'họ tên', 'HSK 2'],
  ['网上', 'wǎngshàng', 'wangshang', 'trên mạng', 'HSK 2'],
  ['事情', 'shìqíng', 'shiqing', 'sự việc, chuyện', 'HSK 2'],
  ['意思', 'yìsi', 'yisi', 'ý, nghĩa', 'HSK 2'],
  ['爱情片', 'àiqíngpiàn', 'aiqingpian', 'phim tình cảm', 'HSK 2'],
  ['小时候', 'xiǎoshíhou', 'xiaoshihou', 'lúc nhỏ', 'HSK 2'],
  ['旅游', 'lǚyóu', 'lvyou', 'du lịch', 'HSK 2'],
  ['介绍', 'jièshào', 'jieshao', 'giới thiệu', 'HSK 2'],
  ['帮忙', 'bāngmáng', 'bangmang', 'giúp đỡ', 'HSK 2'],
  ['帮', 'bāng', 'bang', 'giúp', 'HSK 2'],
  ['给', 'gěi', 'gei', 'đưa, cho', 'HSK 2'],
  ['接', 'jiē', 'jie', 'đón', 'HSK 2'],
  ['送', 'sòng', 'song', 'đưa, tặng, tiễn', 'HSK 2'],
  ['拿', 'ná', 'na', 'lấy, cầm', 'HSK 2'],
  ['洗', 'xǐ', 'xi', 'rửa, gội, giặt', 'HSK 2'],
  ['等', 'děng', 'deng', 'đợi, chờ', 'HSK 2'],
  ['准备', 'zhǔnbèi', 'zhunbei', 'chuẩn bị', 'HSK 2'],
  ['教', 'jiāo', 'jiao', 'dạy', 'HSK 2'],
  ['告诉', 'gàosu', 'gaosu', 'nói cho biết, thông báo', 'HSK 2'],
  ['忘', 'wàng', 'wang', 'quên', 'HSK 2'],
  ['画', 'huà', 'hua', 'vẽ; bức tranh', 'HSK 2'],
  ['画画', 'huàhuà', 'huahua', 'vẽ tranh', 'HSK 2'],
  ['画笔', 'huàbǐ', 'huabi', 'bút màu, cọ vẽ', 'HSK 2'],
  ['过生日', 'guò shēngrì', 'guo shengri', 'đón sinh nhật', 'HSK 2'],
  ['过年', 'guònián', 'guonian', 'đón Tết', 'HSK 2'],
  ['上学', 'shàngxué', 'shangxue', 'đi học', 'HSK 2'],
  ['开学', 'kāixué', 'kaixue', 'khai giảng', 'HSK 2'],
  ['跑步', 'pǎobù', 'paobu', 'chạy bộ', 'HSK 2'],
  ['踢足球', 'tī zúqiú', 'ti zuqiu', 'đá bóng', 'HSK 2'],
  ['打篮球', 'dǎ lánqiú', 'da lanqiu', 'chơi bóng rổ', 'HSK 2'],
  ['篮球', 'lánqiú', 'lanqiu', 'bóng rổ', 'HSK 2'],
  ['足球', 'zúqiú', 'zuqiu', 'bóng đá', 'HSK 2'],
  ['球', 'qiú', 'qiu', 'bóng', 'HSK 2'],
  ['游泳', 'yóuyǒng', 'youyong', 'bơi lội', 'HSK 2'],
  ['跳舞', 'tiàowǔ', 'tiaowu', 'nhảy múa', 'HSK 2'],
  ['上网', 'shàngwǎng', 'shangwang', 'lên mạng', 'HSK 2'],
  ['走路', 'zǒulù', 'zoulu', 'đi bộ', 'HSK 2'],
  ['打车', 'dǎchē', 'dache', 'bắt taxi', 'HSK 2'],
  ['出国', 'chūguó', 'chuguo', 'đi nước ngoài', 'HSK 2'],
  ['出门', 'chūmén', 'chumen', 'ra khỏi nhà', 'HSK 2'],
  ['走', 'zǒu', 'zou', 'đi bộ', 'HSK 2'],
  ['跑', 'pǎo', 'pao', 'chạy', 'HSK 2'],
  ['游', 'yóu', 'you', 'bơi', 'HSK 2'],
  ['踢', 'tī', 'ti', 'đá', 'HSK 2'],
  ['笑', 'xiào', 'xiao', 'cười', 'HSK 2'],
  ['疼', 'téng', 'teng', 'đau', 'HSK 2'],
  ['动', 'dòng', 'dong', 'động, di chuyển', 'HSK 2'],
  ['试', 'shì', 'shi', 'thử', 'HSK 2'],
  ['懂', 'dǒng', 'dong', 'hiểu, biết', 'HSK 2'],
  ['打开', 'dǎkāi', 'dakai', 'mở', 'HSK 2'],
  ['打开礼物', 'dǎkāi lǐwù', 'dakai liwu', 'mở quà', 'HSK 2'],
  ['记得', 'jìde', 'jide', 'nhớ', 'HSK 2'],
  ['点', 'diǎn', 'dian', 'gọi món', 'HSK 2'],
  ['考', 'kǎo', 'kao', 'thi, kiểm tra', 'HSK 2'],
  ['考试', 'kǎoshì', 'kaoshi', 'kỳ thi, kiểm tra', 'HSK 2'],
  ['让', 'ràng', 'rang', 'bảo, khiến, cho phép', 'HSK 2'],
  ['开始', 'kāishǐ', 'kaishi', 'bắt đầu', 'HSK 2'],
  ['希望', 'xīwàng', 'xiwang', 'hy vọng', 'HSK 2'],
  ['可能', 'kěnéng', 'keneng', 'có lẽ, có thể', 'HSK 2'],
  ['过来', 'guòlái', 'guolai', 'đi đến đây', 'HSK 2'],
  ['过去', 'guòqù', 'guoqu', 'đi qua, quá khứ', 'HSK 2'],
  ['回来', 'huílái', 'huilai', 'quay lại đây', 'HSK 2'],
  ['回去', 'huíqù', 'huiqu', 'quay về', 'HSK 2'],
  ['进来', 'jìnlái', 'jinlai', 'vào đây', 'HSK 2'],
  ['进去', 'jìnqù', 'jinqu', 'đi vào', 'HSK 2'],
  ['出来', 'chūlái', 'chulai', 'đi ra đây', 'HSK 2'],
  ['出去', 'chūqù', 'chuqu', 'ra ngoài', 'HSK 2'],
  ['上来', 'shànglái', 'shanglai', 'lên đây', 'HSK 2'],
  ['上去', 'shàngqù', 'shangqu', 'đi lên', 'HSK 2'],
  ['下来', 'xiàlái', 'xialai', 'xuống đây', 'HSK 2'],
  ['下去', 'xiàqù', 'xiaqu', 'đi xuống', 'HSK 2'],
  ['起来', 'qǐlái', 'qilai', 'đứng dậy, bắt đầu', 'HSK 2'],
  ['错', 'cuò', 'cuo', 'sai', 'HSK 2'],
  ['不错', 'búcuò', 'bu cuo', 'không tệ, rất tốt', 'HSK 2'],
  ['舒服', 'shūfu', 'shufu', 'thoải mái, dễ chịu', 'HSK 2'],
  ['很舒服', 'hěn shūfu', 'hen shufu', 'rất thoải mái', 'HSK 2'],
  ['累', 'lèi', 'lei', 'mệt', 'HSK 2'],
  ['远', 'yuǎn', 'yuan', 'xa', 'HSK 2'],
  ['近', 'jìn', 'jin', 'gần', 'HSK 2'],
  ['慢', 'màn', 'man', 'chậm', 'HSK 2'],
  ['快', 'kuài', 'kuai', 'nhanh', 'HSK 2'],
  ['高', 'gāo', 'gao', 'cao', 'HSK 2'],
  ['个子', 'gèzi', 'gezi', 'dáng người, chiều cao', 'HSK 2'],
  ['晴', 'qíng', 'qing', 'nắng, trời quang', 'HSK 2'],
  ['阴', 'yīn', 'yin', 'âm u, nhiều mây', 'HSK 2'],
  ['快乐', 'kuàilè', 'kuaile', 'vui vẻ, hạnh phúc', 'HSK 2'],
  ['有意思', 'yǒu yìsi', 'you yisi', 'thú vị, có ý nghĩa', 'HSK 2'],
  ['没意思', 'méiyìsi', 'mei yisi', 'nhạt nhẽo, nhàm chán', 'HSK 2'],
  ['白色', 'báisè', 'baise', 'màu trắng', 'HSK 2'],
  ['红色', 'hóngsè', 'hongse', 'màu đỏ', 'HSK 2'],
  ['绿色', 'lǜsè', 'lvse', 'màu xanh lá', 'HSK 2'],
  ['黑色', 'hēisè', 'heise', 'màu đen', 'HSK 2'],
  ['颜色', 'yánsè', 'yanse', 'màu sắc', 'HSK 2'],
  ['长', 'cháng', 'chang', 'dài', 'HSK 2'],
  ['坏', 'huài', 'huai', 'xấu, hỏng', 'HSK 2'],
  ['就', 'jiù', 'jiu', 'chính là, liền', 'HSK 2'],
  ['正', 'zhèng', 'zheng', 'đang diễn ra', 'HSK 2'],
  ['已经', 'yǐjīng', 'yijing', 'đã', 'HSK 2'],
  ['经常', 'jīngcháng', 'jingchang', 'thường xuyên', 'HSK 2'],
  ['有时', 'yǒushí', 'youshi', 'có lúc, thỉnh thoảng', 'HSK 2'],
  ['最', 'zuì', 'zui', 'nhất', 'HSK 2'],
  ['更', 'gèng', 'geng', 'hơn, càng', 'HSK 2'],
  ['别', 'bié', 'bie', 'đừng', 'HSK 2'],
  ['还是', 'háishì', 'haishi', 'hay là, vẫn là', 'HSK 2'],
  ['快要', 'kuàiyào', 'kuaiyao', 'sắp', 'HSK 2'],
  ['这么', 'zhème', 'zheme', 'như thế này', 'HSK 2'],
  ['那么', 'nàme', 'name', 'thế thì, như thế kia', 'HSK 2'],
  ['这样', 'zhèyàng', 'zheyang', 'như thế này', 'HSK 2'],
  ['那样', 'nàyàng', 'nayang', 'như thế kia', 'HSK 2'],
  ['自己', 'zìjǐ', 'ziji', 'tự mình', 'HSK 2'],
  ['为什么', 'wèishénme', 'weishenme', 'tại sao', 'HSK 2'],
  ['从', 'cóng', 'cong', 'từ, bắt đầu từ', 'HSK 2'],
  ['往', 'wǎng', 'wang', 'hướng về', 'HSK 2'],
  ['离', 'lí', 'li', 'cách', 'HSK 2'],
  ['跟', 'gēn', 'gen', 'cùng, với', 'HSK 2'],
  ['比', 'bǐ', 'bi', 'so với, hơn', 'HSK 2'],
  ['但', 'dàn', 'dan', 'nhưng', 'HSK 2'],
  ['但是', 'dànshì', 'danshi', 'nhưng mà', 'HSK 2'],
  ['虽然', 'suīrán', 'suiran', 'mặc dù', 'HSK 2'],
  ['因为', 'yīnwèi', 'yinwei', 'bởi vì', 'HSK 2'],
  ['所以', 'suǒyǐ', 'suoyi', 'cho nên, vì thế', 'HSK 2'],
  ['着', 'zhe', 'zhe', 'trợ từ chỉ trạng thái tiếp diễn', 'HSK 2'],
  ['过', 'guo', 'guo', 'trợ từ chỉ kinh nghiệm đã qua', 'HSK 2'],
  ['地', 'de', 'de', 'trợ từ kết cấu trước động từ', 'HSK 2'],
  ['得', 'de', 'de', 'trợ từ kết cấu sau động từ', 'HSK 2'],
  ['吧', 'ba', 'ba', 'trợ từ ngữ khí đề xuất', 'HSK 2'],
  ['啊', 'a', 'a', 'trợ từ ngữ khí cuối câu', 'HSK 2'],
  ['万', 'wàn', 'wan', 'vạn, mười nghìn', 'HSK 2'],
  ['次', 'cì', 'ci', 'lần', 'HSK 2'],
  ['条', 'tiáo', 'tiao', 'lượng từ cho vật dài, hẹp', 'HSK 2'],
  ['张', 'zhāng', 'zhang', 'lượng từ cho vật phẳng', 'HSK 2'],
  ['辆', 'liàng', 'liang', 'lượng từ cho xe cộ', 'HSK 2'],
  ['间', 'jiān', 'jian', 'lượng từ cho phòng', 'HSK 2'],
  ['名', 'míng', 'ming', 'lượng từ cho người', 'HSK 2'],
  ['位', 'wèi', 'wei', 'lượng từ tôn kính cho người', 'HSK 2'],
  ['件', 'jiàn', 'jian', 'lượng từ cho quần áo, sự việc', 'HSK 2'],
  ['双', 'shuāng', 'shuang', 'đôi, cặp', 'HSK 2'],
  ['小时', 'xiǎoshí', 'xiaoshi', 'giờ, tiếng đồng hồ', 'HSK 2'],
  ['周', 'zhōu', 'zhou', 'tuần', 'HSK 2'],
  ['洗手间', 'xǐshǒujiān', 'xishoujian', 'nhà vệ sinh', 'HSK 2'],
  ['生日', 'shēngrì', 'shengri', 'sinh nhật', 'HSK 2'],
  ['包', 'bāo', 'bao', 'túi, bao', 'HSK 2'],
];
