export type VocabularyEntry = readonly [
  hanzi: string,
  pinyin: string,
  typing: string,
  meaning: string,
  level: 'HSK 1' | 'HSK 2' | 'HSK 3' | 'HSK 4' | 'HSK 5' | 'HSK 6' | 'HSK 7' | 'HSK 8' | 'HSK 9',
];

export const hsk2Vocabulary: VocabularyEntry[] = [
  ['不好意思', 'bù hǎo yì si', 'bu hao yi si', 'ngại quá, xin lỗi', 'HSK 2'],
  ['新年', 'xīnnián', 'xinnian', 'năm mới', 'HSK 2'],
  ['蛋糕', 'dàngāo', 'dangao', 'bánh kem, bánh ngọt', 'HSK 2'],
  ['床', 'chuáng', 'chuang', 'giường', 'HSK 2'],
  ['鱼', 'yú', 'yu', 'cá', 'HSK 2'],
  ['肉', 'ròu', 'rou', 'thịt', 'HSK 2'],
  ['手', 'shǒu', 'shou', 'tay', 'HSK 2'],
  ['头', 'tóu', 'tou', 'đầu', 'HSK 2'],
  ['身体', 'shēntǐ', 'shenti', 'cơ thể, sức khỏe', 'HSK 2'],
  ['裤子', 'kùzi', 'kuzi', 'quần', 'HSK 2'],
  ['书包', 'shūbāo', 'shubao', 'cặp sách', 'HSK 2'],
  ['本子', 'běnzi', 'benzi', 'quyển vở', 'HSK 2'],
  ['笔', 'bǐ', 'bi', 'bút, nét chữ', 'HSK 2'],
  ['词', 'cí', 'ci', 'từ', 'HSK 2'],
  ['题', 'tí', 'ti', 'câu hỏi, đề bài', 'HSK 2'],
  ['门', 'mén', 'men', 'cửa', 'HSK 2'],
  ['爷爷', 'yéye', 'yeye', 'ông nội', 'HSK 2'],
  ['奶奶', 'nǎinai', 'nainai', 'bà nội', 'HSK 2'],
  ['小孩儿', 'xiǎoháir', 'xiaohair', 'trẻ nhỏ, con cái', 'HSK 2'],
  ['女孩儿', 'nǚháir', 'nvhair', 'bé gái, thiếu nữ', 'HSK 2'],
  ['男孩儿', 'nánháir', 'nanhair', 'bé trai, cậu con trai', 'HSK 2'],
  ['妻子', 'qīzi', 'qizi', 'vợ', 'HSK 2'],
  ['丈夫', 'zhàngfu', 'zhangfu', 'chồng', 'HSK 2'],
  ['礼物', 'lǐwù', 'liwu', 'món quà', 'HSK 2'],
  ['手表', 'shǒubiǎo', 'shoubiao', 'đồng hồ đeo tay', 'HSK 2'],
  ['花', 'huā', 'hua', 'hoa; tiêu, tốn', 'HSK 2'],
  ['咖啡', 'kāfēi', 'kafei', 'cà phê', 'HSK 2'],
  ['奶茶', 'nǎichá', 'naicha', 'trà sữa', 'HSK 2'],
  ['北京烤鸭', 'běijīng kǎoyā', 'beijing kaoya', 'vịt quay Bắc Kinh', 'HSK 2'],
  ['票', 'piào', 'piao', 'vé', 'HSK 2'],
  ['商场', 'shāngchǎng', 'shangchang', 'trung tâm thương mại', 'HSK 2'],
  ['药店', 'yàodiàn', 'yaodian', 'hiệu thuốc', 'HSK 2'],
  ['酒店', 'jiǔdiàn', 'jiudian', 'khách sạn', 'HSK 2'],
  ['车站', 'chēzhàn', 'chezhan', 'trạm xe, bến xe', 'HSK 2'],
  ['机场', 'jīchǎng', 'jichang', 'sân bay', 'HSK 2'],
  ['教室', 'jiàoshì', 'jiaoshi', 'phòng học, lớp học', 'HSK 2'],
  ['楼', 'lóu', 'lou', 'tòa nhà, tầng lầu', 'HSK 2'],
  ['房子', 'fángzi', 'fangzi', 'căn nhà, căn hộ', 'HSK 2'],
  ['北京大学', 'běijīng dàxué', 'beijing daxue', 'Đại học Bắc Kinh', 'HSK 2'],
  ['高中', 'gāozhōng', 'gaozhong', 'trường trung học phổ thông', 'HSK 2'],
  ['班', 'bān', 'ban', 'lớp học', 'HSK 2'],
  ['外国', 'wàiguó', 'waiguo', 'nước ngoài', 'HSK 2'],
  ['门口', 'ménkǒu', 'menkou', 'cửa ra vào, cổng', 'HSK 2'],
  ['外面', 'wàimiàn', 'waimian', 'bên ngoài', 'HSK 2'],
  ['外边', 'wàibian', 'waibian', 'bên ngoài', 'HSK 2'],
  ['里面', 'lǐmiàn', 'limian', 'bên trong', 'HSK 2'],
  ['里边', 'lǐbian', 'libian', 'bên trong', 'HSK 2'],
  ['上面', 'shàngmiàn', 'shangmian', 'phía trên, bề mặt', 'HSK 2'],
  ['前面', 'qiánmian', 'qianmian', 'phía trước', 'HSK 2'],
  ['左边', 'zuǒbian', 'zuobian', 'bên trái', 'HSK 2'],
  ['右边', 'yòubian', 'youbian', 'bên phải', 'HSK 2'],
  ['旁边', 'pángbiān', 'pangbian', 'bên cạnh', 'HSK 2'],
  ['路上', 'lùshang', 'lushang', 'trên đường', 'HSK 2'],
  ['路', 'lù', 'lu', 'con đường', 'HSK 2'],
  ['地铁', 'dìtiě', 'ditie', 'tàu điện ngầm', 'HSK 2'],
  ['公交车', 'gōngjiāochē', 'gongjiaoche', 'xe buýt', 'HSK 2'],
  ['机票', 'jīpiào', 'jipiao', 'vé máy bay', 'HSK 2'],
  ['门票', 'ménpiào', 'menpiao', 'vé vào cổng', 'HSK 2'],
  ['姓名', 'xìngmíng', 'xingming', 'họ tên', 'HSK 2'],
  ['网上', 'wǎngshàng', 'wangshang', 'trên mạng', 'HSK 2'],
  ['事情', 'shìqíng', 'shiqing', 'sự việc, chuyện', 'HSK 2'],
  ['意思', 'yìsi', 'yisi', 'ý, nghĩa', 'HSK 2'],
  ['爱情片', 'àiqíngpiàn', 'aiqingpian', 'phim tình cảm', 'HSK 2'],
  ['小时候', 'xiǎoshíhou', 'xiaoshihou', 'lúc nhỏ', 'HSK 2'],
  ['旅游', 'lǚyóu', 'lvyou', 'du lịch', 'HSK 2'],
  ['介绍', 'jièshào', 'jieshao', 'giới thiệu', 'HSK 2'],
  ['帮忙', 'bāngmáng', 'bangmang', 'giúp đỡ', 'HSK 2'],
  ['帮', 'bāng', 'bang', 'giúp', 'HSK 2'],
  ['给', 'gěi', 'gei', 'đưa, cho', 'HSK 2'],
  ['接', 'jiē', 'jie', 'đón', 'HSK 2'],
  ['送', 'sòng', 'song', 'đưa, tặng, tiễn', 'HSK 2'],
  ['拿', 'ná', 'na', 'lấy, cầm', 'HSK 2'],
  ['洗', 'xǐ', 'xi', 'rửa, gội, giặt', 'HSK 2'],
  ['等', 'děng', 'deng', 'đợi, chờ', 'HSK 2'],
  ['准备', 'zhǔnbèi', 'zhunbei', 'chuẩn bị', 'HSK 2'],
  ['教', 'jiāo', 'jiao', 'dạy', 'HSK 2'],
  ['告诉', 'gàosu', 'gaosu', 'nói cho biết, thông báo', 'HSK 2'],
  ['忘', 'wàng', 'wang', 'quên', 'HSK 2'],
  ['画', 'huà', 'hua', 'vẽ; bức tranh', 'HSK 2'],
  ['画画', 'huàhuà', 'huahua', 'vẽ tranh', 'HSK 2'],
  ['画笔', 'huàbǐ', 'huabi', 'bút màu, cọ vẽ', 'HSK 2'],
  ['过生日', 'guò shēngrì', 'guo shengri', 'đón sinh nhật', 'HSK 2'],
  ['过年', 'guònián', 'guonian', 'đón Tết', 'HSK 2'],
  ['上学', 'shàngxué', 'shangxue', 'đi học', 'HSK 2'],
  ['开学', 'kāixué', 'kaixue', 'khai giảng', 'HSK 2'],
  ['跑步', 'pǎobù', 'paobu', 'chạy bộ', 'HSK 2'],
  ['踢足球', 'tī zúqiú', 'ti zuqiu', 'đá bóng', 'HSK 2'],
  ['打篮球', 'dǎ lánqiú', 'da lanqiu', 'chơi bóng rổ', 'HSK 2'],
  ['篮球', 'lánqiú', 'lanqiu', 'bóng rổ', 'HSK 2'],
  ['足球', 'zúqiú', 'zuqiu', 'bóng đá', 'HSK 2'],
  ['球', 'qiú', 'qiu', 'bóng', 'HSK 2'],
  ['游泳', 'yóuyǒng', 'youyong', 'bơi lội', 'HSK 2'],
  ['跳舞', 'tiàowǔ', 'tiaowu', 'nhảy múa', 'HSK 2'],
  ['上网', 'shàngwǎng', 'shangwang', 'lên mạng', 'HSK 2'],
  ['走路', 'zǒulù', 'zoulu', 'đi bộ', 'HSK 2'],
  ['打车', 'dǎchē', 'dache', 'bắt taxi', 'HSK 2'],
  ['出国', 'chūguó', 'chuguo', 'đi nước ngoài', 'HSK 2'],
  ['出门', 'chūmén', 'chumen', 'ra khỏi nhà', 'HSK 2'],
  ['走', 'zǒu', 'zou', 'đi bộ', 'HSK 2'],
  ['跑', 'pǎo', 'pao', 'chạy', 'HSK 2'],
  ['游', 'yóu', 'you', 'bơi', 'HSK 2'],
  ['踢', 'tī', 'ti', 'đá', 'HSK 2'],
  ['笑', 'xiào', 'xiao', 'cười', 'HSK 2'],
  ['疼', 'téng', 'teng', 'đau', 'HSK 2'],
  ['动', 'dòng', 'dong', 'động, di chuyển', 'HSK 2'],
  ['试', 'shì', 'shi', 'thử', 'HSK 2'],
  ['懂', 'dǒng', 'dong', 'hiểu, biết', 'HSK 2'],
  ['打开', 'dǎkāi', 'dakai', 'mở', 'HSK 2'],
  ['打开礼物', 'dǎkāi lǐwù', 'dakai liwu', 'mở quà', 'HSK 2'],
  ['记得', 'jìde', 'jide', 'nhớ', 'HSK 2'],
  ['点', 'diǎn', 'dian', 'gọi món', 'HSK 2'],
  ['考', 'kǎo', 'kao', 'thi, kiểm tra', 'HSK 2'],
  ['考试', 'kǎoshì', 'kaoshi', 'kỳ thi, kiểm tra', 'HSK 2'],
  ['让', 'ràng', 'rang', 'bảo, khiến, cho phép', 'HSK 2'],
  ['开始', 'kāishǐ', 'kaishi', 'bắt đầu', 'HSK 2'],
  ['希望', 'xīwàng', 'xiwang', 'hy vọng', 'HSK 2'],
  ['可能', 'kěnéng', 'keneng', 'có lẽ, có thể', 'HSK 2'],
  ['过来', 'guòlái', 'guolai', 'đi đến đây', 'HSK 2'],
  ['过去', 'guòqù', 'guoqu', 'đi qua, quá khứ', 'HSK 2'],
  ['回来', 'huílái', 'huilai', 'quay lại đây', 'HSK 2'],
  ['回去', 'huíqù', 'huiqu', 'quay về', 'HSK 2'],
  ['进来', 'jìnlái', 'jinlai', 'vào đây', 'HSK 2'],
  ['进去', 'jìnqù', 'jinqu', 'đi vào', 'HSK 2'],
  ['出来', 'chūlái', 'chulai', 'đi ra đây', 'HSK 2'],
  ['出去', 'chūqù', 'chuqu', 'ra ngoài', 'HSK 2'],
  ['上来', 'shànglái', 'shanglai', 'lên đây', 'HSK 2'],
  ['上去', 'shàngqù', 'shangqu', 'đi lên', 'HSK 2'],
  ['下来', 'xiàlái', 'xialai', 'xuống đây', 'HSK 2'],
  ['下去', 'xiàqù', 'xiaqu', 'đi xuống', 'HSK 2'],
  ['起来', 'qǐlái', 'qilai', 'đứng dậy, bắt đầu', 'HSK 2'],
  ['错', 'cuò', 'cuo', 'sai', 'HSK 2'],
  ['不错', 'búcuò', 'bu cuo', 'không tệ, rất tốt', 'HSK 2'],
  ['舒服', 'shūfu', 'shufu', 'thoải mái, dễ chịu', 'HSK 2'],
  ['很舒服', 'hěn shūfu', 'hen shufu', 'rất thoải mái', 'HSK 2'],
  ['累', 'lèi', 'lei', 'mệt', 'HSK 2'],
  ['远', 'yuǎn', 'yuan', 'xa', 'HSK 2'],
  ['近', 'jìn', 'jin', 'gần', 'HSK 2'],
  ['慢', 'màn', 'man', 'chậm', 'HSK 2'],
  ['快', 'kuài', 'kuai', 'nhanh', 'HSK 2'],
  ['高', 'gāo', 'gao', 'cao', 'HSK 2'],
  ['个子', 'gèzi', 'gezi', 'dáng người, chiều cao', 'HSK 2'],
  ['晴', 'qíng', 'qing', 'nắng, trời quang', 'HSK 2'],
  ['阴', 'yīn', 'yin', 'âm u, nhiều mây', 'HSK 2'],
  ['快乐', 'kuàilè', 'kuaile', 'vui vẻ, hạnh phúc', 'HSK 2'],
  ['有意思', 'yǒu yìsi', 'you yisi', 'thú vị, có ý nghĩa', 'HSK 2'],
  ['没意思', 'méiyìsi', 'mei yisi', 'nhạt nhẽo, nhàm chán', 'HSK 2'],
  ['白色', 'báisè', 'baise', 'màu trắng', 'HSK 2'],
  ['红色', 'hóngsè', 'hongse', 'màu đỏ', 'HSK 2'],
  ['绿色', 'lǜsè', 'lvse', 'màu xanh lá', 'HSK 2'],
  ['黑色', 'hēisè', 'heise', 'màu đen', 'HSK 2'],
  ['颜色', 'yánsè', 'yanse', 'màu sắc', 'HSK 2'],
  ['长', 'cháng', 'chang', 'dài', 'HSK 2'],
  ['坏', 'huài', 'huai', 'xấu, hỏng', 'HSK 2'],
  ['就', 'jiù', 'jiu', 'chính là, liền', 'HSK 2'],
  ['正', 'zhèng', 'zheng', 'đang diễn ra', 'HSK 2'],
  ['已经', 'yǐjīng', 'yijing', 'đã', 'HSK 2'],
  ['经常', 'jīngcháng', 'jingchang', 'thường xuyên', 'HSK 2'],
  ['有时', 'yǒushí', 'youshi', 'có lúc, thỉnh thoảng', 'HSK 2'],
  ['最', 'zuì', 'zui', 'nhất', 'HSK 2'],
  ['更', 'gèng', 'geng', 'hơn, càng', 'HSK 2'],
  ['别', 'bié', 'bie', 'đừng', 'HSK 2'],
  ['还是', 'háishì', 'haishi', 'hay là, vẫn là', 'HSK 2'],
  ['快要', 'kuàiyào', 'kuaiyao', 'sắp', 'HSK 2'],
  ['这么', 'zhème', 'zheme', 'như thế này', 'HSK 2'],
  ['那么', 'nàme', 'name', 'thế thì, như thế kia', 'HSK 2'],
  ['这样', 'zhèyàng', 'zheyang', 'như thế này', 'HSK 2'],
  ['那样', 'nàyàng', 'nayang', 'như thế kia', 'HSK 2'],
  ['自己', 'zìjǐ', 'ziji', 'tự mình', 'HSK 2'],
  ['为什么', 'wèishénme', 'weishenme', 'tại sao', 'HSK 2'],
  ['从', 'cóng', 'cong', 'từ, bắt đầu từ', 'HSK 2'],
  ['往', 'wǎng', 'wang', 'hướng về', 'HSK 2'],
  ['离', 'lí', 'li', 'cách', 'HSK 2'],
  ['跟', 'gēn', 'gen', 'cùng, với', 'HSK 2'],
  ['比', 'bǐ', 'bi', 'so với, hơn', 'HSK 2'],
  ['但', 'dàn', 'dan', 'nhưng', 'HSK 2'],
  ['但是', 'dànshì', 'danshi', 'nhưng mà', 'HSK 2'],
  ['虽然', 'suīrán', 'suiran', 'mặc dù', 'HSK 2'],
  ['因为', 'yīnwèi', 'yinwei', 'bởi vì', 'HSK 2'],
  ['所以', 'suǒyǐ', 'suoyi', 'cho nên, vì thế', 'HSK 2'],
  ['着', 'zhe', 'zhe', 'trợ từ chỉ trạng thái tiếp diễn', 'HSK 2'],
  ['过', 'guo', 'guo', 'trợ từ chỉ kinh nghiệm đã qua', 'HSK 2'],
  ['地', 'de', 'de', 'trợ từ kết cấu trước động từ', 'HSK 2'],
  ['得', 'de', 'de', 'trợ từ kết cấu sau động từ', 'HSK 2'],
  ['吧', 'ba', 'ba', 'trợ từ ngữ khí đề xuất', 'HSK 2'],
  ['啊', 'a', 'a', 'trợ từ ngữ khí cuối câu', 'HSK 2'],
  ['万', 'wàn', 'wan', 'vạn, mười nghìn', 'HSK 2'],
  ['次', 'cì', 'ci', 'lần', 'HSK 2'],
  ['条', 'tiáo', 'tiao', 'lượng từ cho vật dài, hẹp', 'HSK 2'],
  ['张', 'zhāng', 'zhang', 'lượng từ cho vật phẳng', 'HSK 2'],
  ['辆', 'liàng', 'liang', 'lượng từ cho xe cộ', 'HSK 2'],
  ['间', 'jiān', 'jian', 'lượng từ cho phòng', 'HSK 2'],
  ['名', 'míng', 'ming', 'lượng từ cho người', 'HSK 2'],
  ['位', 'wèi', 'wei', 'lượng từ tôn kính cho người', 'HSK 2'],
  ['件', 'jiàn', 'jian', 'lượng từ cho quần áo, sự việc', 'HSK 2'],
  ['双', 'shuāng', 'shuang', 'đôi, cặp', 'HSK 2'],
  ['小时', 'xiǎoshí', 'xiaoshi', 'giờ, tiếng đồng hồ', 'HSK 2'],
  ['周', 'zhōu', 'zhou', 'tuần', 'HSK 2'],
  ['洗手间', 'xǐshǒujiān', 'xishoujian', 'nhà vệ sinh', 'HSK 2'],
  ['生日', 'shēngrì', 'shengri', 'sinh nhật', 'HSK 2'],
  ['包', 'bāo', 'bao', 'túi, bao', 'HSK 2'],
  ["矮","ǎi","ai","thấp","HSK 2"],
  ["爱好","àihào","aihao","sở thích","HSK 2"],
  ["安静","ānjìng","anjing","yên tĩnh","HSK 2"],
  ["把","bǎ","ba","cầm/nắm","HSK 2"],
  ["办法","bànfǎ","banfa","cách","HSK 2"],
  ["饱","bǎo","bao","no","HSK 2"],
  ["北方","běifāng","beifang","miền bắc","HSK 2"],
  ["被","bèi","bei","bị","HSK 2"],
  ["比较","bǐjiào","bijiao","tương đối","HSK 2"],
  ["比赛","bǐsài","bisai","thi đấu","HSK 2"],
  ["必须","bìxū","bixu","phải","HSK 2"],
  ["变化","biànhuà","bianhua","thay đổi","HSK 2"],
  ["表示","biǎoshì","biaoshi","biểu thị","HSK 2"],
  ["表演","biǎoyǎn","biaoyan","biểu diễn","HSK 2"],
  ["宾馆","bīnguǎn","binguan","khách sạn","HSK 2"],
  ["冰箱","bīngxiāng","bingxiang","tủ lạnh","HSK 2"],
  ["菜单","càidān","caidan","thực đơn","HSK 2"],
  ["参加","cānjiā","canjia","tham gia","HSK 2"],
  ["草","cǎo","cao","cỏ","HSK 2"],
  ["层","céng","ceng","tầng","HSK 2"],
  ["差","chà","cha","kém/sai","HSK 2"],
  ["超市","chāoshì","chaoshi","siêu thị","HSK 2"],
  ["衬衫","chènshān","chenshan","sơ mi","HSK 2"],
  ["成绩","chéngjì","chengji","thành tích","HSK 2"],
  ["城市","chéngshì","chengshi","thành phố","HSK 2"],
  ["程度","chéngdù","chengdu","mức độ","HSK 2"],
  ["迟到","chídào","chidao","đến muộn","HSK 2"],
  ["出现","chūxiàn","chuxian","xuất hiện","HSK 2"],
  ["厨房","chúfáng","chufang","nhà bếp","HSK 2"],
  ["除了","chúle","chule","ngoài... ra","HSK 2"],
  ["穿","chuān","chuan","mặc/xỏ","HSK 2"],
  ["船","chuán","chuan","thuyền","HSK 2"],
  ["打扫","dǎsǎo","dasao","dọn dẹp","HSK 2"],
  ["打算","dǎsuàn","dasuan","dự định","HSK 2"],
  ["带","dài","dai","mang theo","HSK 2"],
  ["担心","dānxīn","danxin","lo lắng","HSK 2"],
  ["当","dāng","dang","khi","HSK 2"],
  ["地方","dìfang","difang","nơi","HSK 2"],
  ["地图","dìtú","ditu","bản đồ","HSK 2"],
  ["电梯","diàntī","dianti","thang máy","HSK 2"],
  ["电子邮件","diànzǐ yóujiàn","dianzi youjian","thư điện tử","HSK 2"],
  ["东","dōng","dong","phía đông","HSK 2"],
  ["动物","dòngwù","dongwu","động vật","HSK 2"],
  ["短","duǎn","duan","ngắn","HSK 2"],
  ["段","duàn","duan","đoạn","HSK 2"],
  ["锻炼","duànliàn","duanlian","rèn luyện","HSK 2"],
  ["多么","duōme","duome","biết bao","HSK 2"],
  ["饿","è","e","đói","HSK 2"],
  ["耳朵","ěrduo","erduo","tai","HSK 2"],
  ["发","fā","fa","phát","HSK 2"],
  ["发现","fāxiàn","faxian","phát hiện","HSK 2"],
  ["方便","fāngbiàn","fangbian","tiện lợi","HSK 2"],
  ["放心","fàngxīn","fangxin","yên tâm","HSK 2"],
  ["分","fēn","fen","phút/điểm","HSK 2"],
  ["份","fèn","fen","suất/phần","HSK 2"],
  ["附近","fùjìn","fujin","gần đây","HSK 2"],
  ["复习","fùxí","fuxi","ôn tập","HSK 2"],
  ["干净","gānjìng","ganjing","sạch sẽ","HSK 2"],
  ["感兴趣","gǎn xìngqù","gan xingqu","hứng thú","HSK 2"],
  ["感觉","gǎnjué","ganjue","cảm thấy","HSK 2"],
  ["感冒","gǎnmào","ganmao","cảm cúm","HSK 2"],
  ["刚才","gāngcái","gangcai","vừa nãy","HSK 2"],
  ["根据","gēnjù","genju","căn cứ","HSK 2"],
  ["公共汽车","gōnggòng qìchē","gonggong qiche","xe buýt","HSK 2"],
  ["公园","gōngyuán","gongyuan","công viên","HSK 2"],
  ["故事","gùshi","gushi","câu chuyện","HSK 2"],
  ["刮风","guāfēng","guafeng","gió thổi","HSK 2"],
  ["关","guān","guan","đóng/tắt","HSK 2"],
  ["关系","guānxi","guanxi","quan hệ","HSK 2"],
  ["关心","guānxīn","guanxin","quan tâm","HSK 2"],
  ["关于","guānyú","guanyu","về","HSK 2"],
  ["国家","guójiā","guojia","quốc gia","HSK 2"],
  ["害怕","hàipà","haipa","sợ hãi","HSK 2"],
  ["河","hé","he","con sông","HSK 2"],
  ["黑板","hēibǎn","heiban","bảng đen","HSK 2"],
  ["后悔","hòuhuǐ","houhui","hối hận","HSK 2"],
  ["花园","huāyuán","huayuan","vườn hoa","HSK 2"],
  ["还","huán","huan","trả lại","HSK 2"],
  ["环境","huánjìng","huanjing","môi trường","HSK 2"],
  ["欢迎","huānyíng","huanying","chào mừng","HSK 2"],
  ["黄","huáng","huang","màu vàng","HSK 2"],
  ["会议","huìyì","huiyi","cuộc họp","HSK 2"],
  ["或者","huòzhě","huozhe","hoặc là","HSK 2"],
  ["几乎","jīhū","jihu","hầu như","HSK 2"],
  ["机会","jīhuì","jihui","cơ hội","HSK 2"],
  ["极","jí","ji","cực kỳ","HSK 2"],
  ["季节","jìjié","jijie","mùa","HSK 2"],
  ["检查","jiǎnchá","jiancha","kiểm tra","HSK 2"],
  ["简单","jiǎndān","jiandan","đơn giản","HSK 2"],
  ["见面","jiànmiàn","jianmian","gặp mặt","HSK 2"],
  ["健康","jiànkāng","jiankang","khỏe mạnh","HSK 2"],
  ["讲","jiǎng","jiang","giảng/nói","HSK 2"],
  ["街道","jiēdào","jiedao","đường phố","HSK 2"],
  ["节目","jiémù","jiemu","chương trình","HSK 2"],
  ["节日","jiérì","jieri","lễ hội","HSK 2"],
  ["结婚","jiéhūn","jiehun","kết hôn","HSK 2"],
  ["结束","jiéshù","jieshu","kết thúc","HSK 2"],
  ["解决","jiějué","jiejue","giải quyết","HSK 2"],
  ["借","jiè","jie","mượn","HSK 2"],
  ["经过","jīngguò","jingguo","đi ngang qua","HSK 2"],
  ["经理","jīnglǐ","jingli","giám đốc","HSK 2"],
  ["久","jiǔ","jiu","lâu","HSK 2"],
  ["决定","juédìng","jueding","quyết định","HSK 2"],
  ["看法","kànfǎ","kanfa","quan điểm","HSK 2"],
  ["渴","kě","ke","khát","HSK 2"],
  ["可爱","kě’ài","keai","đáng yêu","HSK 2"],
  ["空气","kōngqì","kongqi","không khí","HSK 2"],
  ["哭","kū","ku","khóc","HSK 2"],
  ["蓝","lán","lan","xanh dương","HSK 2"],
  ["老","lǎo","lao","già/cũ","HSK 2"],
  ["历史","lìshǐ","lishi","lịch sử","HSK 2"],
  ["脸","liǎn","lian","khuôn mặt","HSK 2"],
  ["练习","liànxí","lianxi","luyện tập","HSK 2"],
  ["两","liǎng","liang","hai","HSK 2"],
  ["了解","liǎojiě","liaojie","hiểu rõ","HSK 2"],
  ["邻居","línjū","linju","hàng xóm","HSK 2"],
  ["留","liú","liu","ở lại","HSK 2"],
  ["流利","liúlì","liuli","lưu loát","HSK 2"],
  ["旅行","lǚxíng","luxing","du lịch","HSK 2"],
  ["绿","lǜ","lu","xanh lá","HSK 2"],
  ["马","mǎ","ma","ngựa","HSK 2"],
  ["马上","mǎshàng","mashang","ngay lập tức","HSK 2"],
  ["满意","mǎnyì","manyi","hài lòng","HSK 2"],
  ["帽子","màozi","maozi","mũ","HSK 2"],
  ["面包","miànbāo","mianbao","bánh mì","HSK 2"],
  ["面条","miàntiáo","miantiao","sợi mì","HSK 2"],
  ["明白","míngbai","mingbai","hiểu rõ","HSK 2"],
  ["南","nán","nan","phía nam","HSK 2"],
  ["难","nán","nan","khó","HSK 2"],
  ["难过","nánguò","nanguo","buồn bã","HSK 2"],
  ["年轻","niánqīng","nianqing","trẻ trung","HSK 2"],
  ["鸟","niǎo","niao","con chim","HSK 2"],
  ["努力","nǔlì","nuli","cố gắng","HSK 2"],
  ["爬山","páshān","pashan","leo núi","HSK 2"],
  ["盘子","pánzi","panzi","cái đĩa","HSK 2"],
  ["胖","pàng","pang","béo","HSK 2"],
  ["皮鞋","píxié","pixie","giày da","HSK 2"],
  ["啤酒","píjiǔ","pijiu","bia","HSK 2"],
  ["便宜","piányi","pianyi","rẻ","HSK 2"],
  ["其实","qíshí","qishi","thực ra","HSK 2"],
  ["其他","qítā","qita","khác","HSK 2"],
  ["奇怪","qíguài","qiguai","kỳ lạ","HSK 2"],
  ["起床","qǐchuáng","qichuang","ngủ dậy","HSK 2"],
  ["千","qiān","qian","nghìn","HSK 2"],
  ["铅笔","qiānbǐ","qianbi","bút chì","HSK 2"],
  ["清楚","qīngchu","qingchu","rõ ràng","HSK 2"],
  ["秋天","qiūtiān","qiutian","mùa thu","HSK 2"],
  ["裙子","qúnzi","qunzi","váy","HSK 2"],
  ["然后","ránhòu","ranhou","sau đó","HSK 2"],
  ["热情","rèqíng","reqing","nhiệt tình","HSK 2"],
  ["认为","rènwéi","renwei","cho rằng","HSK 2"],
  ["认真","rènzhēn","renzhen","nghiêm túc","HSK 2"],
  ["容易","róngyì","rongyi","dễ dàng","HSK 2"],
  ["如果","rúguǒ","ruguo","nếu như","HSK 2"],
  ["散步","sànbù","sanbu","đi dạo","HSK 2"],
  ["上班","shàngbān","shangban","đi làm","HSK 2"],
  ["生病","shēngbìng","shengbing","sinh bệnh","HSK 2"],
  ["声音","shēngyīn","shengyin","âm thanh","HSK 2"],
  ["世界","shìjiè","shijie","thế giới","HSK 2"],
  ["手机","shǒujī","shouji","điện thoại","HSK 2"],
  ["它","tā","ta","nó","HSK 2"],
  ["提高","tígāo","tigao","nâng cao","HSK 2"],
  ["体育","tǐyù","tiyu","thể dục","HSK 2"],
  ["天空","tiānkōng","tiankong","bầu trời","HSK 2"],
  ["同意","tóngyì","tongyi","đồng ý","HSK 2"],
  ["头发","tóufa","toufa","tóc","HSK 2"],
  ["突然","tūrán","turan","đột nhiên","HSK 2"],
  ["图书馆","túshūguǎn","tushuguan","thư viện","HSK 2"],
  ["文化","wénhuà","wenhua","văn hóa","HSK 2"],
  ["问题","wèntí","wenti","vấn đề","HSK 2"],
  ["西","xī","xi","phía tây","HSK 2"],
  ["习惯","xíguàn","xiguan","thói quen","HSK 2"],
  ["洗澡","xǐzǎo","xizao","tắm","HSK 2"],
  ["夏天","xiàtiān","xiatian","mùa hè","HSK 2"],
  ["先","xiān","xian","trước","HSK 2"],
  ["相信","xiāngxìn","xiangxin","tin tưởng","HSK 2"],
  ["想法","xiǎngfǎ","xiangfa","ý nghĩ","HSK 2"],
  ["小心","xiǎoxīn","xiaoxin","cẩn thận","HSK 2"],
  ["新","xīn","xin","mới","HSK 2"],
  ["新闻","xīnwén","xinwen","tin tức","HSK 2"],
  ["信","xìn","xin","thư tay","HSK 2"],
  ["行","xíng","xing","được","HSK 2"],
  ["行李箱","xínglǐxiāng","xinglixiang","vali","HSK 2"],
  ["兴趣","xìngqù","xingqu","hứng thú","HSK 2"],
  ["熊猫","xióngmāo","xiongmao","gấu trúc","HSK 2"],
  ["需要","xūyào","xuyao","cần","HSK 2"],
  ["选择","xuǎnzé","xuanze","lựa chọn","HSK 2"],
  ["要求","yāoqiú","yaoqiu","yêu cầu","HSK 2"],
  ["一边","yìbiān","yibian","vừa... vừa","HSK 2"],
  ["一定","yídìng","yiding","nhất định","HSK 2"],
  ["一共","yígòng","yigong","tổng cộng","HSK 2"],
  ["一直","yìzhí","yizhi","suốt","HSK 2"],
  ["以前","yǐqián","yiqian","trước kia","HSK 2"],
  ["一样","yíyàng","yiyang","giống nhau","HSK 2"],
  ["一般","yìbān","yiban","thông thường","HSK 2"],
  ["一起","yìqǐ","yiqi","cùng nhau","HSK 2"],
  ["一些","yìxiē","yixie","một vài","HSK 2"],
  ["音乐","yīnyuè","yinyue","âm nhạc","HSK 2"],
  ["应该","yīnggāi","yinggai","nên","HSK 2"],
  ["影响","yǐngxiǎng","yingxiang","ảnh hưởng","HSK 2"],
  ["用","yòng","yong","sử dụng","HSK 2"],
  ["游戏","yóuxì","youxi","trò chơi","HSK 2"],
  ["有名","yǒumíng","youming","nổi tiếng","HSK 2"],
  ["遇到","yùdào","yudao","gặp phải","HSK 2"],
  ["愿意","yuànyì","yuanyi","sẵn lòng","HSK 2"],
  ["越","yuè","yue","càng","HSK 2"],
  ["运动","yùndòng","yundong","vận động","HSK 2"],
  ["再","zài","zai","lại","HSK 2"],
  ["在意","zàiyì","zaiyi","để tâm","HSK 2"],
  ["早上","zǎoshang","zaoshang","buổi sáng","HSK 2"],
  ["真","zhēn","zhen","thật","HSK 2"],
  ["正在","zhèngzài","zhengzai","đang","HSK 2"],
  ["知道","zhīdào","zhidao","biết","HSK 2"],
  ["最近","zuìjìn","zuijin","gần đây","HSK 2"],
  ["作业","zuòyè","zuoye","bài tập","HSK 2"],
  ["左右","zuǒyòu","zuoyou","khoảng","HSK 2"],
  ["中间","zhōngjiān","zhongjian","ở giữa","HSK 2"],
  ["爬","pá","pa","leo","HSK 2"],
  ["关门","guān mén","guan men","đóng cửa","HSK 2"],
  ["开门","kāi mén","kai men","mở cửa","HSK 2"],
  ["唱歌","chànggē","changge","hát","HSK 2"],
  ["读书","dúshū","dushu","đọc sách","HSK 2"],
  ["写字","xiězì","xiezi","viết chữ","HSK 2"],
  ["听课","tīngkè","tingke","nghe giảng","HSK 2"],
  ["做饭","zuòfàn","zuofan","nấu ăn","HSK 2"],
  ["买东西","mǎi dôngxi","mai dongxi","mua đồ","HSK 2"],
  ["卖东西","mài dôngxi","mai dongxi","bán đồ","HSK 2"],
  ["开车","kāichē","kaiche","lái xe","HSK 2"],
  ["坐车","zuòchē","zuoche","đi xe","HSK 2"],
  ["送给","sòng gěi","song gei","tặng cho","HSK 2"],
  ["找","zhǎo","zhao","tìm kiếm","HSK 2"],
  ["找到","zhǎodào","zhaodao","tìm thấy","HSK 2"],
  ["丢","diū","diu","đánh mất","HSK 2"],
  ["带来","dàilái","dailai","mang đến","HSK 2"],
  ["带走","dàizǒu","daizou","mang đi","HSK 2"],
  ["起","qǐ","qi","thức dậy/lên","HSK 2"],
  ["放","fàng","fang","đặt/để","HSK 2"],
  ["进","jìn","jin","vào trong","HSK 2"],
  ["出","chū","chu","ra ngoài","HSK 2"],
  ["起飞","qǐfēi","qifei","cất cánh","HSK 2"],
];
