import type { VocabularyEntry } from './hsk2-vocabulary';

export const hsk3Vocabulary: VocabularyEntry[] = [
  ["阿姨","āyí","ayi","cô, dì","HSK 3"],
  ["啊","a","a","à","HSK 3"],
  ["矮","ǎi","ai","thấp","HSK 3"],
  ["爱好","àihào","aihao","sở thích","HSK 3"],
  ["安静","ānjìng","anjing","yên tĩnh","HSK 3"],
  ["把","bǎ","ba","cầm/nắm","HSK 3"],
  ["班","bān","ban","lớp","HSK 3"],
  ["办法","bànfǎ","banfa","cách","HSK 3"],
  ["帮忙","bāngmáng","bangmang","giúp đỡ","HSK 3"],
  ["包","bāo","bao","túi","HSK 3"],
  ["饱","bǎo","bao","no","HSK 3"],
  ["北方","běifāng","beifang","miền bắc","HSK 3"],
  ["被","bèi","bei","bị","HSK 3"],
  ["比","bǐ","bi","so với","HSK 3"],
  ["比较","bǐjiào","bijiao","so sánh","HSK 3"],
  ["比赛","bǐsài","bisai","thi đấu","HSK 3"],
  ["必须","bìxū","bixu","phải","HSK 3"],
  ["变化","biànhuà","bianhua","thay đổi","HSK 3"],
  ["表示","biǎoshì","biaoshi","biểu thị","HSK 3"],
  ["表演","biǎoyǎn","biaoyan","biểu diễn","HSK 3"],
  ["别","bié","bie","đừng","HSK 3"],
  ["宾馆","bīnguǎn","binguan","khách sạn","HSK 3"],
  ["冰箱","bīngxiāng","bingxiang","tủ lạnh","HSK 3"],
  ["菜单","càidān","caidan","menu","HSK 3"],
  ["参加","cānjiā","canjia","tham gia","HSK 3"],
  ["草","cǎo","cao","cỏ","HSK 3"],
  ["层","céng","ceng","tầng","HSK 3"],
  ["差","chà","cha","kém","HSK 3"],
  ["超市","chāoshì","chaoshi","siêu thị","HSK 3"],
  ["衬衫","chènshān","chenshan","áo sơ mi","HSK 3"],
  ["成绩","chéngjì","chengji","thành tích","HSK 3"],
  ["城市","chéngshì","chengshi","thành phố","HSK 3"],
  ["程度","chéngdù","chengdu","mức độ","HSK 3"],
  ["迟到","chídào","chidao","đến muộn","HSK 3"],
  ["出现","chūxiàn","chuxian","xuất hiện","HSK 3"],
  ["厨房","chúfáng","chufang","nhà bếp","HSK 3"],
  ["除了","chúle","chule","ngoài ra","HSK 3"],
  ["穿","chuān","chuan","mặc","HSK 3"],
  ["船","chuán","chuan","thuyền","HSK 3"],
  ["次","cì","ci","lần","HSK 3"],
  ["从","cóng","cong","từ","HSK 3"],
  ["错","cuò","cuo","sai","HSK 3"],
  ["打扫","dǎsǎo","dasao","dọn dẹp","HSK 3"],
  ["打算","dǎsuàn","dasuan","dự định","HSK 3"],
  ["带","dài","dai","mang","HSK 3"],
  ["担心","dānxīn","danxin","lo lắng","HSK 3"],
  ["蛋糕","dàngāo","dangao","bánh","HSK 3"],
  ["当","dāng","dang","khi","HSK 3"],
  ["地","dì","di","đất","HSK 3"],
  ["地方","dìfang","difang","nơi","HSK 3"],
  ["地铁","dìtiě","ditie","tàu điện","HSK 3"],
  ["地图","dìtú","ditu","bản đồ","HSK 3"],
  ["电梯","diàntī","dianti","thang máy","HSK 3"],
  ["电子邮件","diànzǐ yóujiàn","dianzi youjian","email","HSK 3"],
  ["东","dōng","dong","phía đông","HSK 3"],
  ["动物","dòngwù","dongwu","động vật","HSK 3"],
  ["短","duǎn","duan","ngắn","HSK 3"],
  ["段","duàn","duan","đoạn","HSK 3"],
  ["锻炼","duànliàn","duanlian","tập luyện","HSK 3"],
  ["多么","duōme","duome","biết bao","HSK 3"],
  ["饿","è","e","đói","HSK 3"],
  ["耳朵","ěrduo","erduo","tai","HSK 3"],
  ["发","fā","fa","phát","HSK 3"],
  ["发现","fāxiàn","faxian","phát hiện","HSK 3"],
  ["方便","fāngbiàn","fangbian","tiện lợi","HSK 3"],
  ["放心","fàngxīn","fangxin","yên tâm","HSK 3"],
  ["分","fēn","fen","điểm","HSK 3"],
  ["份","fèn","fen","suất/phần","HSK 3"],
  ["附近","fùjìn","fujin","gần","HSK 3"],
  ["复习","fùxí","fuxi","ôn tập","HSK 3"],
  ["干净","gānjìng","ganjing","sạch sẽ","HSK 3"],
  ["感兴趣","gǎn xìngqù","gan xingqu","hứng thú","HSK 3"],
  ["感觉","gǎnjué","ganjue","cảm giác","HSK 3"],
  ["感冒","gǎnmào","ganmao","cúm","HSK 3"],
  ["刚才","gāngcái","gangcai","vừa nãy","HSK 3"],
  ["根据","gēnjù","genju","dựa vào","HSK 3"],
  ["更","gèng","geng","hơn","HSK 3"],
  ["公共汽车","gōnggòng qìchē","gonggong qiche","xe bus","HSK 3"],
  ["公园","gōngyuán","gongyuan","công viên","HSK 3"],
  ["故事","gùshi","gushi","câu chuyện","HSK 3"],
  ["刮风","guāfēng","guafeng","gió thổi","HSK 3"],
  ["关","guān","guan","đóng","HSK 3"],
  ["关系","guānxi","guanxi","quan hệ","HSK 3"],
  ["关心","guānxīn","guanxin","quan tâm","HSK 3"],
  ["关于","guānyú","guanyu","về","HSK 3"],
  ["国家","guójiā","guojia","quốc gia","HSK 3"],
  ["过去","guòqù","guoqu","quá khứ","HSK 3"],
  ["还是","háishì","haishi","hay là","HSK 3"],
  ["害怕","hàipà","haipa","sợ hãi","HSK 3"],
  ["河","hé","he","sông","HSK 3"],
  ["黑板","hēibǎn","heiban","bảng","HSK 3"],
  ["后悔","hòuhuǐ","houhui","hối hận","HSK 3"],
  ["花","huā","hua","tiền/hoa","HSK 3"],
  ["花园","huāyuán","huayuan","vườn","HSK 3"],
  ["画","huà","hua","vẽ","HSK 3"],
  ["坏","huài","huai","xấu","HSK 3"],
  ["还","huán","huan","trả lại","HSK 3"],
  ["环境","huánjìng","huanjing","môi trường","HSK 3"],
  ["欢迎","huānyíng","huanying","chào mừng","HSK 3"],
  ["黄","huáng","huang","vàng","HSK 3"],
  ["会议","huìyì","huiyi","họp","HSK 3"],
  ["或者","huòzhě","huozhe","hoặc","HSK 3"],
  ["几乎","jīhū","jihu","hầu như","HSK 3"],
  ["机会","jīhuì","jihui","cơ hội","HSK 3"],
  ["极","jí","ji","cực kỳ","HSK 3"],
  ["记得","jìde","jide","nhớ","HSK 3"],
  ["季节","jìjié","jijie","mùa","HSK 3"],
  ["检查","jiǎnchá","jiancha","kiểm tra","HSK 3"],
  ["简单","jiǎndān","jiandan","đơn giản","HSK 3"],
  ["见面","jiànmiàn","jianmian","gặp mặt","HSK 3"],
  ["健康","jiànkāng","jiankang","khỏe mạnh","HSK 3"],
  ["講","jiǎng","jiang","nói","HSK 3"],
  ["教","jiāo","jiao","dạy","HSK 3"],
  ["接","jiē","jie","nhận","HSK 3"],
  ["街道","jiēdào","jiedao","đường","HSK 3"],
  ["节目","jiémù","jiemu","chương trình","HSK 3"],
  ["节日","jiérì","jieri","lễ","HSK 3"],
  ["结婚","jiéhūn","jiehun","kết hôn","HSK 3"],
  ["结束","jiéshù","jieshu","kết thúc","HSK 3"],
  ["解决","jiějué","jiejue","giải quyết","HSK 3"],
  ["借","jiè","jie","mượn","HSK 3"],
  ["经常","jīngcháng","jingchang","thường xuyên","HSK 3"],
  ["经过","jīngguò","jingguo","trải qua","HSK 3"],
  ["经理","jīnglǐ","jingli","quản lý","HSK 3"],
  ["久","jiǔ","jiu","lâu","HSK 3"],
  ["决定","juédìng","jueding","quyết định","HSK 3"],
  ["开始","kāishǐ","kaishi","bắt đầu","HSK 3"],
  ["看法","kànfǎ","kanfa","quan điểm","HSK 3"],
  ["考试","kǎoshì","kaoshi","thi","HSK 3"],
  ["渴","kě","ke","khát","HSK 3"],
  ["可爱","kě’ài","keai","dễ thương","HSK 3"],
  ["可能","kěnéng","keneng","có thể","HSK 3"],
  ["空气","kōngqì","kongqi","không khí","HSK 3"],
  ["哭","kū","ku","khóc","HSK 3"],
  ["快","kuài","kuai","nhanh","HSK 3"],
  ["快乐","kuàilè","kuaile","vui","HSK 3"],
  ["裤子","kùzi","kuzi","quần","HSK 3"],
  ["蓝","lán","lan","xanh dương","HSK 3"],
  ["老","lǎo","lao","già","HSK 3"],
  ["离","lí","li","cách","HSK 3"],
  ["礼物","lǐwù","liwu","quà","HSK 3"],
  ["历史","lìshǐ","lishi","lịch sử","HSK 3"],
  ["脸","liǎn","lian","mặt","HSK 3"],
  ["练习","liànxí","lianxi","luyện tập","HSK 3"],
  ["两","liǎng","liang","hai","HSK 3"],
  ["了解","liǎojiě","liaojie","hiểu","HSK 3"],
  ["邻居","línjū","linju","hàng xóm","HSK 3"],
  ["留","liú","liu","ở lại","HSK 3"],
  ["流利","liúlì","liuli","lưu loát","HSK 3"],
  ["旅行","lǚxíng","luxing","du lịch","HSK 3"],
  ["绿","lǜ","lu","xanh lá","HSK 3"],
  ["马","mǎ","ma","ngựa","HSK 3"],
  ["马上","mǎshàng","mashang","ngay lập tức","HSK 3"],
  ["满意","mǎnyì","manyi","hài lòng","HSK 3"],
  ["帽子","màozi","maozi","mũ","HSK 3"],
  ["面包","miànbāo","mianbao","bánh mì","HSK 3"],
  ["面条","miàntiáo","miantiao","mì","HSK 3"],
  ["明白","míngbai","mingbai","hiểu","HSK 3"],
  ["拿","ná","na","cầm","HSK 3"],
  ["奶奶","nǎinai","nainai","bà nội","HSK 3"],
  ["南","nán","nan","phía nam","HSK 3"],
  ["难","nán","nan","khó","HSK 3"],
  ["难过","nánguò","nanguo","buồn bã","HSK 3"],
  ["年轻","niánqīng","nianqing","trẻ trung","HSK 3"],
  ["鸟","niǎo","niao","con chim","HSK 3"],
  ["努力","nǔlì","nuli","cố gắng","HSK 3"],
  ["爬山","páshān","pashan","leo núi","HSK 3"],
  ["盘子","pánzi","panzi","cái đĩa","HSK 3"],
  ["胖","pàng","pang","béo","HSK 3"],
  ["皮鞋","píxié","pixie","giày da","HSK 3"],
  ["啤酒","píjiǔ","pijiu","bia","HSK 3"],
  ["便宜","piányi","pianyi","rẻ","HSK 3"],
  ["票","piào","piao","vé","HSK 3"],
  ["妻子","qīzi","qizi","vợ","HSK 3"],
  ["其实","qíshí","qishi","thực ra","HSK 3"],
  ["其他","qítā","qita","khác","HSK 3"],
  ["奇怪","qíguài","qiguai","kỳ lạ","HSK 3"],
  ["起床","qǐchuáng","qichuang","ngủ dậy","HSK 3"],
  ["千","qiān","qian","nghìn","HSK 3"],
  ["铅笔","qiānbǐ","qianbi","bút chì","HSK 3"],
  ["清楚","qīngchu","qingchu","rõ ràng","HSK 3"],
  ["秋天","qiūtiān","qiutian","mùa thu","HSK 3"],
  ["裙子","qúnzi","qunzi","váy","HSK 3"],
  ["然后","ránhòu","ranhou","sau đó","HSK 3"],
  ["热情","rèqíng","reqing","nhiệt tình","HSK 3"],
  ["认为","rènwéi","renwei","cho rằng","HSK 3"],
  ["认真","rènzhēn","renzhen","nghiêm túc","HSK 3"],
  ["容易","róngyì","rongyi","dễ","HSK 3"],
  ["如果","rúguǒ","ruguo","nếu như","HSK 3"],
  ["散步","sànbù","sanbu","đi dạo","HSK 3"],
  ["上班","shàngbān","shangban","đi làm","HSK 3"],
  ["生病","shēngbìng","shengbing","ốm","HSK 3"],
  ["声音","shēngyīn","shengyin","âm thanh","HSK 3"],
  ["世界","shìjiè","shijie","thế giới","HSK 3"],
  ["事情","shìqing","shiqing","sự việc","HSK 3"],
  ["手表","shǒubiǎo","shoubiao","đồng hồ","HSK 3"],
  ["手机","shǒujī","shouji","điện thoại","HSK 3"],
  ["送","sòng","song","tặng","HSK 3"],
  ["虽然","suīrán","suiran","mặc dù","HSK 3"],
  ["所以","suǒyǐ","suoyi","nên","HSK 3"],
  ["它","tā","ta","nó","HSK 3"],
  ["踢足球","tī zúqiú","ti zuqiu","đá bóng","HSK 3"],
  ["提高","tígāo","tigao","nâng cao","HSK 3"],
  ["体育","tǐyù","tiyu","thể thao","HSK 3"],
  ["天空","tiānkōng","tiankong","bầu trời","HSK 3"],
  ["条","tiáo","tiao","lượng từ vật dài","HSK 3"],
  ["同意","tóngyì","tongyi","đồng ý","HSK 3"],
  ["头发","tóufa","toufa","tóc","HSK 3"],
  ["突然","tūrán","turan","đột nhiên","HSK 3"],
  ["图书馆","túshūguǎn","tushuguan","thư viện","HSK 3"],
  ["完","wán","wan","xong/hết","HSK 3"],
  ["完成","wánchéng","wancheng","hoàn thành","HSK 3"],
  ["玩","wán","wan","chơi","HSK 3"],
  ["晚","wǎn","wan","tối/muộn","HSK 3"],
  ["晚上","wǎnshang","wanshang","buổi tối","HSK 3"],
  ["忘记","wàngjì","wangji","quên","HSK 3"],
  ["为了","wèile","weile","để/vì","HSK 3"],
  ["为什么","wèishénme","weishenme","tại sao","HSK 3"],
  ["位","wèi","wei","vị","HSK 3"],
  ["文化","wénhuà","wenhua","văn hóa","HSK 3"],
  ["问题","wèntí","wenti","vấn đề","HSK 3"],
  ["洗","xǐ","xi","rửa/giặt","HSK 3"],
  ["西","xī","xi","phía tây","HSK 3"],
  ["希望","xīwàng","xiwang","hy vọng","HSK 3"],
  ["习惯","xíguàn","xiguan","thói quen","HSK 3"],
  ["洗澡","xǐzǎo","xizao","tắm","HSK 3"],
  ["夏天","xiàtiān","xiatian","mùa hè","HSK 3"],
  ["先","xiān","xian","trước","HSK 3"],
  ["相信","xiāngxìn","xiangxin","tin tưởng","HSK 3"],
  ["想法","xiǎngfǎ","xiangfa","ý tưởng","HSK 3"],
  ["小心","xiǎoxīn","xiaoxin","cẩn thận","HSK 3"],
  ["笑","xiào","xiao","cười","HSK 3"],
  ["新","xīn","xin","mới","HSK 3"],
  ["新闻","xīnwén","xinwen","tin tức","HSK 3"],
  ["信","xìn","xin","thư","HSK 3"],
  ["行","xíng","xing","được/ok","HSK 3"],
  ["行李箱","xínglǐxiāng","xinglixiang","vali","HSK 3"],
  ["兴趣","xìngqù","xingqu","hứng thú","HSK 3"],
  ["熊猫","xióngmāo","xiongmao","gấu trúc","HSK 3"],
  ["需要","xūyào","xuyao","cần","HSK 3"],
  ["选择","xuǎnzé","xuanze","lựa chọn","HSK 3"],
  ["要求","yāoqiú","yaoqiu","yêu cầu","HSK 3"],
  ["爷爷","yéye","yeye","ông nội","HSK 3"],
  ["一边","yìbiān","yibian","vừa... vừa","HSK 3"],
  ["一定","yídìng","yiding","nhất định","HSK 3"],
  ["一共","yígòng","yigong","tổng cộng","HSK 3"],
  ["一直","yìzhí","yizhi","suốt/luôn","HSK 3"],
  ["以前","yǐqián","yiqian","trước đây","HSK 3"],
  ["一样","yíyàng","yiyang","giống nhau","HSK 3"],
  ["一般","yìbān","yiban","thông thường","HSK 3"],
  ["一起","yìqǐ","yiqi","cùng nhau","HSK 3"],
  ["一些","yìxiē","yixie","một vài","HSK 3"],
  ["意思","yìsi","yisi","ý nghĩa","HSK 3"],
  ["阴","yīn","yin","âm u","HSK 3"],
  ["因为","yīnwèi","yinwei","bởi vì","HSK 3"],
  ["音乐","yīnyuè","yinyue","âm nhạc","HSK 3"],
  ["应该","yīnggāi","yinggai","nên","HSK 3"],
  ["影响","yǐngxiǎng","yingxiang","ảnh hưởng","HSK 3"],
  ["用","yòng","yong","sử dụng","HSK 3"],
  ["游戏","yóuxì","youxi","trò chơi","HSK 3"],
  ["游泳","yóuyǒng","youyong","bơi lội","HSK 3"],
  ["有名","yǒumíng","youming","nổi tiếng","HSK 3"],
  ["遇到","yùdào","yudao","gặp phải","HSK 3"],
  ["愿意","yuànyì","yuanyi","sẵn lòng","HSK 3"],
  ["越","yuè","yue","càng... càng","HSK 3"],
  ["运动","yùndòng","yundong","vận động","HSK 3"],
  ["再","zài","zai","lại","HSK 3"],
  ["在意","zàiyì","zaiyi","để tâm","HSK 3"],
  ["早上","zǎoshang","zaoshang","sáng sớm","HSK 3"],
  ["这样","zhèyàng","zheyang","như thế này","HSK 3"],
  ["真","zhēn","zhen","thật sự","HSK 3"],
  ["正在","zhèngzài","zhengzai","đang","HSK 3"],
  ["知道","zhīdào","zhidao","biết","HSK 3"],
  ["准备","zhǔnbèi","zhunbei","chuẩn bị","HSK 3"],
  ["走","zǒu","zou","đi bộ","HSK 3"],
  ["最","zuì","zui","nhất","HSK 3"],
  ["最近","zuìjìn","zuijin","gần đây","HSK 3"],
  ["作业","zuòyè","zuoye","bài tập","HSK 3"],
  ["左右","zuǒyòu","zuoyou","khoảng","HSK 3"],
  ["中间","zhōngjiān","zhongjian","ở giữa","HSK 3"],
  ["左边","zuǒbiān","zuobian","bên trái","HSK 3"],
  ["右边","yòubiān","youbian","bên phải","HSK 3"],
  ["爬","pá","pa","leo","HSK 3"],
  ["关门","guān mén","guan men","đóng cửa","HSK 3"],
  ["开门","kāi mén","kai men","mở cửa","HSK 3"],
  ["跑步","pǎobù","paobu","chạy bộ","HSK 3"],
  ["唱歌","chànggē","changge","hát","HSK 3"],
  ["跳舞","tiàowǔ","tiaowu","nhảy múa","HSK 3"],
  ["读书","dúshū","dushu","đọc sách","HSK 3"],
  ["写字","xiězì","xiezi","viết chữ","HSK 3"],
  ["听课","tīngkè","tingke","nghe giảng","HSK 3"],
  ["做饭","zuòfàn","zuofan","nấu ăn","HSK 3"],
  ["买东西","mǎi dōngxi","mai dongxi","mua đồ","HSK 3"],
  ["卖东西","mài dôngxi","mai dongxi","bán đồ","HSK 3"],
  ["开车","kāichē","kaiche","lái xe","HSK 3"],
  ["坐车","zuòchē","zuoche","đi xe","HSK 3"],
  ["等","děng","deng","chờ đợi","HSK 3"],
  ["送给","sòng gěi","song gei","tặng cho","HSK 3"],
  ["找","zhǎo","zhao","tìm kiếm","HSK 3"],
  ["找到","zhǎodào","zhaodao","tìm thấy","HSK 3"],
  ["丢","diū","diu","mất","HSK 3"],
  ["带来","dàilái","dailai","mang đến","HSK 3"],
  ["带走","dàizǒu","daizou","mang đi","HSK 3"],
  ["起","qǐ","qi","thức dậy/lên","HSK 3"],
  ["放","fàng","fang","đặt/thả","HSK 3"],
  ["进","jìn","jin","vào trong","HSK 3"],
  ["出","chū","chu","ra ngoài","HSK 3"],
  ["过","guò","guo","qua/băng qua","HSK 3"],
  ["起飞","qǐfēi","qifei","cất cánh","HSK 3"],
  ["降落","jiàngluò","jiangluo","hạ cánh","HSK 3"],
  ["司机","sījī","siji","tài xế","HSK 3"],
  ["护士","hùshi","hushi","y tá","HSK 3"],
  ["银行","yínháng","yinhang","ngân hàng","HSK 3"],
  ["公司","gōngsī","gongsi","công ty","HSK 3"],
  ["办公室","bàngōngshì","bangongshi","văn phòng","HSK 3"],
  ["同事","tóngshì","tongshi","đồng nghiệp","HSK 3"],
  ["老板","lǎobǎn","laoban","sếp","HSK 3"],
  ["客人","kèrén","keren","khách","HSK 3"],
  ["服务","fúwù","fuwu","phục vụ","HSK 3"],
  ["服务员","fúwùyuán","fuwuyuan","nhân viên phục vụ","HSK 3"],
  ["收入","shōurù","shouru","thu nhập","HSK 3"],
  ["花费","huāfèi","huafei","chi tiêu","HSK 3"],
  ["节省","jiéshěng","jiesheng","tiết kiệm","HSK 3"],
  ["价格","jiàgé","jiage","giá cả","HSK 3"],
  ["质量","zhìliàng","zhiliang","chất lượng","HSK 3"],
  ["合适","héshì","heshi","phù hợp","HSK 3"],
  ["麻烦","máfan","mafan","phiền phức","HSK 3"],
  ["迟","chí","chi","muộn","HSK 3"],
  ["早","zǎo","zao","sớm","HSK 3"],
  ["准时","zhǔnshí","zhunshi","đúng giờ","HSK 3"],
  ["安排","ānpái","anpai","sắp xếp","HSK 3"],
  ["计划","jìhuà","jihua","kế hoạch","HSK 3"],
  ["拒绝","jùjué","jujue","từ chối","HSK 3"],
  ["介绍","jièshào","jieshao","giới thiệu","HSK 3"],
  ["举行","jǔxíng","juxing","tổ chức","HSK 3"],
  ["开会","kāihuì","kaihui","họp","HSK 3"],
  ["讨论","tǎolùn","taolun","thảo luận","HSK 3"],
  ["说明","shuōmíng","shuoming","giải thích","HSK 3"],
  ["表达","biǎodá","biaoda","biểu đạt","HSK 3"],
  ["交流","jiāoliú","jiaoliu","giao tiếp","HSK 3"],
  ["理解","lǐjiě","lijie","hiểu","HSK 3"],
  ["记住","jìzhù","jizhu","ghi nhớ","HSK 3"],
  ["忘","wàng","wang","quên","HSK 3"],
  ["学会","xuéhuì","xuehui","học được","HSK 3"],
  ["发展","fāzhǎn","fazhan","phát triển","HSK 3"],
  ["改变","gǎibiàn","gaibian","thay đổi","HSK 3"],
  ["成功","chénggōng","chenggong","thành công","HSK 3"],
  ["失败","shībài","shibai","thất bại","HSK 3"],
  ["经验","jīngyàn","jingyan","kinh nghiệm","HSK 3"],
  ["重要","zhòngyào","zhongyao","quan trọng","HSK 3"],
  ["特别","tèbié","tebie","đặc biệt","HSK 3"],
  ["主要","zhǔyào","zhuyao","chủ yếu","HSK 3"],
  ["复杂","fùzá","fuza","phức tạp","HSK 3"],
  ["正确","zhèngquè","zhengque","chính xác","HSK 3"],
  ["错误","cuòwù","cuowu","sai lầm","HSK 3"],
  ["高兴","gāoxìng","gaoxing","vui vẻ","HSK 3"],
  ["生气","shēngqì","shengqi","tức giận","HSK 3"],
  ["紧张","jǐnzhāng","jinzhang","căng thẳng","HSK 3"],
  ["放松","fàngsōng","fangsong","thư giãn","HSK 3"],
  ["失望","shīwàng","shiwang","thất vọng","HSK 3"],
  ["兴奋","xīngfèn","xingfen","phấn khích","HSK 3"],
  ["天气","tiānqì","tianqi","thời tiết","HSK 3"],
  ["温度","wēndù","wendu","nhiệt độ","HSK 3"],
  ["阳光","yángguāng","yangguang","ánh nắng","HSK 3"],
  ["下雪","xiàxuě","xiaxue","tuyết rơi","HSK 3"],
  ["晴","qíng","qing","nắng","HSK 3"],
  ["阴天","yīntiān","yintian","âm u","HSK 3"],
  ["春天","chūntiān","chuntian","mùa xuân","HSK 3"],
  ["冬天","dōngtiān","dongtian","mùa đông","HSK 3"],
  ["时间","shíjiān","shijian","thời gian","HSK 3"],
  ["现在","xiànzài","xianzai","hiện tại","HSK 3"],
  ["将来","jiānglái","jianglai","tương lai","HSK 3"],
  ["已经","yǐjīng","yijing","đã","HSK 3"],
  ["爱情","àiqíng","aiqing","tình yêu","HSK 3"],
  ["按照","ànzhào","anzhao","theo","HSK 3"],
  ["安全","ānquán","anquan","an toàn","HSK 3"],
  ["表扬","biǎoyáng","biaoyang","khen","HSK 3"],
  ["表情","biǎoqíng","biaoqing","biểu cảm","HSK 3"],
  ["表面","biǎomiàn","biaomian","bề mặt","HSK 3"],
  ["表格","biǎogé","biaoge","bảng biểu","HSK 3"],
  ["表现","biǎoxiàn","biaoxian","thể hiện","HSK 3"],
  ["标准","biāozhǔn","biaozhun","tiêu chuẩn","HSK 3"],
  ["必要","bìyào","biyao","cần thiết","HSK 3"],
  ["毕业","bìyè","biye","tốt nghiệp","HSK 3"],
  ["变成","biànchéng","biancheng","trở thành","HSK 3"],
  ["便利","biànlì","bianli","thuận tiện","HSK 3"],
  ["保护","bǎohù","baohu","bảo vệ","HSK 3"],
  ["保证","bǎozhèng","baozheng","đảm bảo","HSK 3"],
  ["包括","bāokuò","baokuo","bao gồm","HSK 3"],
  ["报告","bàogào","baogao","báo cáo","HSK 3"],
  ["报名","bàomíng","baoming","đăng ký","HSK 3"],
  ["报纸","bàozhǐ","baozhi","báo","HSK 3"],
  ["帮助","bāngzhù","bangzhu","giúp","HSK 3"],
  ["比如","bǐrú","biru","ví dụ","HSK 3"],
  ["比例","bǐlì","bili","tỉ lệ","HSK 3"],
  ["别人","biérén","bieren","người khác","HSK 3"],
  ["并且","bìngqiě","bingqie","và","HSK 3"],
  ["不能","bùnéng","buneng","không thể","HSK 3"],
  ["不同","bùtóng","butong","khác nhau","HSK 3"],
  ["不用","búyòng","buyong","không cần","HSK 3"],
  ["不错","búcuò","bucuo","không tệ","HSK 3"],
  ["才","cái","cai","mới","HSK 3"],
  ["材料","cáiliào","cailiao","tài liệu","HSK 3"],
  ["参观","cānguān","canguan","tham quan","HSK 3"],
  ["操作","cāozuò","caozuo","thao tác","HSK 3"],
  ["曾经","céngjīng","cengjing","từng","HSK 3"],
  ["成为","chéngwéi","chengwei","trở thành","HSK 3"],
  ["成长","chéngzhǎng","chengzhang","trưởng thành","HSK 3"],
  ["诚实","chéngshí","chengshi","trung thực","HSK 3"],
  ["重新","chóngxīn","chongxin","lại","HSK 3"],
  ["出发","chūfā","chufa","xuất phát","HSK 3"],
  ["出口","chūkǒu","chukou","cửa ra","HSK 3"],
  ["出去","chūqù","chuqu","đi ra","HSK 3"],
  ["处理","chǔlǐ","chuli","xử lý","HSK 3"],
  ["传","chuán","chuan","truyền","HSK 3"],
  ["传统","chuántǒng","chuantong","truyền thống","HSK 3"],
  ["窗户","chuānghu","chuanghu","cửa sổ","HSK 3"],
  ["创造","chuàngzào","chuangzao","sáng tạo","HSK 3"],
  ["次要","cìyào","ciyao","thứ yếu","HSK 3"],
  ["聪明","cōngming","congming","thông minh","HSK 3"],
  ["从来","cónglái","conglai","từ trước đến nay","HSK 3"],
  ["达到","dádào","dadao","đạt được","HSK 3"],
  ["大家","dàjiā","dajia","mọi người","HSK 3"],
  ["大部分","dà bùfen","da bufen","phần lớn","HSK 3"],
  ["代表","dàibiǎo","daibiao","đại diện","HSK 3"],
  ["代替","dàitì","daiti","thay thế","HSK 3"],
  ["担任","dānrèn","danren","đảm nhiệm","HSK 3"],
  ["单位","dānwèi","danwei","đơn vị","HSK 3"],
  ["当时","dāngshí","dangshi","lúc đó","HSK 3"],
  ["当中","dāngzhōng","dangzhong","trong đó","HSK 3"],
  ["导致","dǎozhì","daozhi","dẫn đến","HSK 3"],
  ["到底","dàodǐ","daodi","rốt cuộc","HSK 3"],
  ["得到","dédào","dedao","nhận được","HSK 3"],
  ["等待","děngdài","dengdai","chờ","HSK 3"],
  ["低","dī","di","thấp","HSK 3"],
  ["底","dǐ","di","đáy","HSK 3"],
  ["地点","dìdiǎn","didian","địa điểm","HSK 3"],
  ["地区","dìqū","diqu","khu vực","HSK 3"],
  ["递","dì","di","đưa","HSK 3"],
  ["发生","fāshēng","fasheng","xảy ra","HSK 3"],
  ["发明","fāmíng","faming","phát minh","HSK 3"],
  ["方式","fāngshì","fangshi","cách thức","HSK 3"],
  ["方面","fāngmiàn","fangmian","phương diện","HSK 3"],
  ["方向","fāngxiàng","fangxiang","hướng","HSK 3"],
  ["放弃","fàngqì","fangqi","từ bỏ","HSK 3"],
  ["分别","fēnbié","fenbie","phân biệt","HSK 3"],
  ["分配","fēnpèi","fenpei","phân chia","HSK 3"],
  ["分析","fēnxī","fenxi","phân tích","HSK 3"],
  ["丰富","fēngfù","fengfu","phong phú","HSK 3"],
  ["否则","fǒuzé","fouze","nếu không","HSK 3"],
  ["负责","fùzé","fuze","phụ trách","HSK 3"],
  ["改善","gǎishàn","gaishan","cải thiện","HSK 3"],
  ["感情","gǎnqíng","ganqing","tình cảm","HSK 3"],
  ["感谢","gǎnxiè","ganxie","cảm ơn","HSK 3"],
  ["刚刚","gānggāng","ganggang","vừa mới","HSK 3"],
  ["高度","gāodù","gaodu","độ cao","HSK 3"],
  ["告诉","gàosu","gaosu","nói cho","HSK 3"],
  ["各种","gèzhǒng","gezhong","các loại","HSK 3"],
  ["根本","gēnběn","genben","căn bản","HSK 3"],
  ["更加","gèngjiā","gengjia","càng","HSK 3"],
  ["工具","gōngjù","gongju","công cụ","HSK 3"],
  ["共同","gòngtóng","gongtong","cùng","HSK 3"],
  ["贡献","gòngxiàn","gongxian","đóng góp","HSK 3"],
  ["购物","gòuwù","gouwu","mua sắm","HSK 3"],
  ["过程","guòchéng","guocheng","quá trình","HSK 3"],
  ["管理","guǎnlǐ","guanli","quản lý","HSK 3"],
  ["规定","guīdìng","guiding","quy định","HSK 3"],
  ["规划","guīhuà","guihua","quy hoạch","HSK 3"],
  ["果然","guǒrán","guoran","quả nhiên","HSK 3"],
  ["海外","hǎiwài","haiwai","nước ngoài","HSK 3"],
  ["行业","hángyè","hangye","ngành nghề","HSK 3"],
  ["合理","hélǐ","heli","hợp lý","HSK 3"],
  ["合作","hézuò","hezuo","hợp tác","HSK 3"],
  ["核心","héxīn","hexin","cốt lõi","HSK 3"],
  ["后来","hòulái","houlai","sau đó","HSK 3"],
  ["忽然","hūrán","huran","đột nhiên","HSK 3"],
  ["互联网","hùliánwǎng","hulianwang","internet","HSK 3"],
  ["互相","hùxiāng","huxiang","lẫn nhau","HSK 3"],
  ["话题","huàtí","huati","chủ đề","HSK 3"],
  ["活动","huódòng","huodong","hoạt động","HSK 3"],
  ["积极","jījí","jiji","tích cực","HSK 3"],
  ["基本","jīběn","jiben","cơ bản","HSK 3"],
  ["技术","jìshù","jishu","kỹ thuật","HSK 3"],
  ["继续","jìxù","jixu","tiếp tục","HSK 3"],
  ["记忆","jìyì","jiyi","trí nhớ","HSK 3"],
  ["加入","jiārù","jiaru","tham gia","HSK 3"],
  ["加强","jiāqiáng","jiaqiang","tăng cường","HSK 3"],
  ["家庭","jiātíng","jiating","gia đình","HSK 3"],
  ["建立","jiànlì","jianli","xây dựng","HSK 3"],
  ["建议","jiànyì","jianyi","đề xuất","HSK 3"],
  ["教育","jiàoyù","jiaoyu","giáo dục","HSK 3"],
  ["结果","jiéguǒ","jieguo","kết quả","HSK 3"],
  ["解释","jiěshì","jieshi","giải thích","HSK 3"],
  ["进步","jìnbù","jinbu","tiến bộ","HSK 3"],
  ["进行","jìnxíng","jinxing","tiến hành","HSK 3"],
  ["经济","jīngjì","jingji","kinh tế","HSK 3"],
  ["竞争","jìngzhēng","jingzheng","cạnh tranh","HSK 3"],
  ["精神","jīngshén","jingshen","tinh thần","HSK 3"],
  ["开发","kāifā","kaifa","phát triển","HSK 3"],
  ["开放","kāifàng","kaifang","mở cửa","HSK 3"],
  ["开展","kāizhǎn","kaizhan","triển khai","HSK 3"],
  ["科学","kēxué","kexue","khoa học","HSK 3"],
  ["克服","kèfú","kefu","vượt qua","HSK 3"],
  ["客户","kèhù","kehu","khách hàng","HSK 3"],
  ["空间","kōngjiān","kongjian","không gian","HSK 3"],
  ["控制","kòngzhì","kongzhi","kiểm soát","HSK 3"],
  ["困难","kùnnan","kunnan","khó khăn","HSK 3"],
  ["类似","lèisì","leisi","tương tự","HSK 3"],
  ["理想","lǐxiǎng","lixiang","lý tưởng","HSK 3"],
  ["利用","lìyòng","liyong","sử dụng","HSK 3"],
  ["联系","liánxì","lianxi","liên hệ","HSK 3"],
  ["连续","liánxù","lianxu","liên tục","HSK 3"],
  ["领导","lǐngdǎo","lingdao","lãnh đạo","HSK 3"],
  ["另外","lìngwài","lingwai","ngoài ra","HSK 3"],
  ["留下","liúxià","liuxia","ở lại","HSK 3"],
  ["领域","lǐngyù","lingyu","lĩnh vực","HSK 3"],
  ["判断","pànduàn","panduan","phán đoán","HSK 3"],
  ["培养","péiyǎng","peiyang","đào tạo","HSK 3"],
  ["评价","píngjià","pingjia","đánh giá","HSK 3"],
  ["平均","píngjūn","pingjun","trung bình","HSK 3"],
  ["情况","qíngkuàng","qingkuang","tình hình","HSK 3"],
  ["确定","quèdìng","queding","xác định","HSK 3"],
  ["任务","rènwù","renwu","nhiệm vụ","HSK 3"],
  ["任何","rènhé","renhe","bất kỳ","HSK 3"],
  ["设计","shèjì","sheji","thiết kế","HSK 3"],
  ["社会","shèhuì","shehui","xã hội","HSK 3"],
  ["生产","shēngchǎn","shengchan","sản xuất","HSK 3"],
  ["实际","shíjì","shiji","thực tế","HSK 3"],
  ["实现","shíxiàn","shixian","thực hiện","HSK 3"],
  ["使用","shǐyòng","shiyong","sử dụng","HSK 3"],
  ["思想","sīxiǎng","sixiang","tư tưởng","HSK 3"],
  ["提供","tígōng","tigong","cung cấp","HSK 3"],
  ["条件","tiáojiàn","tiaojian","điều kiện","HSK 3"],
];
