import type { VocabularyEntry } from './hsk2-vocabulary';

export const hsk4Vocabulary: VocabularyEntry[] = [
  ["唉","ài","ai","ối dào, chao ôi (thán từ tỏ ý thương cảm, thất vọng)","HSK 4"],
  ["爱情","àiqíng","aiqing","tình yêu","HSK 4"],
  ["暗","àn","an","tối","HSK 4"],
  ["安全","ānquán","anquan","an toàn","HSK 4"],
  ["安全带","ānquándài","anquandai","dây an toàn","HSK 4"],
  ["把","bǎ","ba","(xem phần ngữ pháp của bài)","HSK 4"],
  ["搬","bān","ban","chuyển dời","HSK 4"],
  ["扳","bān","ban","bấm, uốn, bẻ","HSK 4"],
  ["办理","bànlǐ","banli","làm","HSK 4"],
  ["抱","bào","bao","bế, ôm, ẵm","HSK 4"],
  ["杯子","bēizi","beizi","cái ly","HSK 4"],
  ["别人","biérén","bieren","người khác","HSK 4"],
  ["被","bèi","bei","bị, được","HSK 4"],
  ["背","bèi","bei","thuộc","HSK 4"],
  ["笨","bèn","ben","ngu ngốc, đần độn","HSK 4"],
  ["比","bǐ","bi","so với","HSK 4"],
  ["表现","biǎoxiàn","biaoxian","biểu hiện","HSK 4"],
  ["宾馆","bīnguǎn","binguan","sạn, nhà khách","HSK 4"],
  ["冰灯","bīngdēng","bingdeng","đăng, đèn băng","HSK 4"],
  ["冰雕","bīngdiāo","bingdiao","bức điêu khắc bằng băng","HSK 4"],
  ["兵马俑","bīngmǎyǒng","bingmayong","tượng binh mã","HSK 4"],
  ["冰箱","bīngxiāng","bingxiang","tủ lạnh","HSK 4"],
  ["不要紧","bú yàojǐn","buyaojin","không nghiêm trọng","HSK 4"],
  ["不好意思","bù hǎoyìsi","buhaoyisi","ngượng ngùng, ngại ngần","HSK 4"],
  ["不久","bùjiǔ","bujiu","lâu sau","HSK 4"],
  ["布置","bùzhì","buzhi","sắp xếp, trang trí, trang hoàng","HSK 4"],
  ["擦","cā","ca","lau, chùi","HSK 4"],
  ["猜","cāi","cai","đoán","HSK 4"],
  ["彩带","cǎidài","caidai","dây nơ, ruy băng","HSK 4"],
  ["彩灯","cǎidēng","caideng","đèn màu","HSK 4"],
  ["插头","chātóu","chatou","đầu cắm","HSK 4"],
  ["尝","cháng","chang","nếm, thưởng thức","HSK 4"],
  ["长久","chángjiǔ","changjiu","lâu dài","HSK 4"],
  ["乘","chéng","cheng","đáp","HSK 4"],
  ["成立","chénglì","chengli","thành lập","HSK 4"],
  ["抽","chōu","chou","bỏ ra (thời gian)","HSK 4"],
  ["抽烟","chōu yān","chouyan","hút thuốc","HSK 4"],
  ["出汗","chū hànvã","chuhanva","mồ hôi","HSK 4"],
  ["出门","chū mén","chumen","ra ngoài, ngoài đời","HSK 4"],
  ["船","chuán","chuan","thuyền","HSK 4"],
  ["传统","chuántóng","chuantong","truyền thống","HSK 4"],
  ["喘气","chuǎn qì","chuanqi","thở dốc, thở gấp","HSK 4"],
  ["窗","chuāng","chuang","cửa sổ","HSK 4"],
  ["窗户","chuānghu","chuanghu","cửa sổ","HSK 4"],
  ["吹","chuī","chui","nói phét, nói khoác","HSK 4"],
  ["春节","Chūn Jié","chunjie","Tết","HSK 4"],
  ["答应","dāying","daying","đồng ý, chấp thuận","HSK 4"],
  ["打扮","dǎban","daban","trang điểm, ăn mặc","HSK 4"],
  ["打的","dǎ dí","dadi","gọi taxi, đi taxi","HSK 4"],
  ["打扫","dǎsǎo","dasao","quét dọn, quét tước","HSK 4"],
  ["呆","dāi","dai","ở lại","HSK 4"],
  ["带","dài","dai","dây","HSK 4"],
  ["代替","dàitì","daiti","thay thế","HSK 4"],
  ["担心","dānxīn","danxin","lo lắng","HSK 4"],
  ["当","dāng","dang","làm","HSK 4"],
  ["倒","dǎo","dao","đổ, ngã","HSK 4"],
  ["倒","dào","dao","ngược","HSK 4"],
  ["到处","dàochù","daochu","khắp nơi, mọi nơi","HSK 4"],
  ["到底","dàodǐ","daodi","đến cùng","HSK 4"],
  ["……的话","... de huà","dehua","nếu (nhấn mạnh giả thiết)","HSK 4"],
  ["登机","dēng jī","dengji","lên máy bay","HSK 4"],
  ["登机牌","dēngjīpái","dengjipai","thẻ lên máy bay","HSK 4"],
  ["地位","dìwèi","diwei","địa vị","HSK 4"],
  ["地址","dìzhǐ","dizhi","địa chỉ","HSK 4"],
  ["点(菜)","diǎn","dian","(动)chọn, gọi món ăn","HSK 4"],
  ["电台","diàntái","diantai","đài (phát thanh)","HSK 4"],
  ["动","dòng","dong","nổi (bổ ngữ khả năng)","HSK 4"],
  ["动作","dòngzuò","dongzuo","động tác","HSK 4"],
  ["对","duì","dui","cặp, đôi","HSK 4"],
  ["对联","duìlián","duilian","câu đối","HSK 4"],
  ["饿","è","e","đói","HSK 4"],
  ["发","fā","fa","phát ra","HSK 4"],
  ["发生","fāshēng","fasheng","xảy ra","HSK 4"],
  ["罚","fá","fa","phạt","HSK 4"],
  ["放假","fàng jià","fangjia","(cho) nghỉ","HSK 4"],
  ["丰富","fēngfù","fengfu","phong phú","HSK 4"],
  ["风俗","fēngsú","fengsu","phong tục","HSK 4"],
  ["夫妻","fūqī","fuqi","vợ chồng","HSK 4"],
  ["夫人","fūrén","furen","vợ, phu nhân","HSK 4"],
  ["幅","fú","fu","bức","HSK 4"],
  ["福","fú","fu","chữ phúc","HSK 4"],
  ["扶","fú","fu","nâng, dìu, đỡ","HSK 4"],
  ["扶手","fúshǒu","fushou","vịn","HSK 4"],
  ["服装","fúzhuāng","fuzhuang","trang phục","HSK 4"],
  ["盖","gài","gai","xây dựng, xây","HSK 4"],
  ["干杯","gān bēi","ganbei","cạn ly","HSK 4"],
  ["敢","gǎn","gan","dám","HSK 4"],
  ["感动","gǎndòng","gandong","cảm động","HSK 4"],
  ["感情","gǎnqíng","ganqing","tình cảm","HSK 4"],
  ["感想","gǎnxiǎng","ganxiang","cảm nghĩ, cảm tưởng","HSK 4"],
  ["搞","gǎo","gao","làm","HSK 4"],
  ["告诉","gàosu","gaosu","bảo nói cho biết, báo","HSK 4"],
  ["公费","gōngfèi","gongfei","chi phí do nhà nước, công ty đài thọ","HSK 4"],
  ["估计","gūjì","guji","dự tính, tính toán","HSK 4"],
  ["古代","gǔdài","gudai","cổ đại","HSK 4"],
  ["骨头","gǔtou","gutou","xương","HSK 4"],
  ["故意","gùyì","guyi","cố ý","HSK 4"],
  ["管理","guǎnlǐ","guanli","quản lý","HSK 4"],
  ["管理员","guǎnlǐyuán","guanliyuan","người quản lý","HSK 4"],
  ["光","guāng","guang","hết, sạch, sạch trơn","HSK 4"],
  ["广播","guǎngbō","guangbo","phát thanh","HSK 4"],
  ["规矩","guīju","guiju","nề nếp, quy củ","HSK 4"],
  ["国际","guójì","guoji","quốc tế","HSK 4"],
  ["国外","guówài","guowai","nước ngoài","HSK 4"],
  ["过奖","guòjiǎng","guojiang","quá khen","HSK 4"],
  ["滚","gǔn","gun","lăn","HSK 4"],
  ["哈哈","hāhā","haha","(cười) hà hà","HSK 4"],
  ["汗","hàn","han","mồ hôi","HSK 4"],
  ["寒假","hánjià","hanjia","nghỉ đông","HSK 4"],
  ["行业","hángyè","hangye","ngành nghề","HSK 4"],
  ["好吃","hǎochī","haochi","ngon","HSK 4"],
  ["黑板","hēibǎn","heiban","bảng đen","HSK 4"],
  ["合同","hétong","hetong","hợp đồng","HSK 4"],
  ["合资","hézī","hezi","liên doanh","HSK 4"],
  ["胡说","húshuō","hushuo","nói bậy, nói nhảm","HSK 4"],
  ["花","huā","hua","tiêu (tiền), tốn (tiền)","HSK 4"],
  ["画报","huàbào","huabao","báo ảnh, họa báo","HSK 4"],
  ["画家","huàjiā","huajia","họa sĩ","HSK 4"],
  ["话剧","huàjù","huaju","kịch nói","HSK 4"],
  ["欢乐","huānlè","huanle","vui vẻ","HSK 4"],
  ["会场","huìchǎng","huichang","hội trường","HSK 4"],
  ["活","huó","huo","sống","HSK 4"],
  ["机场","jīchǎng","jichang","sân bay","HSK 4"],
  ["基础","jīchǔ","jichu","cơ sở, nền tảng","HSK 4"],
  ["积极","jījí","jiji","tích cực","HSK 4"],
  ["机票","jīpiào","jipiao","vé máy bay","HSK 4"],
  ["吉利","jíli","jili","may mắn","HSK 4"],
  ["吉祥","jíxiáng","jixiang","may mắn, cát tường","HSK 4"],
  ["系","jì","ji","cột, buộc, thắt","HSK 4"],
  ["计划","jìhuà","jihua","kế hoạch","HSK 4"],
  ["继续","jìxù","jixu","tiếp tục","HSK 4"],
  ["加油","jiā yóu","jiayou","cố lên","HSK 4"],
  ["甲","jiǎ","jia","nhất, đứng đầu","HSK 4"],
  ["简单","jiǎndān","jiandan","đơn giản","HSK 4"],
  ["建","jiàn","jian","xây dựng","HSK 4"],
  ["建议","jiànyì","jianyi","đề nghị, kiến nghị","HSK 4"],
  ["交流","jiāoliú","jiaoliu","giao lưu, trao đổi","HSK 4"],
  ["脚","jiǎo","jiao","chân","HSK 4"],
  ["叫","jiào","jiao","bị","HSK 4"],
  ["叫做","jiàozuò","jiaozuo","gọi là","HSK 4"],
  ["结","jiē","jie","kết, ra, có (trái)","HSK 4"],
  ["接着","jiēzhe","jiezhe","tiếp tục","HSK 4"],
  ["节日","jiérì","jieri","ngày lễ, ngày tết","HSK 4"],
  ["戒烟","jiè yān","jieyan","cai thuốc","HSK 4"],
  ["精彩","jīngcǎi","jingcai","đẹp mắt, hay, tuyệt vời","HSK 4"],
  ["惊喜","jīngxǐ","jingxi","kinh ngạc và vui mừng","HSK 4"],
  ["警察","jǐngchá","jingcha","cảnh sát","HSK 4"],
  ["敬酒","jìng jiǔ","jingjiu","mời rượu, chúc rượu","HSK 4"],
  ["纠正","jiūzhèng","jiuzheng","sửa chữa, uốn nắn","HSK 4"],
  ["句","jù","ju","câu","HSK 4"],
  ["剧场","jùchǎng","juchang","nhà hát","HSK 4"],
  ["决定","juédìng","jueding","quyết định","HSK 4"],
  ["开","kāi","kai","tổ chức","HSK 4"],
  ["开关","kāiguān","kaiguan","nút đóng mở, công tắc","HSK 4"],
  ["开玩笑","kāi wánxiào","kaiwanxiao","nói đùa, nói vui","HSK 4"],
  ["开演","kāiyǎn","kaiyan","bắt đầu diễn","HSK 4"],
  ["开展","kāizhǎn","kaizhan","triển khai","HSK 4"],
  ["看样子","kàn yàngzi","kanyangzi","xem ra, có vẻ như","HSK 4"],
  ["考察","kǎochá","kaocha","khảo sát","HSK 4"],
  ["棵","kē","ke","cây","HSK 4"],
  ["渴","kě","ke","khát","HSK 4"],
  ["可","kě","ke","cần, đáng","HSK 4"],
  ["可不是","kěbúshì","kebushi","chẳng phải, đúng thế","HSK 4"],
  ["可气","kěqì","keqi","đáng tức, bực mình","HSK 4"],
  ["肯定","kěndìng","kending","khẳng định, chắc chắn","HSK 4"],
  ["空","kōng","kong","không, rỗng, trống","HSK 4"],
  ["空姐","kōngjiě","kongjie","cô tiếp viên hàng không","HSK 4"],
  ["空调","kōngtiáo","kongtiao","máy điều hoà","HSK 4"],
  ["恐怕","kǒngpà","kongpa","e rằng, sợ rằng","HSK 4"],
  ["空儿","kòngr","kongr","rảnh","HSK 4"],
  ["困难","kùnnan","kunnan","khó khăn","HSK 4"],
  ["拉","lā","la","lôi, kéo","HSK 4"],
  ["辣子鸡丁","làzi jīdīng","lazijiding","gà xắt miếng xào ớt","HSK 4"],
  ["来往","láiwǎng","laiwang","qua lại","HSK 4"],
  ["缆车","lǎnchē","lanche","xe (/ca-bin) cáp treo, cáp treo","HSK 4"],
  ["浪费","làngfèi","langfei","lãng phí","HSK 4"],
  ["离开","líkāi","likai","rời, rời khỏi","HSK 4"],
  ["礼物","lǐwù","liwu","quà","HSK 4"],
  ["立即","lìjí","liji","lập tức","HSK 4"],
  ["连…也…","lián... yě...","lianye","ngay cả ... cũng","HSK 4"],
  ["联欢会","liánhuānhuì","lianhuanhui","hội (buổi) liên hoan","HSK 4"],
  ["脸谱","liǎnpǔ","lianpu","hóa trang mặt","HSK 4"],
  ["凉","liáng","liang","nguội","HSK 4"],
  ["了","liǎo","liao","rồi, xong","HSK 4"],
  ["了解","liǎojiě","liaojie","hiểu, tìm hiểu","HSK 4"],
  ["淋","lín","lin","ướt, bị ướt, xối ướt","HSK 4"],
  ["零下","língxià","lingxia","dưới không, âm","HSK 4"],
  ["领导","lǐngdǎo","lingdao","lãnh đạo, người lãnh đạo","HSK 4"],
  ["流","liú","liu","chảy","HSK 4"],
  ["路线","lùxiàn","luxian","tuyến đường","HSK 4"],
  ["落汤鸡","luòtāngjī","luotangji","(ướt như) chuột lột","HSK 4"],
  ["满","mǎn","man","đầy","HSK 4"],
  ["梅","méi","mei","(cây) mai","HSK 4"],
  ["面前","miànqián","mianqian","trước mặt","HSK 4"],
  ["民族","mínzú","minzu","dân tộc","HSK 4"],
  ["内容","nèiróng","neirong","nội dung","HSK 4"],
  ["农村","nóngcūn","nongcun","nông thôn","HSK 4"],
  ["哦","ò","o","ồ","HSK 4"],
  ["怕","pà","pa","sợ, sợ hãi","HSK 4"],
  ["排","pái","pai","hàng","HSK 4"],
  ["排练","páiliàn","pailian","dàn dựng và tập luyện","HSK 4"],
  ["骗","piàn","pian","lừa, gạt","HSK 4"],
  ["票","piào","piao","vé","HSK 4"],
  ["品尝","pǐncháng","pinchang","nếm, thưởng thức","HSK 4"],
  ["起飞","qǐfēi","qifei","cất cánh","HSK 4"],
  ["卡子","qiǎzi","qiazi","ổ kẹp, ổ bấm","HSK 4"],
  ["签","qiān","qian","ký","HSK 4"],
  ["钱包","qiánbāo","qianbao","ví tiền, bóp tiền","HSK 4"],
  ["巧克力","qiǎokèlì","qiaokeli","sôcôla","HSK 4"],
  ["亲手","qīnshǒu","qinshou","tận tay, tự tay","HSK 4"],
  ["情景","qíngjǐng","qingjing","tình huống, hoàn cảnh","HSK 4"],
  ["让","ràng","rang","bị","HSK 4"],
  ["人间","rénjiān","renjian","nhân gian","HSK 4"],
  ["人们","rénmen","renmen","mọi người","HSK 4"],
  ["人物","rénwù","renwu","nhân vật","HSK 4"],
  ["认识","rènshi","renshi","nhận biết, biết","HSK 4"],
  ["认为","rènwéi","renwei","cho rằng","HSK 4"],
  ["如果","rúguǒ","ruguo","nếu như, nếu","HSK 4"],
  ["洒","sǎ","sa","vẩy, rẩy, đổ toé","HSK 4"],
  ["沙发","shāfā","shafa","ghế xô pha","HSK 4"],
  ["傻","shǎ","sha","ngốc, dại","HSK 4"],
  ["山水","shānshuǐ","shanshui","sơn thủy, sông núi, phong cảnh","HSK 4"],
  ["伤","shāng","shang","bị thương, tổn thương","HSK 4"],
  ["上菜","shàng cài","shangcai","mang thức ăn lên","HSK 4"],
  ["上次","shàngcì","shangci","lần trước","HSK 4"],
  ["上街","shàng jiē","shangjie","ra phố, lên phố, đi phố","HSK 4"],
  ["上下班","shàng xiàbān","shangxiaban","vào ca và tan ca","HSK 4"],
  ["上座","shàngzuò","shangzuo","ghế trên","HSK 4"],
  ["烧","shāo","shao","đốt, cháy","HSK 4"],
  ["少数","shǎoshù","shaoshu","thiểu số","HSK 4"],
  ["少","shào","shao","trẻ","HSK 4"],
  ["舍不得","shěbude","shebude","không nỡ, không đành","HSK 4"],
  ["社会","shèhuì","shehui","xã hội","HSK 4"],
  ["身","shēn","shen","cơ thể, thân","HSK 4"],
  ["伸","shēn","shen","thò ra, giơ ra","HSK 4"],
  ["申请","shēnqǐng","shenqing","xin","HSK 4"],
  ["神话","shénhuà","shenhua","thần thoại","HSK 4"],
  ["声音","shēngyīn","shengyin","âm thanh","HSK 4"],
  ["圣诞节","Shèngdàn Jié","shengdanjie","Giáng sinh, Noel","HSK 4"],
  ["胜利","shènglì","shengli","thắng lợi","HSK 4"],
  ["湿","shī","shi","ướt","HSK 4"],
  ["十分","shífēn","shifen","vô cùng, rất","HSK 4"],
  ["十字路口","shí zì lùkǒu","shizilukou","ngã tư","HSK 4"],
  ["……似的","... de shìde","deshide","như, giống như","HSK 4"],
  ["世上","shìshàng","shishang","trên đời","HSK 4"],
  ["首","shǒu","shou","bài","HSK 4"],
  ["首都","shǒudū","shoudu","thủ đô","HSK 4"],
  ["首先","shǒuxiān","shouxian","trước hết","HSK 4"],
  ["手续","shǒuxù","shouxu","thủ tục","HSK 4"],
  ["受","shòu","shou","bị, chịu","HSK 4"],
  ["受骗","shòu piàn","shoupian","bị lừa, bị gạt","HSK 4"],
  ["受伤","shòu shāng","shoushang","bị thương","HSK 4"],
  ["叔叔","shūshu","shushu","chú","HSK 4"],
  ["熟","shú","shu","quen, thuộc","HSK 4"],
  ["数字","shùzì","shuzi","con số","HSK 4"],
  ["水仙","shuǐxiān","shuixian","(hoa) thủy tiên","HSK 4"],
  ["顺","shùn","shun","thuận lợi","HSK 4"],
  ["说明","shuōmíng","shuoming","thuyết minh, nói rõ","HSK 4"],
  ["说明书","shuōmíngshū","shuomingshu","bản thuyết minh","HSK 4"],
  ["司机","sījī","siji","lái xe, tài xế","HSK 4"],
  ["四合院","sìhéyuàn","siheyuan","nhà tứ hợp, tứ hợp viện","HSK 4"],
  ["松","sōng","song","(cây) tùng","HSK 4"],
  ["算命","suàn mìng","suanming","bói, đoán mệnh, coi số","HSK 4"],
  ["随便","suíbiàn","suibian","tùy tiện, tự nhiên, thoải mái","HSK 4"],
  ["岁寒三友","suì hán sān yǒu","suihansanyou","tuế hàn tam hữu (ba người bạn của tiết trời giá rét)","HSK 4"],
  ["它","tā","ta","nó","HSK 4"],
  ["台词","táicí","taici","lời kịch","HSK 4"],
  ["糖醋鱼","táng cù yú","tangcuyu","cá chua ngọt","HSK 4"],
  ["掏","tāo","tao","móc ra","HSK 4"],
  ["特色","tèsè","tese","đặc sắc, sắc thái riêng","HSK 4"],
  ["提","tí","ti","đưa ra","HSK 4"],
  ["体会","tíhuì","tihui","thể hội, lĩnh hội, hiểu","HSK 4"],
  ["天上","tiānshàng","tianshang","trên trời, thiên đình","HSK 4"],
  ["天堂","tiāntáng","tiantang","thiên đường","HSK 4"],
  ["天下","tiānxià","tianxia","thiên hạ","HSK 4"],
  ["甜","tián","tian","ngọt","HSK 4"],
  ["通","tōng","tong","thành thạo, tinh thông","HSK 4"],
  ["通过","tōngguò","tongguo","thông qua","HSK 4"],
  ["同意","tóngyì","tongyi","đồng ý","HSK 4"],
  ["偷","tōu","tou","ăn cắp, lấy trộm","HSK 4"],
  ["偷偷","tōutōu","toutou","lén","HSK 4"],
  ["透","tòu","tou","đẫm","HSK 4"],
  ["突然","tūrán","turan","đột ngột, đột nhiên","HSK 4"],
  ["图","tú","tu","tranh","HSK 4"],
  ["土豆","tǔdòu","tudou","khoai tây","HSK 4"],
  ["腿","tuǐ","tui","chân, đùi","HSK 4"],
  ["托运","tuōyùn","tuoyun","gửi vận chuyển","HSK 4"],
  ["外地","wàidì","waidi","ngoại tỉnh, nơi khác, địa phương khác","HSK 4"],
  ["弯","wān","wan","khom, cúi xuống","HSK 4"],
  ["玩笑","wánxiào","wanxiao","đùa","HSK 4"],
  ["危险","wēixiǎn","weixian","nguy hiểm","HSK 4"],
  ["伟大","wěidà","weida","vĩ đại, to lớn","HSK 4"],
  ["无","wú","wu","không có","HSK 4"],
  ["武打","wǔdǎ","wuda","đánh võ","HSK 4"],
  ["洗衣机","xǐyījī","xiyiji","máy giặt","HSK 4"],
  ["峡","xiá","xia","eo sông, eo (biển)","HSK 4"],
  ["下","xià","xia","xuống","HSK 4"],
  ["下次","xiàcì","xiaci","lần sau","HSK 4"],
  ["现代化","xiàndàihuà","xiandaihua","hiện đại hoá","HSK 4"],
  ["羡慕","xiànmù","xianmu","ngưỡng mộ","HSK 4"],
  ["仙女","xiānnǚ","xiannu","tiên nữ","HSK 4"],
  ["相信","xiāngxìn","xiangxin","tin tưởng","HSK 4"],
  ["响声","xiǎngshēng","xiangsheng","tiếng kêu, tiếng động","HSK 4"],
  ["相声","xiàngsheng","xiangsheng","tấu hài","HSK 4"],
  ["小区","xiǎoqū","xiaoqu","tiểu khu","HSK 4"],
  ["小偷","xiǎotōu","xiaotou","kẻ cắp","HSK 4"],
  ["小心","xiǎoxīn","xiaoxin","cẩn thận","HSK 4"],
  ["鞋","xié","xie","giày","HSK 4"],
  ["鞋带","xiédài","xiedai","dây giày","HSK 4"],
  ["谐音","xiéyīn","xieyin","hài âm (âm đọc giống hoặc gần giống)","HSK 4"],
  ["血","xiě","xie","máu","HSK 4"],
  ["心","xīn","xin","trái tim, tấm lòng","HSK 4"],
  ["新春","xīnchūn","xinchun","xuân mới","HSK 4"],
  ["新年","xīnnián","xinnian","năm mới","HSK 4"],
  ["兴旺","xīngwàng","xingwang","thịnh vượng, hưng thịnh","HSK 4"],
  ["行李","xíngli","xingli","hành lí","HSK 4"],
  ["幸福","xìngfú","xingfu","hạnh phúc","HSK 4"],
  ["性格","xìnggé","xingge","tính cách","HSK 4"],
  ["演","yǎn","yan","diễn, đóng","HSK 4"],
  ["演出","yǎnchū","yanchu","diễn xuất, biểu diễn","HSK 4"],
  ["演员","yǎnyuán","yanyuan","diễn viên","HSK 4"],
  ["宴会","yànhuì","yanhui","tiệc, yến tiệc","HSK 4"],
  ["样子","yàngzi","yangzi","dáng vẻ","HSK 4"],
  ["腰","yāo","yao","lưng","HSK 4"],
  ["邀请","yāoqǐng","yaoqing","mời","HSK 4"],
  ["要紧","yàojǐn","yaojin","nghiêm trọng, nặng","HSK 4"],
  ["业务","yèwù","yewu","nghiệp vụ, công việc","HSK 4"],
  ["一半","yíbàn","yiban","một nửa","HSK 4"],
  ["一定","yídìng","yiding","nhất định, chắc chắn","HSK 4"],
  ["遗憾","yíhàn","yihan","đáng tiếc, tiếc nuối","HSK 4"],
  ["一一下子","yíxiàzi","yixiazi","thoáng chốc","HSK 4"],
  ["椅子","yǐzi","yizi","(cái) ghế tựa","HSK 4"],
  ["一边…一边","yìbiān... yìbiān","yibianyibian","vừa... vừa...","HSK 4"],
  ["意见","yìjiàn","yijian","ý kiến","HSK 4"],
  ["艺术","yìshù","yishu","nghệ thuật","HSK 4"],
  ["音","yīn","yin","âm","HSK 4"],
  ["音响","yīnxiǎng","yinxiang","âm thanh","HSK 4"],
  ["影响","yǐngxiǎng","yingxiang","ảnh hưởng","HSK 4"],
  ["应","yìng","ying","nhận lời (mời)","HSK 4"],
  ["硬币","yìngbì","yingbi","tiền bằng kim loại","HSK 4"],
];
